packages/demo-cra/package.json, packages/demo-gatsby/package.json, packages/demo-next/package.json
`lerna version` doesn't update the dependencies of packages without
a version
=> build: fix updating demo deps when bumping versions

README.md
* Fix an error when setting up for the first time and running `npm run bootstrap` without first running `npm install`. 
> lerna ERR! ENOLERNA `lerna.json` does not exist, have you run `lerna init`?
* Correct path into demo folder
* Fix similar missing package error when running demo without first running npm install:
> Error: Unable to find plugin "gatsby-tinacms-json". Perhaps you need to install its package?
=> Add missing step & fix path in Readme "To get started"

packages/tinacms/src/components/FormView.tsx
While forms load the empty state is sometimes displayed. This adds an animation with a delay so that in the time it takes a form to load the empty state isn't visible. 
Closes #291
=> style: add fade in animation to empty state

packages/tinacms/src/plugins/fields/DateFieldPlugin.tsx
Displaying in the users timezone causes issues with the datepicker: https://github.com/tinacms/tinacms/issues/256
E.g When a user chooses Jan 26, it might then display Jan 25, or Jan 27 depending on the current time of day, and the browser's timezone setting. 
If a user wants to configure the display setting to use the user's timezone they can, but this will fix issues for the majority of users.
=> improvement: Use utc as default for datepicker

README.md, packages/@tinacms/core/src/cms-forms/form.ts, packages/@tinacms/form-builder/src/field-plugin.tsx, packages/@tinacms/form-builder/src/final-form-builder.tsx, packages/tinacms/src/plugins/fields/DateFieldPlugin.tsx, packages/tinacms/src/plugins/fields/dateFormat.test.ts, packages/tinacms/src/plugins/fields/dateFormat.ts
Fix for: https://github.com/tinacms/tinacms/issues/307 
Also:
- Uses 'format' from plugin if not set on field
- Adds "field" as a param for 'parse' & 'format'.
- Hides TimeFormat by default (because it's currently buggy, and will require more attention)
- Changes default date display to: MMM DD, YYYY
=> Date format fix

packages/@tinacms/fields/src/ImageUpload/ImageUpload.tsx, packages/@tinacms/styles/src/Button.tsx, packages/demo-gatsby/src/templates/blog-post.js, packages/tinacms/src/plugins/fields/ImageFieldPlugin.tsx
Improvement for: https://github.com/tinacms/tinacms/issues/190
Add a delete button to the image-upload. 
Also fixed the upload directory in the demo project, and made its parse handle a clearable image.
TODO:
=> Clearable Images

CONTRIBUTING.md
* switch branches where releases can be done from
* update `lcc` command and make sure it's installed
* release `from-package` instead of `from-git`
=> Update docs on releasing to npm

packages/tinacms/src/plugins/fields/BlocksFieldPlugin.tsx
Menu items are stacked horizontally so nothing after the first one is shown.
Before
After
=> fix: fix block menu not showing all items

packages/@tinacms/api-git/src/router.ts, packages/@tinacms/git-client/src/git-client.ts
closes #333 
<details><summary>Old Version (one endpoint)</summary>
This adds a branch API endpoint which returns a summary of branch information. The branch summary includes information about which branch is currently checked out, all available local branch names in a convenient array, and a dictionary to look up detailed information about each branch by name. The information for each branch includes the commit sha, the most recent commit message, and whether or not it is the current branch. There is also a `detached` flag which indicates whether the working copy is in a detached state. If we are detached, the detached commit is handled as an additional branch.
<details><summary>Screenshot</summary>
</details>
Here I have the `debugging-branch` branch checked out, and local branches …
=> feat(git): implement branch summary API

package.json
running `npm run nuke` deletes all the following from packages:
* node_modules
* build
* .rts2_cache
=> build: npm run nuke

CONTRIBUTING.md
`git push` does not push tags. Need to run `git push` to push changelog commits and `git push --tags` to push tags.
=> update release instructions

packages/@tinacms/core/package.json, packages/@tinacms/fields/package.json, packages/demo-cra/package.json, packages/gatsby-tinacms-git/package.json, packages/tinacms/package.json
Make sure all `tinacms/tinacms` packages declare `react` and `react-dom` as peer dependencies.
https://nodejs.org/en/blog/npm/peer-dependencies/#using-peer-dependencies
```json
"peerDependencies": {
"react": ">=16.8",
"react-dom": ">=16.8"
}
```
I chose `16.8` because we use React Hooks heavily, and that's the version where hooks were introduced.
What prompted me to look into this, was a issue #362. A similar change will probably have to be made for `styled-components`.
=> build: make react a peer dependency >=16.8

.github/workflows/release-canary.yml, packages/gatsby-plugin-tinacms/index.ts, packages/gatsby-tinacms-json/index.ts, packages/gatsby-tinacms-remark/index.ts
will happen on `master` and `canary` branches
canary versions could be installed like:
yarn add tinacms@canary
I'm not exactly sure how valuable this will be in practice. When deciding what to publish, lerna only looks at packages changed between `HEAD` and `HEAD~1`. If you changed `gatsby-tinacms-git` in this latest commit, and `gatsby-tinacms-remark` in the previous. It would only publish `gatsby-tinacms-git`.
My hope is that in merging a PR it will recognize all packages modified by that PR, not just the ones  modified in that PRs last commit.
P.S. I'm going to squash and merge this branch
=> build: attempt to publish canary releases

.eslintrc.json
https://github.com/tinacms/tinacms/issues/370#issuecomment-546142922
_According to @ncphillips:_
> we need to switch `"react-hooks/exhaustive-deps": "warn"` off entirely. It is a bad rule. The assumption that you want to re-run for all deps is just not correct. Doing so breaks tinacms, so until that's turned off please don't run the auto-fixer.
=> chore(linting): Turn off react-hooks/exhaustive-deps

packages/react-tinacms/src/use-plugin.tsx, packages/react-tinacms/src/with-plugin.tsx
```ts
function usePlugin(plugin: Plugin): void 
function withPlugin(component: any, plugin: Plugin): void 
```
The above functions accept a single Plugin or a list of Plugin.
```ts
function usePlugin(plugins: Plugin | Plugin[]): void 
function withPlugin(component: any, plugins: Plugin | Plugin[]): void 
```
There's also an alias that's pluralized:
```ts
function usePlugins(plugins: Plugin | Plugin[]): void 
function withPlugins(component: any, plugins: Plugin | Plugin[]): void 
```
**usePlugin•*
```js
export default function Layourt(props) {
usePlugins([
CreatePostPlugin,
CreateEventPlugin,
])
return <div>...</div>
}
```
**withPlugin**
```js
export default withPlugin(Layout, [
CreatePostPlugin,
CreateEventPlugin,
])
```
Right now if you want to include multiple plugins you need to wrap …
=> usePlugin accepts multiple plugins

packages/demo-gatsby/src/templates/blog-post.js, packages/tinacms/src/plugins/fields/BlocksFieldPlugin.tsx
Two features were added to Block templates in this PR:
* `itemProps` lets you programmatically set the `key` and `label`
* `defaultItem` can be a function
```javascript
const heading = {
label: "Heading",
defaultItem: {
text: "",
},
itemProps: block => ({
label: `${block.text}`,
}),
fields: [{ name: "text", component: "text", label: "Text" }],
}
const image = {
label: "Image",
defaultItem: () => ({
text: "",
}),
itemProps: block => ({
key: `${block.src}`,
label: `${block.alt}`,
}),
fields: [
{ name: "src", component: "text", label: "Source URL" },
{ name: "alt", component: "text", label: "Alt Text" },
],
}```
=> Blocks item props

dangerfile.ts
`tinacms` uses milestones to keep track of what will be published with a new release.
This update reminds the @tinacms/devs to add PRs to a milestone before merging.
=> build(danger): check for milestone

packages/gatsby-tinacms-remark/gatsby-node.js
On Windows the resolution for `fileRelativePath` was  incorrect because the 
`source.fileAbsolutePath` has been normalised to use forward slashes on both `win32` and `posix`.
So that it reads like
C:/project/tinacms/content/hello-world/index.md
To correctly calculate the relativePath, on windows, we need to turn `process.cwd()`
from 
C:\project\tinacms\
to
C:/project/tinacms/
=> Support Gatsby on Windows #382

packages/gatsby-tinacms-json/index.ts
=> gatsby-tinacms-json throws helpful errors if improperly configured

dangerfile.ts, packages/gatsby-tinacms-remark/src/create-remark-plugin.ts, packages/gatsby-tinacms-remark/src/index.ts, packages/gatsby-tinacms-remark/src/remark-creator-plugin.ts, packages/tinacms/src/plugins/create-content-form-plugin.ts
Deprecates `createRemarkButton` in favour of a class.
```
let PostCreatorPlugin = new RemarkCreatorPlugin({
// ...
})
```
Will require an update to the docs.
=> Add CreateRemarkPlugin class

packages/@tinacms/api-git/src/commit.ts
On Tina Teams, the push will fail unless we explicitly set the branchname
=> fix(git): set branchname on push (required for cloud pushes)

packages/@tinacms/fields/src/Wysiwyg/state/buildKeymap.ts
fixes #393
Keymaps were being added out of order
=> fix(wysiwyg): enter should split items

packages/gatsby-tinacms-json/src/use-json-form.ts
Updating `useJsonForm` to use the same label logic as `useRemarkForm`; look for a provided label first and use `fileRelativePath` as a fallback.
=> feat: use form options label when provided

packages/demo-gatsby/src/templates/blog-post.js, packages/gatsby-tinacms-remark/src/errors.ts, packages/gatsby-tinacms-remark/src/remark-fragment.ts
Adds 3 fields to MarkdownRemark queries:
* fileRelativePath
* rawFrontmatter
* rawMarkdownBody
Updated error messages accordingly
closes #442
=> feat(GraphQL): add TinaRemark fragment

packages/gatsby-tinacms-json/src/use-json-form.ts
useJsonForm was only writing out fields if they had
been queried for in the gatsby GraphQL query.
=> fix(useJsonForm): writes out all data Closes #450

packages/gatsby-tinacms-json/gatsby-node.js
The `fields` key in a node's top level is generated by plugins and shouldn't be persisted to the source file. When it is, aside from data corruption, Gatsby throws the following error:
```
gatsby-transformer-json" threw an error while running the onCreateNode lifecycle:
Plugins creating nodes can not set data on the reserved field "fields"
as this is reserved for plugins which wish to extend your nodes.
```
=> fix(json): don't leak 'fields' into rawJson

package-lock.json, packages/@tinacms/api-git/package-lock.json, packages/gatsby-tinacms-remark/package-lock.json, packages/tinacms/src/plugins/fields/MarkdownFieldPlugin.tsx
Simply adds `min-height`, `max-height`, & `overflow-y` properties on the markdown field. Partially addresses #230 - doesn't make it configurable, but I'm not sure how useful that would be given that most folks will probably gravitate towards inline editing.
=> Feat: Adds minmax height to markdown field

package-lock.json, package.json, packages/tinacms/src/plugins/fields/BlocksFieldPlugin.tsx
Render a placeholder block that can't be clicked into if a block item's `_template` field does not reference a known block type
=> fix(Blocks): add placeholder for invalid blocks

packages/react-tinacms/src/use-plugin.tsx
In UsePlugins, the pluginArray was empty during initial renders as the forms register. For some reason in brevifolia-next-tinacms, this was causing the useEffect hook to not fire since the number of array items changed. This fix ensures that there is always at least 1 item in the pluginArray so the hook will run. The plugin won't be added if its undefined or null.
=> Fix: Adjusts pluginArray to never be empty

packages/@tinacms/react-core/src/use-form.ts, packages/demo-gatsby/src/pages/index.js, packages/tinacms/src/react-tinacms/use-form.ts
```js
const [ values, form] = useGlobalForm({
id: "blog-index-styles",
label: "Blog Styles",
initialValues: {
backgroundColor: "",
hideBio: false,
date: "2019 03 04",
thumbnail: "",
},
fields: [
{
name: "backgroundColor",
label: "Heading Color",
component: "color",
colorFormat: "HeX",
},
{
name: "hideBio",
label: "Hide Bio",
component: "toggle",
},
{
name: "date",
label: "Date",
component: "date",
dateFormat: "YYYY MM DD",
timeFormat: null,
},
],
onSubmit() {
alert("Saving doesn't do anything.")
},
})
```
=> feat(useGlobalForm): add hook for registering global forms

dangerfile.ts, packages/demo-gatsby/src/templates/blog-post.js, packages/tinacms/src/components/Tina.tsx, packages/tinacms/src/index.ts
The `tinacms` package now re-exports the inputs from `@tinacms/fields` and the inline editing components from `@tinacms/form-builder`. Which means this:
```js
import { liveRemarkForm } from 'gatsby-tinacms-remark'
import { Wysiwyg } from '@tinacms/fields'
import { TinaField } from '@tinacms/form-builder'
const Template = ({ data, isEditing, setIsEditing }) => (
<TinaField name="rawMarkdownBody" Component={Wysiwyg}>
<section class="content" dangerouslySetInnerHTML={{ __html: data.markdownRemark.html }}></section>
<button onClick={() => setIsEditing(p => !p)}>{isEditing ? 'Preview' : 'Edit'}</button>
</TinaField>
)
export default liveRemarkForm(Template)
```
Can now be done like this:
```js
import { liveRemarkForm } from 'gatsby-tinacms-remark'
import { Wysiwyg } from 'tinacms'
const …
```
=> Refactor tinacms

packages/gatsby-tinacms-json/src/create-json-plugin.ts, packages/gatsby-tinacms-remark/src/remark-creator-plugin.ts, packages/tinacms/src/components/CreateContent.tsx, packages/tinacms/src/plugins/create-content-form-plugin.ts
Opt for more semantic name of plugin type, `content-creator` versus `content-button`.
=> other: renames type content-button --> content-creator

package-lock.json, package.json, packages/demo-gatsby/package.json, packages/demo-gatsby/src/templates/blog-post.js, packages/react-dismissible/package-lock.json, packages/react-tinacms-blocks/.gitignore, packages/react-tinacms-blocks/CHANGELOG.md, packages/react-tinacms-blocks/README.md, packages/react-tinacms-blocks/package-lock.json, packages/react-tinacms-blocks/package.json, packages/react-tinacms-blocks/src/blocks.spec.tsx, packages/react-tinacms-blocks/src/blocks.tsx, packages/react-tinacms-blocks/src/index.tsx, packages/react-tinacms-blocks/tsconfig.json, packages/tinacms/src/plugins/fields/BlocksFieldPlugin.tsx, packages/tinacms/src/plugins/fields/index.ts
`react-tinacms-blocks` provides a re-usable `Blocks` component that knows how to render data from the tinacms `BlocksFieldPlugin`. 
**Usage**
```js
import { Blocks } from "react-tinacms-blocks"
const PageBlogForm = {
// ...
}
export default remarkForm(function Page(props) {
const { frontmatter } = props.data.markdownRemark
return (
<Blocks 
name="rawFrontmatter.blocks"
data={props.data.markdownRemark} 
templates={{ heading, banner, content }}
/>
)
}, PageBlockForm)
```
**Test Output**
```
PASS  src/blocks.spec.tsx
Blocks
without data
✓ renders nothing into the containing element (2ms)
with some data
when there are no templates
✓ renders nothing into the containing element (1ms)
if (process.env.NODE_ENV === 'development')
✓ throws an error (3ms)
when there is a matching template
and it has …
```
=> New Package: react-tinacms-blocks

packages/demo-gatsby/src/components/blog-blocks.js, packages/demo-gatsby/src/templates/blog-post.js, packages/gatsby-tinacms-remark/src/remarkFormHoc.tsx, packages/react-tinacms-blocks/package.json, packages/react-tinacms-blocks/src/index.tsx, packages/react-tinacms-blocks/src/inline-blocks.tsx
Adds support for adding, removing, and moving blocks while editing content inline.
=> react-tinacms-blocks: Add support for inline editing

packages/@tinacms/react-core/src/use-form.ts
This behaviour should be implemented by wrapping functions
This will let people use Tina forms when `process.env.NODE_ENV==="production"`
=> fix(useForm): allow forms in production

packages/react-tinacms-blocks/src/blocks.tsx, packages/react-tinacms-blocks/src/inline-blocks.tsx
I've moved the defaulting behaviour for data & components inside the Blocks & EditableBlocks functions to prevent crashing when an empty value is passed.
=> fix(blocks): move defaults inside function

packages/tinacms/src/components/CreateContent.tsx
A small fix that I think adds to a more seamless UX. In the form modal, upon completion of a new blog post title, user can simply press their 'return' key to create new post rather than having to click (or tab to) 'create' button
=> feat: allow user to user enter/return key to create new blog entry

dangerfile.ts, packages/gatsby-tinacms-git/gatsby-browser.ts
I was reading through the dangerfile.ts and found a small typo in the` updateDocTitle` function parameter. I simply updated `chagnes` to `changes` to match the param naming convention seen in the rest of the file.
=> fix: fixed typo in dangerfile.ts

packages/@tinacms/form-builder/src/Form.tsx
I added proptypes to `TinaField` in order to improve the error message displayed when the `Component` prop is missing.
Now displays:
```
Warning: Failed prop type: The prop `Component` is marked as required in `y`, but its value is `undefined`.
```
Resolves https://github.com/tinacms/tinacms/issues/241
=> chore: better error messages for tinafield

packages/@tinacms/api-git/src/router.test.ts, packages/@tinacms/api-git/src/router.ts
fixes #596
The Git API was failing to start for repositories without remotes.
=> fix: server should start without an origin

packages/gatsby-tinacms-json/src/use-json-form.ts, packages/gatsby-tinacms-remark/src/useRemarkForm.tsx
Gatsby occasionally sends the browser null values when it's updating it's database, which russells Tina's jimmies. 
This PR makes Tina ignore those null values and just keep using the last valid query result. 
Potentially addresses #611 and #534
=> fix: disregard intermittent null vals from gatsby

packages/@tinacms/api-git/src/router.ts, packages/demo-gatsby/src/components/bio.js
Possible fix for several reports
There are three pieces to this bug.
First, on windows path's can contain forward slashes, or
double back slashes. For example
data/author.json
or
data\\author.json
Second, Node's `path.join` returns the second on Windows.
Third, the `git show` command behaves oddly with the former:
git show HEAD:data/author.json
Returns the contents of the file
git show HEAD:data/dne.json
Throws an error, and finally
git show HEAD:data\\author.json
returns an empty string.
This very well may be a bug in Git. I'm not sure.
=> Fix @tinacms/api-git `/show/:path` endpoint

packages/@tinacms/fields/src/Wysiwyg/plugins/keymap.ts
Wysiwyg was crashing when using arrows to move around in the document. Turns out we weren't accessing Selection. 
Don't cast to `any`.
=> fix(wysiwyg): prevent selection crash from arrows

packages/next-tinacms-json/package.json
If a package is a plugin for another package, then the parent should be a peerDep
This PR corrects that issue for `next-tinacms-json`
=> fix(deps): tinacms, react, and next are peerDeps

RELEASE.md
Added a section to `RELEASE.md` showing commands for listing contributors. Could be useful for newsletters or other places we might want to give kudos.
* https://codeinthehole.com/tips/command-line-tips-for-effective-release-announcements/#summarising-changes
=> docs(release): add section to list contributors

packages/tinacms/src/components/Tina.tsx, packages/tinacms/src/components/sidebar/Sidebar.tsx, packages/tinacms/src/components/sidebar/SidebarProvider.tsx, packages/tinacms/src/tina-cms.ts
Looking for everyone's thoughts on this. 
I started mulling over the Sidebar state after checking out @weibenfalk's thoughts on configuring the text on the Save/Reset buttons.
This change reifies the sidebar state and places it on the TinaCMS class as a property. I think this approach has a couple benefits:
1. The API feels more righter
1. It removes the need for the `SidebarContext` in the React app, instead relying on the pre-existinig CMSContext. 
Here is how it would be used.
cms.sidebar.isOpen
cms.sidebar.isOpen = true
import { useCMS, useSubscribable } from "tinacms"
const cms = useCMS()
useSubscribable(cms.sidebar)
const sidebar = useSidebar()
=> refactor(sidebar state): moved onto TinaCMS

packages/gatsby-tinacms-remark/package.json, packages/gatsby-tinacms-remark/src/remarkFormHoc.tsx
This PR fixes a couple things
* `gatsby-tinacms-remark` is a plugin for `tinacms` and should therefore have it as a `peerDependency`. This will not break anything for existing users since `gatsby-plugin-tinacms` depends directly on `tinacms`.
* `js-yaml` wasn't listed as a dependency
=> Fix gatsby tinacms remark deps

dangerfile.ts
Fine tuning the config for depcheck
Once things are really ironed out I'm going to switch it from a warning to a failure
=> build(danger): ignore more development deps

CONTRIBUTING.md
For dealing with the following error
Failed to Compile: Module not found: Can't resolve some-tinacms-package
=> docs(development): failed to compile section

packages/@tinacms/core/src/cms.test.ts, packages/@tinacms/core/src/cms.ts, packages/demo-next/pages/_app.js, packages/tinacms/package.json, packages/tinacms/src/react-tinacms/index.ts, packages/tinacms/src/react-tinacms/with-tina.tsx, packages/tinacms/src/tina-cms.ts
This PR aims to improve the DX of bootstrapping Tina on a project by doing the following: 
1. introduce a higher-order component `withTina` to wrap a component with the `<Tina>` CMS provider
2. Allow configuration of CMS/plugins more declaratively by passing a config object to the `TinaCMS` class. Since using the HOC option no longer gives you access to the CMS instance up front this also provides us with a way to configure the CMS by passing this information to the HOC as well.
Consider the current Next.js example of boostrapping Tina in `_app.js`:
```javascript
import React from 'react'
import App from 'next/app'
import { Tina, TinaCMS } from 'tinacms'
import { GitClient } from '@tinacms/git-client'
class MyApp extends App {
constructor() {
super()
this.cms = new TinaCMS()
const client …
```
=> withTina HOC

packages/react-tinacms-inline/package.json
`InlineForm` will only work with `tincms >= 13`
=> fix(react-tinacms-inline): update tinacms peer dep to >=13

packages/react-tinacms-inline/package.json
```
lerna info versioning independent
lerna info Bootstrapping 26 packages
lerna WARN EHOIST_ROOT_VERSION The repository root depends on @types/jest@^24.0.25, which differs from the more common @types/jest@^24.0.23.
lerna WARN EHOIST_PKG_VERSION "react-tinacms-inline" package depends on @types/jest@^24.0.23, which differs from the hoisted @types/jest@^24.0.25.
```
```
lerna info Bootstrapping 26 packages
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
````
=> fix: lerna warning on react-tinacms-inline package

packages/@tinacms/react-core/src/use-form.ts
`useForm` no longer passes `loadInitialValues` to `Form` constructor.
It instead handles that and calls it safely inside a `useEffect`.
=> chore: in react loadInitialVaues with useEffect

package-lock.json, packages/demo-gatsby/content/about.mdx, packages/demo-gatsby/src/pages/about.js, packages/gatsby-tinacms-mdx/gatsby-node.js, packages/gatsby-tinacms-mdx/package-lock.json, packages/gatsby-tinacms-mdx/package.json, packages/gatsby-tinacms-mdx/src/errors.ts, packages/gatsby-tinacms-mdx/src/generate-fields.ts, packages/gatsby-tinacms-mdx/src/mdx-creator-plugin.ts, packages/gatsby-tinacms-mdx/src/mdx-fragment.ts, packages/gatsby-tinacms-mdx/src/mdx-node.ts, packages/gatsby-tinacms-mdx/src/to-mdx.ts, packages/gatsby-tinacms-mdx/src/useMdxForm.tsx
I've updated this branch with changes that were made in the remark plugin
I've also changed references to 'markdown' because mdx is not markdown and will break if it isn't valid.
Still working on a fix for validation
=> Updates in line with inline updates

.github/workflows/main.yml
fixes #751
Only execute `npm run lint` on ubuntu
The linting job currently runs 3 times. Once for Mac, Ubuntu, and Windows. This results in a 3x as many linting warnings as is necessary. This PR will reduce noise from our CI, and also make it run a tiny bit faster.
=> build: only lint once

packages/tinacms/src/components/FormView.tsx
A crack at fixing #778. In a nutshell, the callback passed to `useSubscribable` was only being called after navigating to a new page, or some other update. So I added an initial `useEffect` to set the active form on first render. Also, the form list will only render when there are multiple forms, and if no active form is set, but there is a form on the cms, nothing will render until the active form is set. Did some testing in the `gatsby-demo` and it seems to work but feel free to poke holes.
We still have the multiple form issue - https://github.com/tinacms/tinacms/issues/438... and essentially the form almost always behaves as if there is only one on first go.
=> fix(tinacms): if single form, FormView no longer renders form list

packages/@tinacms/fields/package.json, packages/gatsby-tinacms-mdx/package.json
- Fix DangerJS warning on `@tinacms/fields` package
- Fix Lerna warnings on `gatsby-tinacms-mdx` package
=> deps: Fix warnings

packages/@tinacms/api-git/src/router.ts
There was an API change in `@tinacms/api-git#router`. It was accounted for in the gatsby plugin but not for Next. This adds a warning about that and updates the `demo-next`.
=> @tincams/api-git warns about missing Repo

packages/demo-gatsby/data/author.json, packages/tinacms/src/plugins/fields/BlocksFieldPlugin.tsx, packages/tinacms/src/plugins/fields/GroupListFieldPlugin.tsx
Fix #756 
Changed spelling from  "There's no items" to  "There are no items
=> fix spelling in case of no items

packages/demo-gatsby/gatsby-config.js
This is likely causing some weird bugs in the gatsby demo, I suspect it is the cause of #783
=> chore: avoid double-sourcing content in gats demo

packages/demo-next/pages/index.js, packages/tinacms/src/plugins/screen-plugin.tsx, packages/tinacms/src/react-tinacms/use-screen-plugin.tsx
Creating reusable screens is a bit benedict cumbersome at the moment. This PR aims to address this by introducing two new functions:
* `createScreen` a function for creating screen plugin objects, and
* `useScreenPlugin` a function that calls memos a call to `createScreen` and registers the plugin.
=> feat: useScreenPlugin

packages/next-tinacms-json/src/use-json-form.ts
Similar to #790
Risk of writing to wrong file becuase writeToDisk would not update
if the fileRelativePath was changed, thus always writing to the first
file that was encountered.
=> fix(useJsonForm): update writeToDisk when file is changed

packages/@tinacms/api-git/src/configure.ts, packages/@tinacms/api-git/src/repo.ts
This was happening when opening repo. It was
only for the sake of cloud editing environments.
Now, we will issue that warning in the repo configuration phase.
=> fix(repo): issue missing ssh_key warning in setup

packages/react-tinacms-inline/src/inline-form.tsx
This can be used to make the page editable immediately upon rendering.
```js
<InlineForm form={form} initialStatus="active">
<h1><InlineText name="title" /></h1>
</InlineForm>
```
=> feat(InlineForm): accept optional defaultStatus

.github/ISSUE_TEMPLATE/config.yml
This was still pointing to the old website repository. This makes it point to the correct one
=> fix: this was still pointing to the old website repo

dangerfile.ts
The file link was still pointing to the former repository.
=> fix: link to site repository in DangerJS

package-lock.json, package.json, packages/@tinacms/scripts/bin/scripts.js
Original PR by @maciekgrzybek 
- install and add typescript-plugin-styled-components to the rollup config
- plugins creates better developer experience by adding meaningful class names
=> feat(rollup) Add ts plugin for better style components experience

packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/Menu.tsx, packages/tinacms/src/plugins/fields/GroupFieldPlugin.tsx
Adjusts the z-index for both the markdown toolbar & group panel. 
Fixes #830
=> Markdown Toolbar Z-index Fix

packages/@tinacms/core/src/cms.ts, packages/tinacms/src/tina-cms.ts
Before this was required
new TinaCMS({})
Now we can just do this
new TinaCMS()
=> TinaCMS constructor config is now optional

packages/tinacms/src/components/Tina.tsx, packages/tinacms/src/index.ts
The new name the purpose of the component.
The old name is still accessible, but it has been deprecated
```tsx
import { TinaCMS, TinaProvider } from "tinacms"
const cms = new TinaCMS()
function App () {
return <TinaProvider cms={cms}> ... </TinaProvider>
}
```
=> fix: renamed Tina to TinaProvider

packages/tinacms/src/tina-cms.ts
I noticed @kendallstrautman had to stop using `withTina` because a media store needed to be added to the `demo-next`. This PR removes that need.
=> fix: tinacms constructor accepts media.store

packages/react-tinacms-editor/src/Wysiwyg.tsx, packages/react-tinacms-inline/src/inline-wysiwyg.tsx
Refactor `InlineWysiwyg` to accepts all props–except `input`–acceptable by `Wysiwyg`
=> Wysiwyg passthrough

packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
With this PR, if there's only one block, clicking the 'Add Block' button will automatically add the block and the entire `AddBlockMenu` won't open. Wanted to add this to semi-mimic group-list behavior until we make that field, mostly for tinacms.org.
=> chore(react-tinacms-inline): adjust add block logic for single block

packages/tinacms/src/plugins/fields/BlocksFieldPlugin.tsx, packages/tinacms/src/plugins/fields/GroupFieldPlugin.tsx, packages/tinacms/src/plugins/fields/GroupListFieldPlugin.tsx, packages/tinacms/src/plugins/fields/wrapFieldWithMeta.tsx
Blocks, groups, and group lists weren't being wrapped with `wrapFieldsWithMeta`. For the group field I simply added this wrapper, but blocks and group lists handle their own labelling so I've added the ability for them to accept a description for now. 
Now all three of these fields will accept a description, and some styling inconsistencies have been fixed.
Closes #910
=> Add description to block, group & group list

packages/tinacms/src/components/TinaProvider.tsx
This sets the `SiteWrapper` component to only animate `width` instead of `all`. 
Closes #944
=> style: set transition property to width

packages/tinacms/src/index.ts
This was causing an error:
```
There was an error compiling the html.js component for the development server.
See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html TypeError: Cannot redefine property: Input
> 1 | !function(n,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports,require("@ti
```
=> fix: duplicate exports

packages/@tinacms/react-modals/src/ModalProvider.tsx
You no longer need to provide a 'close' function to the `ModalHeader` component.
closes #950
=> chore: make close prop optional

packages/@tinacms/fields/src/components/ColorPicker/ColorPicker.tsx, packages/@tinacms/fields/src/plugins/BlocksFieldPlugin.tsx, packages/@tinacms/fields/src/plugins/GroupFieldPlugin.tsx, packages/@tinacms/react-forms/src/FormActions.tsx, packages/@tinacms/react-modals/src/ModalFullscreen.tsx, packages/@tinacms/react-modals/src/ModalPopup.tsx, packages/@tinacms/react-modals/src/ModalProvider.tsx, packages/@tinacms/styles/src/Styles.tsx, packages/react-tinacms-blocks/src/inline-blocks.tsx, packages/react-tinacms-editor/src/state/plugins/Menu/FloatingTableMenu/AddRowMenu.tsx, packages/react-tinacms-editor/src/state/plugins/Menu/MenuComponents.tsx, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/styles/input-focus-wrapper.tsx, packages/tinacms/src/Globals.tsx, packages/tinacms/src/components/sidebar/CreateContentMenu.tsx, packages/tinacms/src/components/sidebar/Sidebar.tsx
This removes a lot of the aggressive z-index values and instead uses a set of CSS custom properties to set consistent z-index values for components throughout Tina. 
The sidebar will no longer have an incredibly high z-index. Instead, if you find your site has elements that render on top of the sidebar, you can adjust the z-index values used by Tina to compensate. 
Here are the values used: 
```
--tina-z-index-0: 500;
--tina-z-index-1: 1000;
--tina-z-index-2: 1500;
--tina-z-index-3: 2000;
--tina-z-index-4: 2500;
```
Some elements will continue to use values like `-1` for local layering.
=> style: add z-index custom properties

packages/@tinacms/react-toolbar/package.json, packages/@tinacms/react-toolbar/src/components/ToolbarProvider.tsx, packages/@tinacms/react-toolbar/src/components/index.ts, packages/@tinacms/react-toolbar/src/index.ts, packages/@tinacms/react-toolbar/src/toolbar.ts, packages/demo-next/pages/_app.js, packages/tinacms/package.json, packages/tinacms/src/components/TinaProvider.tsx, packages/tinacms/src/tina-cms.ts
- Adds `ToolbarState`
- Creates `ToolbarProvider`, adds it to `TinaProvider`
- Instantiates `ToolbarState` class on `tinacms` 
The toolbar's default state is hidden. The toolbar will only mount if the `hidden` property is specified in the config: 
```js
this.cms = new TinaCMS({
sidebar: {
position: 'overlay',
hidden: true,
},
toolbar: {
hidden: false,
},
})
```
Let me know if this is in the ballpark of what you had in mind @ncphillips — I know this isn't a long-term implementation but felt like these are good first steps to let folks opt-in to using the toolbar w/o breaking changes.
=> Feat: Adds ToolbarState & ToolbarProvider

packages/demo-gatsby/src/components/edit-toggle.js, packages/demo-gatsby/src/templates/blog-post.js
The Edit button was unstyled and aligned to left.
The PR updates `EditToggle` to inherit from @tinacms/styles
Co-authored-by: Scott Byrne  <scott.byrne@forestry.io>
=> chore: use Tina Styles for the Edit Button

packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
If there was no block data, the `AddBlock` menu was rendering when the form was inactive.
=> Fix(react-tinacms-inline): hide AddBlock when form is inactive

packages/next-tinacms-github/README.md, packages/next-tinacms-github/src/constants.ts, packages/next-tinacms-github/src/github/create-access-token.ts, packages/next-tinacms-github/src/github/proxy.ts, packages/next-tinacms-github/src/next/preview.ts
Cookie schema was user-specified, perhaps to ensure interoperability with `react-tinacms-github` which contains the code that sets these cookies. After discussing with @jamespohalloran,  we determined that this degree of configuration was unnecessary and may even be a detriment down the line. This schema is now a hard-coded concern within the package, which has the benefit of simplifying userland implementation for these API routes
=> Don't allow users to set cookie schema in api handlers

packages/react-tinacms-inline/package.json
Fix #999
react-tinacms-inline should depend directly on react-textarea-autosize
=> fix: dependend on react-textarea-autosize

packages/react-tinacms-github/src/github-client/index.ts
Was using an env, now uses this.baseRepoFullName.
=> chore: fix client.createFork request

packages/next-tinacms-github/package.json, packages/react-tinacms-github/package.json, packages/react-tinacms-github/src/components/AsyncButton.tsx, packages/react-tinacms-github/src/github-editing-context/GithubAuthModal.tsx
Show error message when GitHub fork fails. This might occur is the repo url is incorrect or private.
=> feat(github): Show error message when github fork fails

packages/react-tinacms-github/src/toolbar-plugins/pull-request/PRModal.tsx
Using an undeclared variable name in PRModal (causes screen to blow up). Slipped through with the ts-ignore
=> fix(Github): fix incorrect property access in PRModal

packages/react-tinacms-editor/src/state/plugins/Menu/index.tsx
When not in edit mode, the menu would return null based on editorView. Since the useEffect code that measures the menu (setMenuBoundingBox) relies on menuRef, and menuRef relies on the component rendering, editorView has been added to the useEffect dep list, fixing the issue preventing the sticky menu from working.
Closes #1018
=> fix: sticky menu useEffect dep list addition

packages/@tinacms/react-forms/src/FormView.tsx
This updates the empty state placeholder link that points to our fields docs. It now points to more generic field docs.
Closes #881
=> chore: update fields doc link

packages/@tinacms/react-alerts/src/Alerts.tsx
The alerts container was rendering under site elements. This applies the second highest z-index available in Tina to the container.
=> style: add z-index to alerts container

packages/react-tinacms-github/src/toolbar-plugins/pull-request/PRModal.tsx
Note: `baseBranch` and `workingBranch` contain the owner name if they're different?
closes #1069
=> chore: prevent user from creating PR on base branch

packages/react-tinacms-github/src/toolbar-plugins/BranchSwitcherPlugin.tsx
This explicitly sets a font size for the branch switcher current branch name. It was previously inheriting from site styles, which would only work in some situations.
=> style: set current branch name font size

packages/react-tinacms-github/src/github-client/github-client.ts
It was defaulting to 'master' even if that wasn't the base
Discovered this while trying to turn the tinacms/rfcs repo into a Next+Github site.
=> fix: github-client branch name should default to base branch

packages/react-tinacms-github/src/github-client/authenticate.ts, packages/react-tinacms-github/src/github-client/github-client.ts
allows for access to private repositories if it should be so desired
Co-authored-by: Logan Anderson <logan@forestry.io>
**Example**
```ts
new GitHubClient({
authScope: 'repo' // defaults to 'public_repo'
})
```
=> feat(github-client): optionally accept scope

packages/react-tinacms-github/src/form/useGithubJsonForm.ts, packages/react-tinacms-github/src/form/useGithubMarkdownForm.ts
No need for second argument:
```ts
useGithubJsonForm(file)
// equivalent to
useGithubJsonForm(file, {})
```
=> fix(use-github-format-forms): the options are optional

packages/react-tinacms-editor/src/plugins/Image/Popups/Edit.tsx
Fix for image not getting deleted when popup over it is closed and delete button is hit.
Ref: https://github.com/tinacms/tinacms/issues/1083
=> fix: close image popup and hitting delete button should delete image

packages/react-tinacms-editor/src/plugins/Link/Menu/index.tsx
Link button will be disabled if no text is selected.
=> fix: link button should be disabled if selection is empty

packages/next-tinacms-github/README.md
Very small docs fix. I was confused because the link text is the page you're already on 😄
=> Fix link text in next-tinacms-github README

packages/react-tinacms-github/src/github-client/github-client.ts
Instead of "Unprocessable Entity" we get the error message from the github api
=> fix: github error uses message from response

packages/@tinacms/forms/src/form.ts, packages/gatsby-tinacms-git/src/use-git-form.ts, packages/gatsby-tinacms-mdx/src/useMdxForm.tsx, packages/next-tinacms-json/src/use-json-form.ts, packages/next-tinacms-markdown/src/use-markdown-form.ts
This PR makes it possible to pass an `onChange` callback to a form construction.
This change makes it possible to override default behaviour of `useGitForm`:
```js
const cms = useCMS()
useRemarkForm(node, {
onSubmit(data) {
return cms.api.git.writeToDisk({
fileRelativePath: values.fileRelativePath,
content: toMarkdown(values),
})
}, 
onChange: null,
})
```
This makes it so:
1. The form does not write to disk `onChange` 
1. Pressing `Save` writes to disk
Effectively disabling the "live" preview mode which causes problems for users with slow builds.
=> feat: form({ onChange })

packages/@tinacms/core/src/cms.ts, packages/@tinacms/react-sidebar/src/components/Sidebar.tsx, packages/@tinacms/react-toolbar/src/components/ToolbarProvider.tsx, packages/gatsby-plugin-tinacms/gatsby-browser.tsx, packages/gatsby-plugin-tinacms/options.ts, packages/react-tinacms-github/src/github-client/github-client.ts, packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx, packages/tinacms/src/components/TinaProvider.tsx
This PR fixes a few issues with the UI:
* The UI is disabled when `cms.disabled`
* The `TinaProvider` subscribes to cms events i.e. enabling and disabling
* Starting the Github auth flow enables the CMS, thus loading the styles and rendering the sidebar/toolbar
* Exiting the Github auth flow early disables the CMS, thus hiding the sidebar/toolbar
* Toolbar UI subscribes to changes in toolbar state
=> Various UI Logic Corrections

packages/tinacms/src/components/TinaProvider.test.tsx, packages/tinacms/src/components/TinaProvider.tsx
From the discourse topic here: https://community.tinacms.org/t/error-when-trying-to-set-up-tina-for-first-time-cannot-read-property-all-of-undefined/189
When passing an empty object to TinaProvider's `cms` prop, the following error would be thrown:
```
Cannot read property 'all' of undefined
TypeError: Cannot read property 'all' of undefined
at n.Alerts (C:\Development\TorqIT\TorqIT-next\node_modules\@tinacms\react-alerts\build\index.js:1:5729)
at processChild (C:\Development\TorqIT\TorqIT-next\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
at resolve (C:\Development\TorqIT\TorqIT-next\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
at ReactDOMServerRenderer.render (C:\Development\TorqIT\TorqIT-next\node_modules\react-dom\cjs\react-dom-serv …
```
=> improvement: add type check on cms property of TinaProvider

packages/react-tinacms-github/src/github-client/github-client.ts
Added ref to the fetch file method in the github client. before this it would only fetch from the default branch.
=> fix: github client fetch file works on any branch

packages/tinacms/src/components/TinaProvider.test.tsx, packages/tinacms/src/components/TinaProvider.tsx
Original PR in #1196 by @IronSean 
---
From the discourse topic here: https://community.tinacms.org/t/error-when-trying-to-set-up-tina-for-first-time-cannot-read-property-all-of-undefined/189
When passing an empty object to TinaProvider's `cms` prop, the following error would be thrown:
```
Cannot read property 'all' of undefined
TypeError: Cannot read property 'all' of undefined
at n.Alerts (C:\Development\TorqIT\TorqIT-next\node_modules\@tinacms\react-alerts\build\index.js:1:5729)
at processChild (C:\Development\TorqIT\TorqIT-next\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
at resolve (C:\Development\TorqIT\TorqIT-next\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
at ReactDOMServerRenderer.render …
```
=> Cms error check

packages/@tinacms/styles/src/Button.tsx, packages/demo-next/pages/info.js, packages/react-tinacms-inline/src/inline-settings.tsx
Closes #1003 
- Hitting the 'Cancel' button resets any changes made in the modal form to the initial values when the settings modal was opened
- Adds a confirm button that essentially just closes the modal but makes for better UX. 
My questions @spbyrne : 
- Do we add an alert or confirmation to this action? - Waiting until it's needed
- Should we call this 'reset' or does 'cancel' feel good? 👉 Cancel
- ~Should the type be red to indicate a delete action?~ Nay
- Should 'cancel' also close the modal? ✅
=> Inline settings — cancel & confirm

packages/demo-next/pages/nesting.tsx, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/inline-group/inline-group-controls.tsx, packages/react-tinacms-inline/src/inline-group/inline-group.tsx
This allows you to set `insetControls={true}` on BlocksControls & InlineGroups. I'm not sure if it would make sense to also have the ability to set this at the `InlineBlocks` or not since it depends on how the individual block is set up.
=> Add Inset Option For Blocks Controls

packages/@tinacms/styles/src/Styles.tsx, packages/react-tinacms-inline/src/blocks/add-block-menu.tsx, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx, packages/react-tinacms-inline/src/styles/focus-ring.tsx
- Fixes add block menu positioning depending on proximity to the top/bottom of the viewport.
- Fixes close add block menu button.
- Increases z-index of add block button & menu to fix overlap issues.
- Standardize large drop shadow.
- Prevent text selection of add block menu items.
- Centers add block button when no blocks are present for both column and row layouts.
- Hides `BlocksEmptyState` when not selected (add block button when no blocks present).
=> Add Block Fixes

packages/demo-next/pages/info.js, packages/demo-next/pages/nesting.tsx, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/inline-group/index.ts, packages/react-tinacms-inline/src/inline-group/inline-group-controls.tsx, packages/react-tinacms-inline/src/inline-group/inline-group.tsx
```js
<InlineGroup
name="frontmatter"
fields={[
{ label: 'Name', name: 'name', component: 'text' },
{ label: 'Hometown', name: 'hometown', component: 'text' },
]}
offset={10}
borderRadius={5}
focusRing={false}
>
...
</InlineGroup>
```
or 
```js
<BlocksControls index={index} focusRing={false}>
...
</BlocksControls>
```
=> Adds focus ring prop to inline groups and blocks controls

packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
Sometimes it makes sense to set a negative offset for the focus ring. This positions the add block menu in the correct location in that case.
=> style: fix button positioning for negative offsets

packages/@tinacms/fields/src/components/ImageUpload/ImageUpload.tsx, packages/react-tinacms-inline/src/fields/inline-image-field.tsx
Resolves the warnings for image upload by removing unused variables: `isDragActive`, `isDragAccept` & `isDragReject`. Typically these are passed to styled components to add various style states depending on the drag, but we weren't doing that.
=> chore: removes unused dropzone variables from image upload

packages/@tinacms/fields/src/plugins/BlocksFieldPlugin.tsx, packages/react-tinacms-inline/src/blocks/add-block-menu.tsx, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
Blocks require a "type" be set on the template, but the defined blocks that you use, already are key'ed.
```
const PAGE_BLOCKS = {
hero: {
Component: HeroBlock,
template: Hero,
},
// ...
```
This PR removed type, and instead uses the key from the blocks definition.
This could be a breaking change if the key differed from the template's type.
=> refactor(blocks): Remove type from block template

packages/@tinacms/fields/src/plugins/TagsFieldPlugin.tsx
Fixes #1201 
Added a simple check to return out of the function if tag field value is an empty string.
(I couldn't find the tests or I would have added one)
=> fix: prevents empty tag field registering

packages/@tinacms/core/src/cms.ts
From this [discussion](https://github.com/tinacms/tinacms.org/pull/458#discussion_r440293299). 
Instead of doing this:
```tsx
<button onClick={cms.enabled ? cms.disable() : cms.enable()}>
```
you can now do this:
```tsx
<button onClick={cms.toggle}>
```
=> feat: add cms.toggle to make togling the cms.enabled prop easier

packages/react-tinacms-github/src/toolbar-plugins/BranchSwitcherPlugin.tsx
This feels like a **feat** to me but let me know if it should be a **chore** instead.
By firing an event, developers can subscribe to branch change in their form-creating code.
This addresses the problem described in #1264, but we might also want to implement the desired behavior in `useGithubFileForm`
=> feat(react-tinacms-github): fire event on branch change

packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
should solve:
```
react.development.js:315 Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Droppable`. See https://fb.me/react-warning-keys for more information.
in InlineBlock (created by Droppable)
in Droppable (created by ConnectFunction)
in ConnectFunction
in ConnectFunction (created by ForwardRef(Field))
in ForwardRef(Field) (created by InlineField)
```
i guess
=> fix: use key prop

packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
this allows passing trough dynamic props
---
I've just gave tina-cms a spin after reading the next.js blogpost about it.
When experimenting a bit with the incredible cool inline features I faced some problems.
I wanted to make a collapsible list which roughly works like that:
```js
function InteractiveBlocks() {
// ensure a single collapsible is open at a time
const [expanded, setExpanded] = React.useState<number | false>(false);
const handleChange = (panel: number) => (
event: React.ChangeEvent<{}>,
newExpanded: boolean
) => {
setExpanded(newExpanded ? panel : false);
};
return (
<InlineBlocks name="faqs" blocks={FAQ_BLOCKS} blockProps={{onChange: handleChange, expanded}} />
)
}
const faq_item_template = {
type: "faq_item",
label: "Selling Point",
defaultItem: {
title: "How much is the …
```
=> feat: add a blockProps prop which spreads props to child elements

packages/demo-next/pages/blocks.tsx, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
[_Original PR by @sakulstra PR_](https://github.com/tinacms/tinacms/pull/1274)
this allows passing trough dynamic props
---
I've just gave tina-cms a spin after reading the next.js blogpost about it.
When experimenting a bit with the incredible cool inline features I faced some problems.
I wanted to make a collapsible list which roughly works like that:
```js
function InteractiveBlocks() {
// ensure a single collapsible is open at a time
const [expanded, setExpanded] = React.useState<number | false>(false);
const handleChange = (panel: number) => (
event: React.ChangeEvent<{}>,
newExpanded: boolean
) => {
setExpanded(newExpanded ? panel : false);
};
return (
<InlineBlocks name="faqs" blocks={FAQ_BLOCKS} blockProps={{onChange: handleChange, expanded}} />
)
}
const faq_item_template = { …
```
=> Inline blocks child props

packages/react-tinacms-editor/src/components/MenuHelpers/MenuDropdown.tsx, packages/react-tinacms-editor/src/plugins/Link/Menu/ProsemirrorMenu.tsx
Fixes https://github.com/tinacms/tinacms/issues/1269
1. Heading dropdown not hidden behind code block.
2 Link menu disabled in code block.
=> fix: code block breaking heading dropdown

packages/react-tinacms-editor/src/plugins/Image/Popups/Edit.tsx, packages/react-tinacms-editor/src/plugins/Link/Popups/InnerForm.tsx, packages/react-tinacms-editor/src/plugins/Table/commands/index.ts
The PR fixes issue with extra paragraphs being inserted when table is created.
May be we can reduce margins also above and below the table:
Currently its `32px`:
---
---
It can be reduced to `20px` or lesser by moving also icons can be moved closer to table:
---
---
@spbyrne , @DirtyF : plz suggest.
=> fix: extra paragraphs created while inserting table

packages/demo-next/pages/blocks.tsx, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
Pretty simple implementation. The add block and trash icons are hidden / shown based on the limits. Checkout the blocks page in `demo-next` for an example. When the range is limited (i.e. min === max), neither add block or trash icon will show. 
**Example**
```jsx
<InlineBlocks
name="blocks"
blocks={PAGE_BUILDER_BLOCKS}
min= {1}
max={4}
/>
```
---
_Note: I will write docs if we like this API_
=> feat: Block limits

packages/@tinacms/fields/src/plugins/wrapFieldWithMeta.tsx, packages/@tinacms/react-toolbar/src/components/Toolbar.tsx, packages/@tinacms/styles/src/Styles.tsx
* Fixes toolbar menu panel styles. On sites where a box sizing reset wasn't used the padding was being added to the calculated width.
* Bumps minimum Tina font size from 11 to 12px. This size is used for field descriptions.
* Prevents field description text from inheriting site <p> styles.
=> Minor Style Fixes

packages/react-tinacms-github/src/toolbar-plugins/BranchSwitcherPlugin.tsx
Creating a branch now fires `github:branch:create` and `github:branch:checkout`
Branch switcher updates branch listing on `github:branch:create`
=> GitHub: Fire events on branch create

packages/react-tinacms-editor/src/components/ProsemirrorEditor/index.tsx, packages/react-tinacms-editor/src/components/ProsemirrorEditor/utils/buildEditor.ts, packages/react-tinacms-editor/src/components/ProsemirrorEditor/utils/updateEditorState.ts
Fixes https://github.com/tinacms/tinacms/issues/1283
When editor is not focused and an update is received its state is re-build from new content this results in history of changes being lost.
PR fixes issue by updating state and not re-creating a new version of state.
=> fix: on updating editor state when new content is received and editor is not focused, editor history should not be lost

packages/@tinacms/core/src/cms.ts
This binds the cms to the functions so they can be passed around. For example:
onClick={cms.enable}
Before you would have had to do:
onClick={() => cms.enable()}
=> fix: the enable and disable are now lamdas

packages/next-tinacms-github/src/next/preview.ts, packages/react-tinacms-github/README.md
Because `fetch('/preview').then(response => response.json())` doesn't resolve if there's not a json body
=> fix: send json message on succesful preview handling

README.md
found this repo by accident via google and think it should be more prominently linked as it's quite interesting 
---
When being at it: would you consider enabling github discussions?
This is an obviously super subjective observation of myself so feel free to ignore that request:
Working with tina is fun, troubleshooting not so much :)
The "problem" i'm facing is that information is not at all centralized. Some is in `1) issues`, some in `2) readmes`, some in the `3) rfc repo`, some on `4) tinacms.org`, some on `5) https://community.tinacms.org/`.
Github search covers `1,2,~3`, via google i frequently land on `4`. `5` i only found by accident via the readme - never via google, but contains a lot of valuable information. I'd personally prefer `5` to be on github as well like e.g. on …
=> docs: link rfc repo in readme

packages/react-tinacms-editor/src/plugins/Link/Popups/Form.tsx, packages/react-tinacms-editor/src/plugins/Link/Popups/InnerForm.tsx
Prevents confusion when adding a link, as most of the time the `title` attribute should not be used on links anyway for accessibility concerns (see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#Accessibility_concerns).
=> fix: hide title input from link modal

packages/react-tinacms-editor/src/components/ProsemirrorEditor/styles/ProseMirror.tsx
The PR addresses issue of table add and delete row icons overlapping:
It might also address the issue of cursor not visible in empty document but I could not replicate or text that.
=> fix: table row add delete icons overlapping

packages/react-tinacms-editor/src/plugins/Table/Popup/OptionsPopup.tsx
Table delete icon should be visible only if whole table is selected.
=> fix: table delete icon should be visible only if whole table is selected

packages/@tinacms/react-core/src/use-form.ts, packages/gatsby-tinacms-git/src/use-git-form.ts, packages/gatsby-tinacms-mdx/src/useMdxForm.tsx, packages/next-tinacms-json/src/use-json-form.ts, packages/next-tinacms-markdown/src/use-markdown-form.ts
The `useForm` hook was making a weird assumption that `loadInitialValues` should never execute if the CMS is disabled. This PR undoes that assumption and pushes the responsibility to the client. If a developer does not want to make a request in prod, then it's the their responsibility to make sure the `loadInitialValues` they define works that way.
=> Use form load initial values

packages/@tinacms/core/src/cms.test.ts, packages/@tinacms/core/src/cms.ts
This fixes certain bugs where the CMS will accidentally become enabled because the enabled is set to undefined. It occasionally shows up in in Next.js websites (i.e. tinacms.org)
=> feat(@tinacms/react-core): a new CMS is disabled by default 

packages/next-tinacms-json/README.md, packages/next-tinacms-markdown/README.md, packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/styles/focus-ring.tsx
- Adds `react-tinacms-inline` package docs 
- Adjusts types on focus ring and blocks controls
- Updates a few small things in `next-tinacms-markdown` & `next-tinacms-json` READMEs
_Note_: Some of the examples and information is duplicated in the docs / inline editing guide. I was having a hard time knowing what to include / exclude from the package docs. IMO, the package docs should provide information on all of the components / functions / helpers that someone may want to use in building their own CMS — with basic interfaces & examples (or links to examples). Or should the interfaces live just in the docs? I think we need some clarity on _what goes in package docs_ versus regular docs.
=> Updates package READMEs

packages/next-tinacms-github/src/github/create-auth-handler.test.ts, packages/next-tinacms-github/src/github/create-auth-handler.ts, packages/next-tinacms-github/src/github/proxy.test.ts, packages/next-tinacms-github/src/github/proxy.ts, packages/next-tinacms-github/src/next/preview.test.ts, packages/next-tinacms-github/src/next/preview.ts, packages/next-tinacms-github/src/test-helpers.ts
This does not fully solve the problem as the frontend does not react appropriately but it's an improvement for #1357
=> next-tinacms-github: check for signing key and return 500 if it's missing

packages/@tinacms/react-modals/src/Modal/ModalHeader.tsx, packages/@tinacms/react-sidebar/src/components/SidebarBody.tsx, packages/react-tinacms-github/README.md, packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/styles/focus-ring.tsx
Follow up from e2fd14c
Caught in the build of tinacms/tinacms.org#637
(Also accidentally committed updates to the react-tinacms-github docs)
=> fix: switch from ReactNode to ReactChild for various props

dangerfile.ts
Now that we are automatically generating the root CHANGLOG and the GitHub release, the need to use Milestones has gone. This PR removes that check from the CI
=> build: remove checkForMilestone

packages/react-tinacms-editor/src/plugins/Block/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/plugins/Link/Popups/InnerForm.tsx, packages/react-tinacms-editor/src/plugins/Table/commands/index.ts
@DirtyF: PR fixes the issues in editor we discussed last week:
1. I added tooltip to heading icon in menubar
2. Link URL input to get focus as modal opens
3. In link modal disable Save until URL is entered
4. In an edge case table creation was failing, that is fixed
In addition I also checked in heading dropdown to ensure that current heading get highlighted correctly and it seems to work well for all heading types.
=> fix: wysiwym UX issues fixes in table, heading, link modals

packages/@tinacms/core/src/cms.test.ts, packages/@tinacms/core/src/cms.ts
See [RFC 0010](https://github.com/tinacms/rfcs/blob/master/0010-api-events.md) for more information.
=> feat(@tinacms/core): events from APIs are dispatched to the entire CMS

packages/react-tinacms-inline/src/fields/inline-text-field.tsx, packages/react-tinacms-inline/src/fields/inline-textarea-field.tsx
Backwards compatible change.
When inside a form with `title = "Hello World"`
**Default Usage**
```jsx
<InlineText name="title" />
```
Output when `cms.disabled` will be:
```html
Hello World
```
**With Children**
```jsx
<InlineText name="title">
Not Editing
</InlineText>
```
Output when `cms.disabled` will be:
```html
Not Editing
```
---
=> Inline text children

packages/@tinacms/fields/src/plugins/ImageFieldPlugin.tsx, packages/@tinacms/git-client/src/git-media-store.ts, packages/@tinacms/media/src/media.ts, packages/react-tinacms-editor/README.md, packages/react-tinacms-editor/src/components/MarkdownEditor/index.test.tsx, packages/react-tinacms-editor/src/components/ProsemirrorEditor/index.tsx, packages/react-tinacms-editor/src/components/ProsemirrorEditor/utils/buildEditor.ts, packages/react-tinacms-editor/src/components/ProsemirrorEditor/utils/buildEditorState.ts, packages/react-tinacms-editor/src/plugins/Image/Popups/Edit.tsx, packages/react-tinacms-editor/src/plugins/Image/nodeView.ts, packages/react-tinacms-editor/src/plugins/Image/plugin.ts, packages/react-tinacms-editor/src/plugins/Link/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/plugins/Link/Popups/Form.tsx, packages/react-tinacms-editor/src/plugins/Link/plugin.ts, packages/react-tinacms-editor/src/tinacms-inline/inline-wysiwyg.tsx, packages/react-tinacms-editor/src/types.ts, packages/react-tinacms-editor/stories/wysiwyg.stories.tsx, packages/react-tinacms-github/src/github-client/github-client.ts, packages/react-tinacms-github/src/github-media-store/index.ts, packages/react-tinacms-inline/src/fields/inline-image-field.tsx, packages/react-tinacms-strapi/src/strapi-media-store.ts, packages/tinacms/src/tina-cms.ts
This RFC introduces `MediaStore#previewSrc`. This allows `MediaStores` to provide a default method that can be overridden on a field-by-field basis
Todo:
Done
- Needs to work with async previewSrc
Note: READMEs don't really require any updates from this PR
Setup
* Add the `parse` function to the `InlineWysiwyg` wrapper.
* Run with local TINA version
* Turn on the sidebar and add a dummy `image` field to the sidebar
* Make sure to create a new testing branch
* Add an Inline Image Field somewhere
Tests
=> MediaStore#previewSrc

packages/react-tinacms-editor/README.md
- adds focus ring info
- adds table and example on `imageProps`...could use a second eye here as I know this has changed recently.
=> Updates `react-tinacms-editor` docs 

packages/react-tinacms-github/README.md
[View README](https://github.com/tinacms/tinacms/blob/58eebf59e5e6f3c42c00e5625baac7e07703b663/packages/react-tinacms-github/README.md)
- Reorganizes README
- delegates step-by-step content to the Next.js + GitHub guide
- documents `GithubFile` and `useGithubFile`
- documents `GithubClient` public methods
The API reference for `GithubClient` is a bit big and clunky and would likely be better served by Typedoc annotations.
=> Update README for react-tinacms-github

packages/gatsby-plugin-tinacms/gatsby-ssr.tsx
According to the docs: https://tinacms.org/docs/releases/2020-08-03#upgrading-from-v0250,  you have to pass `enabled` since 0.26.0.
Context: being able to upgrade tina-starter-grande to latest Tina
=> gatsby-plugin-tinacms: pass enabled option

packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
Updating the `InlineBlocks` interface based on changes from #1404. 
Also, made the `className` prop optional on the new blocks container.
=> Update inline blocks docs

packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
https://reactjs.org/docs/forwarding-refs.html
We can either pass the ref in a different prop (`innerRef`, as is done here) or we could require consumers to use `React.forwardRef` when creating their custom container component
=> fix ref forwarding in InlineBlocks

packages/react-tinacms-inline/src/fields/inline-image-field.tsx
When I was trying to test something in`demo-next`, none of the `previewSrc` for inline images were working. In doing some testing, I think I found the issue. There is no `getState` method on `form`, so I updated this to `form.values` which calls on `finalForm.getState().values`
There may be something I am missing because [this line is used](https://github.com/tinacms/tinacms/blob/master/packages/%40tinacms/fields/src/plugins/ImageFieldPlugin.tsx#L47) in the regular `ImageFieldPlugin`: `form.getState().values`. Wondering if there's a different usecase or something with the form config changed.
=> fix(react-tinacms-inline): preview src passes form values

packages/react-tinacms-editor/src/plugins/Image/Menu/ProsemirrorMenu.tsx
Fix #1405 Upoad image modal issue:
Note: there is a broken scenario, probably @spbyrne can check later:
=> fix: wysiwym image modal issues

packages/react-tinacms-editor/src/context/editorMode.tsx
Adding keyboard shortcut `Cmd-/` or `Ctrl-/` for mode toggling in editor.
=> feat: keyboard shortcut for toggle editor mode

packages/@tinacms/core/src/media.ts, packages/@tinacms/fields/package.json, packages/@tinacms/fields/src/plugins/ImageFieldPlugin.tsx, packages/react-tinacms-editor/src/tinacms-inline/inline-wysiwyg.tsx, packages/react-tinacms-inline/src/fields/inline-image-field.tsx
The `previewSrc` signature for `MediaStore`, `InlineImageField`, and `ImageFieldPlugin` are all identical now.
=> Previewsrc refactor

packages/@tinacms/core/src/media.ts, packages/@tinacms/fields/src/plugins/ImageFieldPlugin.tsx, packages/demo-next/pages/blocks.tsx, packages/demo-next/pages/info.js, packages/react-tinacms-inline/src/blocks/inline-block-image.tsx, packages/react-tinacms-inline/src/fields/inline-image-field.tsx, packages/react-tinacms-inline/src/fields/inline-image/editable-image.tsx, packages/react-tinacms-inline/src/fields/inline-image/index.ts, packages/react-tinacms-inline/src/fields/inline-image/inline-image-field.tsx, packages/react-tinacms-inline/src/fields/inline-image/inline-image-upload.tsx, packages/react-tinacms-inline/src/fields/inline-image/non-editable-image.tsx, packages/react-tinacms-inline/src/inline-field.tsx
- **Feat**: Allows the extension of styles on the `InlineImage` container div via styled components or by passing a `className` directly. 
```js
// via styled components
<StyledInlineImage
name="frontmatter.image"
uploadDir={() => '/public/images/'}
parse={media => media.id}
>
{props => <img src={props.src} />}
</StyledInlineImage>
const StyledInlineImage = styled(InlineImage)`
background-color: red;
`
// or directly via className
<InlineImage
name="frontmatter.image"
uploadDir={() => '/public/images/'}
parse={media => media.id}
className="inline-img"
/>
```
- **Feat**: `InlineImage` accepts an `alt` prop, so if one doesn't use the render props pattern, they can still set the alt on the image element. 
```js
<InlineImage
name="frontmatter.image"
parse={media => media.id}
alt="RAD-ALT-TAG" …
```
=> Inline Image Updates

packages/@tinacms/git-client/src/git-media-store.ts, packages/demo-next/next-git-media-store.js, packages/demo-next/pages/_app.js
This allows folks to provide a custom `previewSrc` function by extending `GitMediaStore` so the proper src urls can render in the media manager list. 
Note that if the `type` is `file`, then `previewSrc` will be called. This can result in broken image paths for non-image files. One can account for this in their custom function, and I'm assuming the filtering or additional media types will help mitigate this.
=> git-media-store#list calls previewSrc

packages/@tinacms/react-alerts/src/Alerts.tsx, packages/tinacms/src/components/media/media-manager.tsx, packages/tinacms/src/tina-cms.ts
Default alerts for media upload and deletion failure
Not the _most_ helpful error message but still better then no feedback at all.
=> chore: add error and loading states for media manager

packages/@tinacms/fields/src/plugins/ImageFieldPlugin.tsx, packages/react-tinacms-editor/src/components/Wysiwyg/index.tsx, packages/react-tinacms-editor/src/types.ts, packages/react-tinacms-inline/src/fields/inline-image/editable-image.tsx, packages/react-tinacms-inline/src/fields/inline-image/inline-image-field.tsx
The wysiwyg images & inline image field was passing the entire `form` as opposed to `form.values`.
=> fix: uploadDir passes form values

packages/demo-gatsby/src/templates/blog-post.js, packages/react-tinacms-editor/src/plugins/Image/Menu/ProsemirrorMenu.tsx, packages/tinacms/src/components/media/media-manager.tsx
Updates the demo to work with latest media changes. I had to adjust the way the selected media preview src was being generated with wysiwyg images...I'm not sure if this is the best way to handle the `previewSrc`. The previous code didn't account for promises. 
Also, a small style fix in the media manager.
=> chore(demo-gatsby): media updates

packages/@tinacms/git-client/src/git-media-store.ts, packages/demo-next/next-git-media-store.js, packages/tinacms/src/components/media/media-manager.tsx
With this change, all media files will render with the `File` icon in the media manager list. This default prevents broken preview src states for media files. 
The assumption is that for preview src's to work in the media manager with any project using the git-client, they will need to extend the media store to tailor the `previewSrc` and `list` methods according to their project / framework.
=> (@tinacms/git-client): git-media-store#list doesn't set previewSrc

packages/demo-next/pages/info.js, packages/react-tinacms-editor/src/plugins/Image/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/tinacms-plugins/HtmlFieldPlugin.tsx, packages/react-tinacms-editor/src/tinacms-plugins/MarkdownFieldPlugin.tsx
Enables `imageProps` to be passed to the sidebar wysiwyg. Also removes the image popup from the menu entirely, so when you hit the media icon in the wysiwyg menu, the media manager opens immediately. 
Would love help testing this out to make sure it's all good and see if we actually like it better without the popup. If we want to keep the popup, we'll need to adjust some things in the sidebar.
=> feat(react-tinacms-editor): Sidebar wysiwyg images, removes media popup

packages/@tinacms/fields/src/components/Input.tsx, packages/@tinacms/fields/src/components/Select.tsx, packages/@tinacms/react-modals/src/Modal/ModalHeader.tsx
We're going to have to more aggressively reset CSS at a component level given Tina's UI is no longer isolated. Using `all: unset;` will reset everything for us, but it may nuke defaults we were previously relying on so it can't simply be applied universally. 
This is just a start, I will continue to apply this reset (and compensate for the missing defaults after it's applied) as issues come up.
=> style: add css override

packages/@tinacms/fields/src/components/Toggle.tsx, packages/demo-next/pages/nesting.tsx
Example to test in `demo-next` on the nesting page in the sidebar form.
Found an issue with the toggle (and select) in the inline settings modal that I think should be addressed in a different PR. I'll create a ticket to describe upon testing further.
=> Adjust toggle labels

packages/react-tinacms-inline/src/styles/focus-ring.tsx
Focus rings weren't working for absolutely positioned elements in some cases, this fixes the issue.
=> style: add focus ring height

packages/@tinacms/react-toolbar/src/components/DesktopLabel.tsx, packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
Fixing two more cases where global styles were interfering with Tina styles. When a Tina element applies padding or border it relies on the `box-sizing: border-box;` model, which was previously inherited from global Tina styles. Going forward this will have to be applied manually at the component level as needed, after `all: unset;` is used. This still feels like a patchwork solution but any elements updated to include 'all: unset;` should be safe moving forward.
=> style: fix font color

packages/@tinacms/fields/src/components/ColorPicker/ColorPicker.tsx, packages/@tinacms/react-modals/src/Modal/ModalOverlay.tsx, packages/@tinacms/react-sidebar/src/components/Sidebar.tsx, packages/@tinacms/react-toolbar/src/components/Toolbar.tsx, packages/@tinacms/styles/src/Styles.tsx, packages/react-tinacms-inline/src/blocks/add-block-menu.tsx, packages/react-tinacms-inline/src/styles/focus-ring.tsx
The focus ring didn't have an explicit z-index set and so was hidden behind absolutely positioned children. We also needed an additional level of z-index available for Tina UI, so `--tina-z-index-5` was added to the existing values.
=> style: improve z-index

packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
The block container interface didn't explicitly accept `children`. This made the typing awkward when trying to type props with `children` in the wild.
=> chore(react-tinacms-inline): Update block container props

packages/demo-next/pages/blocks.tsx, packages/react-tinacms-editor/src/tinacms-inline/inline-wysiwyg.tsx, packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/inline-form.tsx, packages/react-tinacms-inline/src/inline-group/inline-group-controls.tsx, packages/react-tinacms-inline/src/styles/focus-ring.tsx
_Left: v0.32.0; Right: build of this branch_
When an inline field is active, the focus-setting callback would return before `event.stopPropagation` is called, yielding to the parent element which would assign itself focus. This led to a state where focus was constantly toggling back and forth between parent and child fields.
This seems to give a pretty significant performance boost when there are many blocks in a single inline blocks field.
This PR adds a render-child option to `FocusRing`, enabling conditional rendering of children depending on if the focus ring is currently focused.
```jsx
<FocusRing>
{active => {
if (active) {
return <ComplicatedEditableComponent />
}
return <SimpleDisplayComponent />
}}
</FocusRing>
```
This feature is now used by `InlineWysiwyg` to only render the …
=> Performance improvements for inline blocks

packages/@tinacms/core/src/cms.ts
=> fix(@tinacms/core): unsubscribe from events when replacing api

packages/demo-next/pages/nesting.tsx, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx
Make it possible to use custom Actions in BlocksControls. Usage looks like this:
``` typescript
<BlocksControls
index={index}
customActions={[
{
icon: <TinaIcon />,
onClick: () => alert('Hello from a custom Block Action!'),
},
]}
/>
``` 
This opens a variety of use cases, such as:
- Opening a custom Screen when a custom action is clicked.
- Toggle a `boolean` field value when clicked.
=> feat: Use custom actions in BlocksControls

packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
This fixes the bug where the add block menu was opening below the focus ring and other add block buttons.
=> style: fix inline add block z-index bug

packages/@tinacms/react-core/src/use-form.ts, packages/gatsby-tinacms-git/src/use-git-form.ts, packages/react-tinacms-github/src/github-client/github-client.ts, packages/react-tinacms-inline/src/inline-group/inline-group.test.tsx
before:
```js
const [data, form] = useForm({
//...
loadInitialValues: async () => { await doSomething() },
})
return form.loading ? <Spinner /> : <Page data={data} />
```
This wouldn't correctly subscribe to the form loading state. With this PR, `useForm` has been updated to track its loading state in a `useState` under the hood, which is more idiomatic:
```js
const [data, form, formIsLoading] = useForm({
//...
loadInitialValues: async () => { await doSomething() },
})
return formIsLoading ? <Spinner /> : <Page data={data} />
```
also includes some other fixes involving workflows with loadInitialValues
potential fix for #1551 
Note this also **creates a new event** — `unstable:reload-form-data` that fires on branch switch. This is helpful for pages that fetch data client-side or don't …
=> Async form improvements

packages/@tinacms/fields/src/components/Input.tsx
Should fix #1632, reverts a change from [this commit](https://github.com/tinacms/tinacms/commit/cfe38f348e1384e590cdb7cc53488d8b4679444e#diff-44421cc8cb1c86e2056b172d759885efc66f09ca174d40f5fd15710e0ba42ca1R29). We'll have to find a different way to reset those input styles.
=> fix(@tinacms/fields): input doesn't unset all styles

scripts/prerelease.sh, scripts/release.sh, scripts/require_clean_work_tree.sh
Whenever I run a prerelease I panic for 3 seconds and double check to make sure I ran the prerelease script and not the release script.
This PR does two things:
1. ensures there are no uncommitted or unstaged changes in the working tree before running a release or prerelease, and
2. requires a manual confirmation before running a release (to ensure it isn't run by mistake when intending to create a prerelease.)
=> Require confirmation before running release

packages/demo-next/pages/nesting.tsx, packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/inline-group/inline-group-controls.tsx
Adds a block label for inline blocks which appears opposite the blocks controls. This label uses the 'label' from the block template. `BlocksControls` now accepts a 'label' prop (boolean) to disable the label when it's not needed. The label is displayed by default.
I'd like to see what people think of this label design. I also tried a smaller blue label joined to the focus ring and also putting the label alongside the other blocks controls. This seemed to be the better option. 
It probably makes sense to add this to inline groups but they don't have an easy label option like `template.label` used by inline blocks.
[Docs PR](https://github.com/tinacms/tinacms.org/pull/761)
Here's what happens on blocks that are smaller than the width of the controls:
Thanks @chrisdmacrae for coming up with …
=> feat(react-tinacms-inline): Adds Block Label

packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx
* Fixes issue where the block label is positioned incorrectly when `BlocksControls` have `insetControls` set to `true`.
Current inset label:
Fixed inset label:
=> style: fix inset block label

packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx
This fixes an issue where the block menu spacer element was preventing pointer events from being passed down to children.
=> style: fix pointer events

packages/react-tinacms-github/src/form/useGithubFileForm.ts, packages/react-tinacms-github/src/form/useGithubJsonForm.ts, packages/react-tinacms-github/src/form/useGithubMarkdownForm.ts
Before this commit, the return type of `useGithubFileForm` (and transitively of `useGithubJsonForm` & `useGithubMarkdownForm`) was `[any, any]`. 
Now it is `[T, Form]`, where `T` is the generic type parameter describing the shape of the parsed file data.
Also, `useGithubJsonForm` & `useGithubMardownForm` didn't **have** that type parameter `T` (describing the shape of the parsed file data), and where it could be used, an implicit `any` was used instead. 
Now they have that type parameter, defaulted to `any`, so that it may be something more specific than `any`, either by explicit definition, or by inference from argument types.
This same problem existed in options interfaces for all 3 hooks, and I applied the same solution.
Thanks for your work on this awesome project :)
=> fix(react-tinacms-github): Fix types for form hooks

packages/react-tinacms-github/src/github-client/GithubFile.ts, packages/react-tinacms-github/src/github-error/github-interpeter.ts
I want to be able to save a new file to GitHub with a form plugin.
I figured I should be able to initialize the form (i.e. use `useGithubJsonForm`) with an empty `GitFile` (e.g. `{ fileRelativePath: "content/offerings/${slug}.json", data: {}, sha: "" }` when the file doesn't exist yet, and clicking "Save" in that form should make a commit **creating** that file (instead of updating a preexisting file).
The first part works.. I can initialize the form with an empty file.
The problem comes when trying to save the form:
First off, I received a wrong error message in the browser, saying I was on a branch that doesn't exist. (I was on a branch that did in fact exist). With my first commit 7e3ba86 I fixed this, to show the [more] correct error message, "Content Not Found". 
I think that commit …
=> react-tinacms-github: Allow creating new file by saving form

packages/react-tinacms-editor/README.md
By default, Tina's toolbar will hide the WYSIWYG menu bar. As the `sticky` prop accepts a string, it also accepts CSS variables, such as the one used by Tina to determine toolbar height.
This means that editors can pass `var(--tina-toolbar-height)` to `sticky` to ensure the WYSIWYG menu is always visible, even in an environment where Tina's toolbar is displaying. It might be worth considering this as default behaviour whenever the toolbar is enabled in case sticky is not set explicitly. If this is seen as a good idea, I can create a PR for it.
=> Suggested trick for pushing menu below toolbar

packages/@tinacms/react-sidebar/src/components/Sidebar.tsx
Currently, elements in host site that are fixed (like navigation bars) are underneath the Tina sidebar and toolbar when the rest of the site is moved to keep it in view. 
https://user-images.githubusercontent.com/806104/104685494-ca240580-56c0-11eb-96a1-2d6136e20c4b.mp4
Notice the logo is left behind the sidebar. This is because the navigation bar containing the logo is set to `position: fixed; left: 0;`. Because fixed elements are positioned relative to the viewport, this presents a problem when introducing sidebars for sites that may contain elements like this.
Luckily there is a fix to this problem. This is done by putting a transform on the `SiteWrapper`. The transform creates a new local coordinate system, per [W3C spec](https://www.w3.org/TR/css-transforms-1/#transform-rendering): …
=> fix(@tinacms/react-sidebar): fixed site elements relative to SiteWrapper

packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx, packages/react-tinacms-inline/src/inline-form.tsx
The drag + drop feature of inline blocks adds a lot of complexity to the code. The incoming [planned changes to inline editing](https://tina.io/blog/more-changes-coming-to-inline-editing/) do not yet have a plan for working with drag + drop functionality.
The feature doesn't work in all cases (https://github.com/tinacms/tinacms/issues/1610), and even at its best, it is of limited utility when the layout is composed of tall, full-width blocks (our most common pattern right now.)
Because of this, we believe that, at least for now, it makes sense to remove drag + drop capabilities for inline blocks. Blocks can still be reordered using the chevron buttons on block controls. This UI is simpler and less buggy than drag + drop.
=> refactor(react-tinacms-inline): remove drag + drop for blocks

.github/workflows/danger.yml, dangerfile.ts
We've been wrangling with the problem of how to run DangerJS against PRs that originate from forks. DangerJS works by leaving comments on PRs with warnings/errors triggered by the script, and the read-only `GITHUB_TOKEN` provided to GItHub actions that run against forks can't comment on PRs.
Previously, I attempted to resolve this by using a machine user and generating a personal access token for them, which we then send to the script. The idea is that this user can comment on PRs, but doesn't have access to anything important since there is potential for this access token to be extracted by a malicious PR. Creating a build environment to provide this token, and requiring builds to first be approved before running, seemed like adequate mitigation against this threat. Unfortunately, I …
=> Run DangerJS workflow on pull_request_target instead of pull_request

packages/tinacms/src/react-tinacms/use-form.ts
Adds an optional second argument to 'useFormScreenPlugin' to allow an icon to be passed to GlobalFormPlugin when instantiating a new Form Screen.
=> Some options for GlobalFormPlugin can't be passed through useFormScreenPlugin

packages/@tinacms/fields/src/components/ColorPicker/ColorPicker.tsx
This fixes a bug, when color picker is nested inside form and does not open up. The problem is that the click event is fired twice (one for Swatch and one for SwatchInner) and the color picker then stays always closed.
Example field configuration:
```
const formOptions = {
label: 'Header',
fields: [
{
label: 'Banner',
name: 'banner',
component: 'group',
fields: [
{
label: 'Background color',
name: 'backgroundColor',
component: 'color',
},
{
label: 'Text',
name: 'text',
component: 'text',
},
{
label: 'Text color',
name: 'textColor',
component: 'color',
},
],
},
],
}
const [data, form] = useGithubJsonForm(file, formOptions)
useFormScreenPlugin(form)
...
```
=> Stop event propagation

.github/workflows/build-test-lint.yml
I think this was working on forked PRs by coincidence before, and due to changes in the dangerjs workflow is not currently running on forked PRs
=> chore(build): run PR build on `pull_request` event

packages/react-tinacms-inline/src/inline-form.tsx
Closes #1725
This adds back the `<div onClick={() => setFocussedField('')}>` element that was removed in #1702.
@dwalkr Did this element need to be removed for some reason? I'm guessing it was just forgotten when refactoring?
Thanks!
=> fix(react-tinacms-inline): Fix ability to clear field selection

packages/react-tinacms-github/src/form/useGithubFileForm.ts, packages/react-tinacms-github/src/form/useGithubJsonForm.ts, packages/react-tinacms-github/src/form/useGithubMarkdownForm.ts
Adds an additional `watch` argument to the Github file hooks in order to be passed on to the useForm hook.
=> feat(react-tinacms-github): Add WatchableFormValues argument to use file hooks

packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx
This prevents block and group actions from being clicked when the block or group isn't active.
=> fix: inline group click event  bug

packages/@tinacms/forms/src/content-creator-plugin.ts, packages/@tinacms/react-sidebar/src/components/CreateContentMenu.tsx
Fixes #1715 
Behind the scenes, a custom `ContentCreator` plugin is a `Form` wrapped in `Modal` functionality.  Because of this, `initialValues` can be passed in the same way as defining a `Form` config and then used when creating the `Form` (via the `plugin.initialValues`).
=> fix(@tinacms/react-sidebar): Allows initialValues for ContentCreator Plugins

packages/tinacms/src/components/media/pagination.tsx
**Fixes #1747**
`offset` was incorrectly being calculated against the page's **display number** rather than the page's **index**.
For example, Page 2 should have an `offset` of `5`, but `setOffset(...)` calculated it to be `10` (`display * limit` or `2 * 5`).
This explains why Page 1 was usually accurate (rarely is `offset` passed in the initial `MediaList` options), but any other page would be incorrect (as `setOffset(...)` would trigger the bug on click).
Note:  I also addressed a React `Warning` regarding `key` missing from the `<PageNumber>` components.
=> fix(tinacms): Fixes pagination for any MediaStore

packages/react-tinacms-inline/src/inline-settings.tsx
The inline settings modal 'cancel' button would revert changes, but the 'x' button in the modal header was just closing the modal. Both buttons now trigger the cancel behaviour.
=> Fix Inline Settings Cancel Behaviour

packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
This sets a `max-height` on the inline add block menu and adds a visual cue when the list is overflowing in a given direction. 
https://user-images.githubusercontent.com/5075484/112364056-e772e280-8cb4-11eb-9afa-695741bbc9d6.mp4
=> style: scrolling add block menu

packages/@tinacms/fields/src/plugins/BlocksFieldPlugin.tsx, packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
This takes the filter pattern from the git branch switcher and applies it to the inline add block menu, with a few tweaks. This search input is only displayed if there are 10+ blocks, so it will hopefully make the current block selector more usable in cases with many blocks.
Here's how I padded out the existing demo-next blocks page with more blocks to hit the minimum required:
```
const HeaderBlock = () => {}
const header_template: BlockTemplate = {
label: 'Header',
fields: [],
}
const TestimonialBlock = () => {}
const testimonial_template: BlockTemplate = {
label: 'Testimonial',
fields: [],
}
const NavBlock = () => {}
const nav_template: BlockTemplate = {
label: 'Nav',
fields: [],
}
const VideoBlock = () => {}
const video_template: BlockTemplate = {
label: 'Video',
fields: [],
}
const …
```
=> Inline Add Block Menu Filter

packages/@tinacms/fields/src/components/RadioGroup.tsx
I noticed that value changes to `RadioGroup` was triggering a warning within `react-final-form` due to how `final-form` handles radios:
> Warning: You must pass `type="radio"` props to your Field component.
> Without it we don't know how to unpack your `value` prop - "undefined".
According to https://github.com/final-form/react-final-form/issues/392, this appears to be an unusual quirk of `react-final-form`'s API (and specific to `type=radio`) and a helpful suggestion (https://github.com/final-form/react-final-form/issues/392#issuecomment-543118944) is to skip the `SyntheticEvent` (`onChange={input.onChange}`) and pass `value` directly:
`onChange={event => input.onChange(event.target.value)}`
This seemingly produces the same result - minus the warning.
=> fix(@tinacms/fields): Fix "type=radio" field warning

dangerfile.ts
Updates `dangerfile.ts` in order to allow this PR to run without errors:
https://github.com/tinacms/tinacms/pull/1782
Going to quote @dwalkr to explain why:
> danger workflow runs on pull request target https://github.com/tinacms/tinacms/blob/master/.github/workflows/danger.yml#L2
> ... the main reason we're using pull_request_target is that if we get a PR that originates from a fork (instead of a branch on the main repo,) Danger doesn't receive the right permissions to be able to comment on that PR - the code runs in the context of the fork. pull_request_target lets us run checks on that PR but in the context of the code on master
=> fix(dangerfile): Updates dangerfile

packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
This reintroduces the 'click outside' code removed in #1772 but with added logic to handle the filter input.
=> fix: close on click outside

packages/@tinacms/styles/src/Styles.tsx
`--tina-color-grey-10` had the wrong hue, this fixes it.
=> Fix grey 10

packages/@tinacms/fields/src/components/Select.tsx, packages/@tinacms/fields/src/plugins/ListFieldPlugin.tsx
Something I encountered while working with the `starter`, a `select` inside of a `list` can extend beyond the edge of the sidebar, making it difficult to interact with the `select` and other list members:
https://user-images.githubusercontent.com/1699544/114768222-3220d100-9d2e-11eb-8591-1417ee92b33f.mov
This pure CSS fix will simply add ellipsis (`text-overflow: ellipsis;`) to long `select`s:
https://user-images.githubusercontent.com/1699544/114768353-5b416180-9d2e-11eb-8356-ded9fa811f4c.mov
=> fix(@tinacms/fields): Adds ellipsis to long list selects

packages/@tinacms/react-alerts/src/Alerts.tsx
The container alerts pop up in was blocking click events, so in order to open the sidebar you had to wait for any alerts to go away given the toggle is underneath this container. This is now fixed so that the container itself doesn't capture any click events, just the alerts.
=> fix: alert container click blocking

packages/@tinacms/react-sidebar/src/components/ResizeHandle.tsx, packages/@tinacms/react-sidebar/src/components/Sidebar.tsx
You can now click and drag the right edge of the sidebar to resize it!  🎉
- Sidebar width will still default to `--tina-sidebar-width`, which the user can customize in their CSS.
- There's a 250px minimum width and it can't extend beyond the width of the window viewport. 
- All the logic is contained in a new `ResizeHandle` component.
- There's a 4px clickable area at the right edge of the sidebar instead of a visible handle. Hovering this area will change your cursor.
- Text selection is blocked with a universal selector while dragging.
[Thanks @weibenfalk for your initial work on this](https://github.com/tinacms/tinacms/pull/565)
https://user-images.githubusercontent.com/5075484/114748808-a6587600-9d28-11eb-95d3-b5f7df98c5d8.mp4
Closes #558
=> feat: drag to resize sidebar

scripts/prerelease.sh, scripts/release.sh
Mentioned by DJ, it might be good to check that `$GH_TOKEN` is set before running either release script.
While `prerelease.sh` is probably fine, running `release.sh` without `$GH_TOKEN` will result in the changelogs getting swallowed and that, in his words, "sucks".
Learn more at https://github.com/lerna/lerna/blob/main/commands/version/README.md#--create-release-type
=> fix: Check for $GH_TOKEN when releasing

packages/@tinacms/react-toolbar/src/components/CreateContentMenu.tsx
Prevent rage clicks on when adding new content.
UX: We should convey that the document is currently being created like we do for save.
=> disable create content button via toolbar

dangerfile.ts, package-lock.json, package.json
Because we're running against pull_request_target, local scans don't work here. We've decided to remove it for now and investigate other options for maintaining dependency hygiene.
=> chore(build): remove depcheck from danger script

packages/@tinacms/react-forms/src/FormView.tsx, packages/@tinacms/react-toolbar/src/components/Toolbar.tsx, packages/demo-next/data/blog/apple.md, packages/demo-next/pages/blog/[slug].tsx
This PR will disable the save button in the sidebar and toolbar if a field fails a validation check.
Big thanks to @Enigmatical who did the heavy lifting to track down the source.
=> fix(bug): disables form save button if field fails validation

packages/@tinacms/react-toolbar/src/components/Toolbar.tsx
3rd-party toolbar widgets should implement this interface to ensure interop, so we need to export it
=> chore: export ToolbarWidgetPlugin interface

packages/@tinacms/core/src/cms.ts, packages/@tinacms/core/src/media-store.default.ts, packages/@tinacms/core/src/media.ts, packages/@tinacms/git-client/src/git-media-store.ts, packages/react-tinacms-github/src/github-media-store/index.ts, packages/react-tinacms-strapi/README.md, packages/react-tinacms-strapi/src/strapi-media-store.ts, packages/tinacms/src/components/media/index.ts, packages/tinacms/src/components/media/media-manager.tsx, packages/tinacms/src/components/media/pagination.tsx, packages/tinacms/src/index.ts, packages/tinacms/src/tina-cms.ts
This is essential to support Cloudinary and likely other DAMs in the media manager. The API changes reflect a relaxing of the needed pagination data from Media Stores, moving from a "SQL-style" `limit` + `offset` calculation to a less-opinionated `prevOffset` / `nextOffset` approach.
- *This was an experimental feature added to work around UI bugs with page numbers in large media libraries. Existing paginator plugins are expected to break due to the API changes anyway. I think the best course of action is to remove support for these plugins until the needs are better understood.*
=> feat(tinacms): use cursor-based pagination in media manager

packages/@tinacms/forms/src/content-creator-plugin.ts, packages/@tinacms/react-forms/src/CreateContentMenu.tsx, packages/gatsby-tinacms-git/src/use-git-form.ts, packages/gatsby-tinacms-mdx/src/useMdxForm.tsx, packages/gatsby-tinacms-remark/src/use-remark-form.tsx, packages/next-tinacms-json/src/use-json-form.ts, packages/next-tinacms-markdown/src/use-markdown-form.ts, packages/react-tinacms-github/src/form/useGithubFileForm.ts, packages/react-tinacms-github/src/form/useGithubJsonForm.ts, packages/react-tinacms-github/src/form/useGithubMarkdownForm.ts
**This PR is dependent on #1840 and should be merged afterwards.**
Discovered during research into Form Inconsistencies, our various versions of `useForm(...)` and its wrappers (i.e. `useGitHubFileForm(...), `ContentCreator` Plugin) accepted and respected a certain subset of `FormOptions` - usually identified as `Options` (that sometimes extended `FormOptions`).
This has the unintended consequence of unpredictable behavior when using a `Form`.  Can I provide `reset`?  `onChange`?  `buttons`?  `actions`?  Will `label` actually be used?
This PR seeks to smooth over those rough edges by (to some degree) allow `FormOptions` to be directly passed and each of the options to be respected.  There are still places where `overrides` or `default` options are used (namely, `loadInitialValues()` is …
=> 1841 - Unify `FormOptions` for `useForm(...)` and its variations

scripts/release.sh, scripts/require_gh_token.sh
Automatically creating a GitHub release is one of the last steps in the release script, and can cause some minor havoc for the entire release if the script runner's credentials are misconfigured. This PR updates the release script to check this capability by creating and deleting a dummy release before kicking off the rest of the process.
=> chore(release): ensure access token can create a release before starting

packages/@tinacms/core/src/media.ts, packages/tinacms/src/components/media/media-manager.tsx, packages/tinacms/src/index.ts
alternative to https://github.com/tinacms/tinacms/pull/1868
this enables customizing error feedback by throwing an instance of `MediaListError` which enables you to customize the title, explanation message, and link to documentation.
This feels simpler, and allows Media Stores to include troubleshooting instructions directly.
```
import { MediaListError } from 'tinacms'
class MyCustomMediaStore {
// ...
async list(options) {
// ...
throw new MediaListError({
title: 'Missing API Key'
message: 'We couldn't find the API key',
docsLink: 'https://example.com/my-media-store-docs',
})
}
}
```
=> feat(tinacms): customize list error message by throwing a MediaListError

packages/react-tinacms-editor/src/tinacms-inline/inline-wysiwyg.tsx
Using relative path to import `FocusRingOptions` fails when using webpack and node as the path becomes `react-tinacms-inline/dist/src/styles`
=> fix(react-tinacms-editor): fixing FocusRingOptions import path

packages/react-tinacms-github/package.json
... rather than a direct dependency.  Should resolve issues where `useCMS()` could not locate a `cms` context and maybe other issues downstream.
Could be a fix for issues encountered here:
https://github.com/tinacms/tinacms/issues/1865
=> fix(react-tinacms-github): Makes form-builder a peerDependency

packages/react-tinacms-editor/package.json, packages/react-tinacms-inline/package.json
Like the work on `react-tinacms-github` and `next-tinacms-github`, `@tinacms/form-builder` should no longer be a direct `dependency`, but instead a `peerDependency/devDependency`.  Having it a direct depdendency was causing issues downstream with (I believe) the use of `FormPortalProvider` which would have relied on a shared context.
Can confirm that I was able to using the `MarkdownFieldPlugin` once I made this change using `beta` releases of both packages and the GitHub Backend flow.
Relates to #1865
=> fix(react-tinacms-editor,react-tinacms-inline): Fixes deps

.github/workflows/danger.yml, dangerfile.ts
- consumers metadata on tina.io is not maintained
- global dep check will no longer be necessary with migration to PNP
=> remove unused danger scripts

packages/@tinacms/toolkit/src/packages/form-builder/FormBuilder.tsx
A lingering difference between our `ContentCreator` (and Modal Forms) vs. Sidebar is that Modal Forms were coded to submit on `Enter`.  While handy, this meant that certain fields - namely `textarea` - would not function properly.
This behavior was carried over to `FormBuilder` as part of the merger, but is better left removed entirely.
=> fix(@tinacms/toolkit): Removes onKeyPress from FormBuilder

packages/@tinacms/form-builder/src/FormBuilder.tsx
A lingering difference between our ContentCreator (and Modal Forms) vs. Sidebar is that Modal Forms were coded to submit on Enter. While handy, this meant that certain fields - namely textarea - would not function properly.
This behavior was carried over to FormBuilder as part of the merger, but is better left removed entirely.
=> fix(@tinacms/form-builder): Removes onKeyPress from FormBuilder

dangerfile.ts
Trying to change the dangerfile to exclude files in the `examples/` folder.  I believe it needs to be a separate PR to work.
=> chore: Excludes examples folder when determining files needing license

.changeset/hungry-lies-shave.md, examples/tina-cloud-starter/.tina/__generated__/_schema.json, examples/tina-cloud-starter/.tina/__generated__/config/schema.json, examples/tina-cloud-starter/.tina/schema.ts, examples/tina-cloud-starter/package.json, examples/tina-cloud-starter/pages/_app.js, packages/react-tinacms-editor/package.json
`react-tinacms-editor` wasn't actually using any APIs in `final-form` or `react-final-form` so they don't need to be in the dependency tree at all.
=> simplify installation for `react-tinacms-editor`

.changeset/little-colts-confess.md, packages/tinacms/src/hooks/use-graphql-forms.tsx
NOTE: the _fix_ here is to use `formValues` as the `useEffect` dependency. I know we're violating the dependency rule pretty hard here, but I think we'll come up with something better soon. Adding detailed notes to give some context.
This design is pretty flaky, but better than what we've had previously. The way it works is we update `formValues` with state from the final form subscription, so it stays perfectly in-sync with form values. But since the `data` key has different needs, we have to track how a change to the same path in the `data` object should run.
To do that, we tap in to the `change` and mutator (`insert`, `move`, & `remove`) functions and set the `newUpdate` state with the path that is to be updated.
So when a `title` changes, we do 2 things: 1. Set `formValues` to the new …
=> Fix issue where data was off by one character from WYIWYG

.changeset/healthy-items-unite.md, examples/tina-cloud-starter/pages/_app.js
Uses the `documentCreatorCallback` to set up specific behavior for the `tina-cloud-starter`.  Utilizes `onNewDocument()` to redirect to the new document's relative url after it is successfully created.  Utilizes `filterCollections()` to limit the available Collections to just `Blog Posts`.
=> chore(examples/tina-cloud-starter): Adds documentCreatorCallback 

packages/@tinacms/cli/CHANGELOG.md, packages/@tinacms/cli/README.md, packages/@tinacms/cli/package.json
Rename tinacms-cli to @tinacms/cli in our docs/examples
(I _think_ this matches our new package naming, but may be off)
=> docs(tinacms): rename tinacms-cli

.changeset/config.json
From [changsets](https://github.com/atlassian/changesets/blob/main/docs/decisions.md#the-versioning-of-peer-dependencies) docs:
> Currently, if you list a package as a peerDependency of another package, this causes the package with the peerDependency to be released as a major change. This is because peerDependency changes will not be caught by package installation.
This resulted in an [unwanted major version bump](https://github.com/tinacms/tinacms/pull/1930), while it's likely the more correct behavior, until we're at 1.0 we'll try and hold off on too many major version bumps.
Settings this [option](https://github.com/atlassian/changesets/issues/524) prevents that behavior
=> use experimental flag for changsets

.github/workflows/main.yml
`tsup` doesn't appear to work with Node 10. Since Node 10 is now EOL, we might as well drop it from the matrix.
Additionally, there seem to be some problems with the build on windows. We are disabling windows builds for now and will come back to it later, as noted in #1934 
to test this, I updated the `main` workflow to also run on this branch, but have rebased out that change before merging. I'm attaching a screenshot of the checks to document:
=> Fix main build

.changeset/olive-radios-drum.md, packages/@tinacms/graphql/src/primitives/resolver/index.ts
Updates the primitives resolver to use `checkbox-group` when field is `type: string`, `options: [...]`, and `list: true`.  This will render as the new `CheckboxGroupField` Plugin and accept multiple `string` values.
Closes #1866
=> feat(@tinacms/graphql): Use checkbox-group field

.github/workflows/build-test-lint.yml
Workflows triggered from PRs do not run when a PR is created by github actions, so the required workflow is not running when changeset bot creates a versioning PR. By also triggering this workflow on pushes to branches prefixed with changeset-release, the expectation is that this workflow will run on pull requests opened by changeset bot.
=> trigger PR build on pushes to changeset-release branches

.changeset/giant-badgers-flow.md, examples/tina-cloud-starter/pages/_app.js, packages/tinacms/README.md, packages/tinacms/src/hooks/use-graphql-forms.tsx
the formify API can provide a simple way to create global forms in its callback, similar to the existing createForm
=> expose a createGlobalForm function in formify args

.changeset/stale-tables-heal.md, examples/tina-cloud-starter/components/header.tsx, packages/tinacms/src/hooks/use-graphql-forms.tsx
This cropped up when adding a new NavItem to the Starter.  The error message:
`currentFields.find() is not a function.`
Debugging this, it appears that `currentFields` is not always a function of `fields` and can sometimes be a singular `field`.
The fix appears to be simply to test if `currentFields` is an Array, otherwise, the value of `currentFields` is already a singular `field`.
Fixes https://github.com/tinacms/tina-cloud-starter/issues/141
Fixes https://github.com/tinacms/tina-cloud-starter/issues/143
=> fix(tinacms): Test if currentFields is an Array

.changeset/mighty-moons-divide.md, packages/@tinacms/cli/src/cmds/start-server/index.ts
The issues we are seeing with windows are only happening when installed from NPM and not happening on the monorepo. This PR is to add a better error message for more context into what is happening.
=> added a better error message for childProcess

.changeset/silver-icons-guess.md, packages/@tinacms/graphql/src/primitives/resolve.ts
When using the starter, if you add a new document, and then go and add an author to that document - we don't know how to properly build the path for that request, so it just gets the `id: path/to/author.md` instead of the node itself. 
When GraphQL gets a `null` value, it doesn't continue to resolve the fields:
```graphql
{
getPostsDocument(relativePath: $relativePath) {
data { # when this is null
author { # this resolver function doesn't run
name  
}
}
}
}
```
If `data` is null (as it is after creating a new document), `author` is never resolved. And that's where we set up the information to tell the form how to update when a reference is changed [here](https://github.com/tinacms/tinacms/compare/fix-null-document-reference-error?expand=1#diff-275a3281b2f1deff910cd6e4496be5abf14160c8ea92d1 …
=> Fix references for empty documents

packages/tinacms/src/utils/index.ts
Before, we were throwing an error when a site was missing its clientId. This flags things for the user on local development, but when you run into this on a hosted environment, e.g, when trying to edit on our [hosted starter](https://tina-cloud-starter-orcin.vercel.app/), things blow up, without a helpful message.
With a recent up, the dashboard shows an error with an invalid client-id. 
We shouldn't have to throw this error within tinacms anymore
=> fix: remove missing-clientId error

.changeset/good-frogs-appear.md, examples/tina-cloud-starter/pages/_app.js, examples/tina-cloud-starter/pages/posts/[filename].tsx, packages/tinacms/src/tina-cms.tsx
Fixes an issue where new documents returned a 404 when on a hosted deployement. Instead, `getStaticPropsForTina` will catch and return an empty object for the data key. This allows us to replace it with real data client-side.
Relates to https://github.com/tinacms/tina-cloud-starter/issues/147
=> Fix 404s for new documents on hosted site

.changeset/seven-ducks-camp.md, packages/tinacms/src/client/index.ts
We were treating the base client as a localClient when clientId not set. This caused weird behaviour, such as our on starter:
When the user has local-mode turned off, but hasn't set a client-id: if they enter edit-mode, it immediately thinks the user is authenticated and [tried to render the root components children](https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/auth/TinaCloudProvider.tsx#L54). This causes things to blow up.
Instead, we want to avoid rendering children if we are not logged in (including when we don't have a valid client-id to log into.)
On a refactoring level, the base class was also a bit too aware of its LocalClient child implementation.
=> fix: Don't treat client w/ missing client-id as LocalClient

.changeset/wise-beans-pump.md, packages/@tinacms/graphql/src/primitives/database/github.ts, packages/@tinacms/graphql/src/primitives/database/index.ts
Something Jeff discovered:  In the event a user chooses a GitHub repository lacking a `.tina` and `.tina/__generated__` folder, they are given a very confusing error message.
I've modified the `GraphQLError` messages thrown by the `GithubBridge` to more accurately reference the file, the repository, and the reference (branch) being used.
Additionally, I've added in a suggestion to "confirm" the repository and the existence of `.tina` and `.tina/schema.ts` in the event that the error is throw while looking for the `SYSTEM_FILES`.
Closes #1993
=> 1993 - Better Error Messaging when linking to Tina Cloud 

.changeset/odd-ducks-raise.md, packages/tinacms/src/tina-cms.tsx
Closes https://github.com/tinacms/tinacms/issues/2009
=> Ensure `null` values aren't passed back from getStaticPropsForTina

.changeset/khaki-cups-worry.md, examples/tina-cloud-starter/.tina/__generated__/_schema.json, examples/tina-cloud-starter/.tina/__generated__/config/schema.json, examples/tina-cloud-starter/.tina/schema.ts, examples/tina-cloud-starter/components/post.tsx, examples/tina-cloud-starter/content/posts/voteForPedro.md, packages/@tinacms/graphql/src/primitives/resolver/index.ts, packages/@tinacms/toolkit/src/packages/fields/plugins/DateFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/dateFormat.ts
Removes any conversions to `utc` inside the `format` method for the `DateFieldPlugin`.
`toISOString()` still converts to UTC which is called both in the `parse` method and again in the `graphql/primitives/resolver`.
For example:
`July 3, 2021 3:30 PM` (Central Timezone)
saves as
`2021-07-03T20:30:00.000Z` (UTC)
Closes #2025
=> 2025 - Make DateFieldPlugin timezone friendly 

dangerfile.ts
it's an autogenerated file and is too large to retrieve via the contents api, leading to failures from the danger script
=> ignore .pnp.js in license check

.github/ISSUE_TEMPLATE/contributing.md, .github/SUPPORT.md, README.md, packages/@tinacms/scripts/README.md, packages/@tinacms/webpack-helpers/README.md, packages/next-tinacms-github/src/next/preview.ts, packages/react-tinacms-editor/README.md, packages/react-tinacms-editor/editor-docs/README.md, packages/react-tinacms-inline/README.md
Fix several links to main from our readme's (master branch still exists, but is behind)
=> docs: Link to main instead of master branch

packages/tinacms/src/auth/TinaCloudProvider.tsx
This fixes the issue where you have to refresh your page on save during development since a hot-reload would wipe out your sidebar form
`new TinaCMS` wasn't protected by memoization in the React component so was getting reinitialized on each render. Since this was higher in the tree I guess we didn't see too many issues with it, but was probably hurting performance. At any rate, it was also wiping out the work `useGraphQLForms` was doing because the re-render didn't trigger a re-run of the hook (something that's also not ideal).
=> Memoize cms initialization so hot-reloads don't run into race-conditions

.changeset/violet-games-prove.md, packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/block.ts
Thanks tinaCMS team
In the process of using tinaCMS, I found that the "data" type of BlockComponentProps was hard-coded to any. I suggest to modify it to generic
The type of Block is defined as `React.FC<BlockComponentProps>`, it will not be able to pass in class components, I suggest changing it to `React.ComponentType<BlockComponentProps>`
=> Improve the type definition

.changeset/cyan-radios-decide.md, examples/tina-cloud-starter/components/post.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/DateFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/dateFormat.ts
While dogfooding, I noticed some unusual behavior in the `react-datetime` picker when using `DEFAULT_DATE_FORMAT` (`MMM dd, yyyy`).
`dd` is actually not a supported token by `moment` (https://momentjs.com/docs/#/parsing/string-format/).  Swapping to `DD` resolves this.
We had not encountered this before because the `tina-cloud-starter` schema uses `DD` correctly for `dateFormat`.
I also made a change to better handle when a date is `invalid` (`parse` was failing).
=> Uses better default dateFormat for DateField

packages/tinacms/src/auth/AuthModal.tsx, packages/tinacms/src/auth/TinaCloudProvider.tsx, packages/tinacms/src/edit-state.tsx
There was an issue that was introduced with our new build set. For some reason the edit context is not getting shared. This caused the close button not to work. 
This PR is a temp fix that allows the close button to work once again.
=> temporary fix for edit state context issues

.changeset/real-pears-chew.md, examples/tina-cloud-starter/.tina/__generated__/_lookup.json, packages/@tinacms/cli/src/cmds/compile/index.ts, packages/@tinacms/cli/src/cmds/start-server/index.ts, packages/@tinacms/graphql/src/primitives/builder/index.ts
Fixes https://github.com/tinacms/tinacms/issues/2056. It does not only fix it for the reference field but all fields that do not support list: true.
@jeffsee55 Should we provide a way to opt out as someone could provide their own UI and it would work as expected ?
EDIT: Maybe this change is too aggressive? We could also give a warning to the user that this UI is not currently supported and direct them to the docs for a work around (embed in object). 
EDIT again: I think I like the warning message better. I updated it to be a warning message now.
=> added new warning messages for list UI

.changeset/fast-spiders-repeat.md, packages/tinacms/src/auth/TinaCloudProvider.tsx, packages/tinacms/src/client/index.ts, packages/tinacms/src/tina-cms.tsx, packages/tinacms/src/utils/index.ts
Allow tina.io URLs to be supplied as a a prop:
```tsx
<TinaEditProvider
editMode={
<TinaCMS
branch="main"
clientId={NEXT_PUBLIC_TINA_CLIENT_ID}
tinaioConfig={{
baseUrl: "some-base.io"
}}
//...
```
Or just the identity/content URLs:
```tsx
<TinaEditProvider
editMode={
<TinaCMS
branch="main"
clientId={NEXT_PUBLIC_TINA_CLIENT_ID}
tinaioConfig={{
identityApiUrl: "https://some-base.io"
// AND/OR
contentApiUrl: "https://content.some-base.io"
}}
//...
```
Closes https://github.com/tinacms/tinacms/issues/2086
=> Add tinaioconfig to override API endpoints

.changeset/rotten-clocks-grin.md, packages/@tinacms/toolkit/src/packages/fields/plugins/BlocksFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/SidebarBody.tsx
One of our users pointed out an interesting way to circumvent validation on forms:
> If you have a `group`, `group-list`, `blocks`, or multiple forms, you can use the "back" arrow in the form header to navigate away from an invalid form and use the Save/Reset buttons to commit those invalid changes.
The reason for this is because we're only using the currently rendered `finalForm`'s `invalid` flag to determine the state of those buttons rather than looking at all of the changes and validating them.
While a much bigger solution would probably exist in something like "Nested Forms," a much simpler solution is to simply prevent navigating away from an `invalid` form.
(As an aside, I also found a bug with `GroupFieldPlugin` where it was incorrectly being used with `wrapFieldWithMeta`.  This …
=> 2113 - Prevent nagivation away from an invalid form

.changeset/odd-eels-jump.md, examples/tina-cloud-starter/.tina/__generated__/_graphql.json, examples/tina-cloud-starter/.tina/__generated__/_lookup.json, examples/tina-cloud-starter/.tina/__generated__/schema.gql, examples/tina-cloud-starter/.tina/__generated__/types.ts, packages/@tinacms/graphql/src/primitives/ast-builder/index.ts, packages/@tinacms/graphql/src/primitives/build.ts, packages/@tinacms/graphql/src/primitives/builder/index.ts, packages/@tinacms/graphql/src/primitives/database/index.ts, packages/@tinacms/graphql/src/primitives/resolve.ts, packages/@tinacms/graphql/src/primitives/resolver/index.ts
Adds mutations for `createDocument(collection, relativePath, params)` and `create<Collection>Document(relativePath, params)`.
This includes adding errors when attempting to `update` a document that doesn't exist or `create` a document that already exists.
Renamed a couple of `multi` functions to be `update`, reflecting their actual use.
Related to #2110
=> 2110 - Adds support for `create` document mutations

.changeset/twenty-countries-agree.md, packages/@tinacms/cli/src/cmds/baseCmds.ts, packages/@tinacms/cli/src/cmds/start-server/index.ts
In some environments (not just when `process.CI` is `true`), watching for changes to all files is not ideal/will be a problem.
This PR addresses the issue by adding a `--noWatch` option to the `server:start` command. When this option is used, file watching is disabled.
=> Server no watch option

.changeset/empty-gifts-tease.md, packages/react-tinacms-strapi/package.json
Fixes an issue #2098
Fixes a bug, that npm package is missing `dist` folder, because of the changed build path.
=> fix(react-tinacms-strapi): Main file in package.json

.changeset/weak-rules-argue.md, .yarnrc.yml, packages/react-tinacms-strapi/package.json, yarn.lock
When using the strapi package you'll run into this:
```
Module not found: Can't resolve 'react-final-form'
Module not found: Can't resolve 'zustand'
```
While `zustand` isn't something we're using, I believe you only need to install `react-final-form` and `final-form` and that will go away. But then you get to the real error, which was that `styled-components` was listed as a direct dependency:
```
error - Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips …
```
=> Fix styled-components listing in strapi

.changeset/blue-walls-vanish.md, examples/tina-cloud-starter/.tina/__generated__/_graphql.json, examples/tina-cloud-starter/.tina/__generated__/_schema.json, examples/tina-cloud-starter/.tina/__generated__/config/schema.json, examples/tina-cloud-starter/.tina/__generated__/schema.gql, examples/tina-cloud-starter/.tina/__generated__/types.ts, examples/tina-cloud-starter/.tina/schema.ts, packages/@tinacms/graphql/src/primitives/builder/index.ts, packages/@tinacms/graphql/src/primitives/resolve.ts, packages/@tinacms/graphql/src/primitives/resolver/index.ts, packages/@tinacms/graphql/src/primitives/spec/forestry-sample/requests/updateDocument-no-collection/request.gql, packages/@tinacms/graphql/src/primitives/spec/forestry-sample/requests/updateDocument-no-collection/response.json, packages/@tinacms/graphql/src/primitives/spec/forestry-sample/requests/updateDocument/request.gql, packages/@tinacms/graphql/src/primitives/spec/movies/requests/updateDocument/request.gql, packages/tinacms/src/admin/components/GetCollection.tsx, packages/tinacms/src/admin/components/GetDocumentFields.tsx, packages/tinacms/src/admin/index.tsx, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx
`TinaAdmin` now supports `collections` with `templates` (instead of `fields`).  While our documentation has moved away from explicitly talking about `templates`, our schema still supports them, so I personally felt the `TinaAdmin` story was incomplete with support for them, as well.
This necessitated some backend work that Jeff and I had been planning for a while, restructuring `resolveDocument()` to be broken up into small chunks of functionality - `get`, `create`, and `update`.
Things are still a little messy:  I'd like to rework/restructure `getDocumentFields()` now that I've a better idea of what TinaAdmin needs, but that's for a later time.
https://www.loom.com/share/acf56a87c13b4a55b3ac53144285c62f
Closes #2163
=> 2163 - Adds support for collection.templates to TinaAdmin

.changeset/eleven-schools-design.md, packages/next-tinacms-cloudinary/src/handlers.ts
Currently, the Cloudinary media manager loads images in their full resolution, even though only a small thumbnail is shown. The PR addresses this issue by applying these transformations to the `previewSrc` of images in the media manager: `w_75,h_75,c_fill,q_auto`.
=> Smaller Cloudinary images in media manager

.changeset/eleven-schools-design.md, packages/next-tinacms-cloudinary/src/handlers.ts
@employee451  thanks for the Cloudinary image improvement. I ran into a snag while testing it which is that currently the `previewSrc` value gets persisted. This isn't ideal because ideally we're storing the full image URL, so developers can modify it's size at render time in their app. I've made an adjustment to our media implementation [here](https://github.com/tinacms/tinacms/pull/2201), but we need to discuss it a bit before moving forward so just reverting this for now.
=> Revert "Smaller Cloudinary images in media manager"

.changeset/unlucky-chairs-eat.md, packages/tinacms/src/hooks/use-graphql-forms.tsx
Hopefully the non-breaking version of what this was supposed to be #2135
=> Ensure forms unmount properly when `useGraphQLForms` unmounts

.changeset/cool-pianos-pull.md, packages/react-tinacms-inline/package.json
Fixed path to Typescript typings, so that they are included in generated NPM package.
=> Fix missing Typescript typings for react-tinacms-inline package

.changeset/cuddly-cycles-camp.md, .changeset/dry-carrots-fix.md, packages/react-tinacms-strapi/package.json
1. Added path to Typescript typings, so that they are included in generated NPM package (currently they are not).
2. Moved `react` and `react-dom` to peer dependencies to avoid them to be installed in packaged "local" node_modules folder and avoid conflict with newer React versions (e.g. 17)
=> Some package.json fixes for react-tinacms-strapi package

.changeset/grumpy-melons-shout.md, experimental-examples/tina-cloud-starter/.tina/__generated__/_graphql.json, experimental-examples/tina-cloud-starter/.tina/__generated__/schema.gql, experimental-examples/tina-cloud-starter/.tina/__generated__/types.ts, packages/@tinacms/graphql/src/primitives/builder/index.ts
Credit to Jeff for discovering this quickly, but the upcoming changes to the GraphQL queries might break some existing uses of `updateDocument()` when they are introduced for `TinaAdmin`.
Before `createDocument` and `updateDocument` took a required argument `collection`, but more recently, we've discovered that argument is really necessary.
Originally, I removed the argument entirely from those queries, but because `TinaCloud` is not up-to-date with the latest `cli` changes, we've decided to bring the argument back (optional, instead of required).
This should ensure some degree of backwards compatability.
=> 2163 - Returns optional collection args for generic GraphQL queries

packages/@tinacms/cli/src/cmds/compile/index.ts, packages/@tinacms/scripts/src/index.ts
If your local repo wasn't called `tinacms` the build/watch commands wouldn't work. This just makes the check a little less strict.
Builds on top of https://github.com/tinacms/tinacms/pull/2239
=> Fixup script paths

.changeset/long-jokes-compete.md, packages/next-tinacms-github/package.json, yarn.lock
Closes https://github.com/tinacms/tinacms/issues/2037 (maybe)
I only fixed the ones for `next-tinacms-github`, but I suspect that this was missing and was causing the nested package `react-tinacms-github` to also appear to be missing
=> Fix types declaration for next-tinacms-github

dangerfile.ts
This updates `dangerfile.ts` so that it does not check the examples sub folder added in [this PR](https://github.com/tinacms/tinacms/pull/2251).
Can test it out here: https://regex101.com/r/c3gS2L/1/
=> update danger file to reject any file with example in the path

.changeset/thick-jobs-call.md, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/image/index.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/toolbar/index.tsx
We recently optimized the image src for preview thumbnails in Cloudinary. This value was also being used effectively as the src, also for MDX. This PR should update things so the correct (full) url is provided instead.
Thanks @jhuggett
=> Ensure "src" is used instead of "previewSrc" for images in MDX

.changeset/eight-pets-eat.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/NoFormsPlaceHolder.tsx, packages/tinacms/src/edit-state.tsx
Could use some copywriting improvements but in general an empty form isn't really an indication of any sort of error, just that there's no formifiable query on the page. Also added docs PR https://github.com/tinacms/tinacms.org/pull/1089
=> Alter empty sidebar message to be more specific to auto-generating logic

.changeset/wicked-eagles-turn.md, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
Replaces `/admin` and `/exit-admin` with the `TinaAdmin` pattern of `/pages/admin/[[..tina]].js`.
Closes #2235 
There will be a sister PR to change the documentation for `/admin` here:
https://tina.io/docs/tinacms-context/#manually-toggling-edit-mode
=> 2235 - Modifies `tinacms init` to add the new `TinaAdmin` page

packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
Remove old organization param from cli codegen
=> fix: remove organization from cli init codegen

packages/@tinacms/graphql/src/database/index.ts
@logan-anderson pointed out that schema updates weren't triggering from the CLI when a schema changed. This is due to the memoization of these into class properties and they weren't getting reinitialized. I think this should do for now, but I want to revisit this as part of a cleanup when the data store stuff settles.
=> Dont memoize schema configs

.changeset/sixty-kiwis-listen.md, examples/basic/.tina/__generated__/_schema.json, experimental-examples/tina-cloud-starter/.tina/__generated__/_schema.json, packages/@tinacms/graphql/package.json, packages/@tinacms/graphql/src/build.ts, packages/@tinacms/graphql/src/schema/index.ts, packages/@tinacms/graphql/src/spec/forestry-sample/.tina/__generated__/_schema.json, packages/@tinacms/graphql/src/spec/movies-with-datalayer/.tina/__generated__/_schema.json, packages/@tinacms/graphql/src/spec/movies/.tina/__generated__/_schema.json
Pin version number and metadata from @tinacms/graphql during schema compilation. This can be used to ensure the proper version is provided when working with Tina Cloud and appropriate features (like data are switched on)
Updated schemas will now look like this:
```json
"version": {
"fullVersion": "0.57.2",
"major": "0",
"minor": "57",
"patch": "2"
},
"meta": {
"flags": [
"experimentalData"
]
},
```
@kldavis4 and I discussed this and while including the API version in the URL is great, the data layer work will mean that webhooks coming from Github also need to know which version to build the index with. The upshot from this is that it's a more fullproof way of know that if the CLI compiled with a given schema, they're guaranteed to get that same version on Tina Cloud without needing to do …
=> Pin version number and meta data during schema compilation

.changeset/eleven-wombats-press.md, packages/@tinacms/graphql/src/build.ts
I'd updated the graphql version on tinacms.org for the GraphQL playground, which worked locally but I guess I never tested it on Vercel 😬 . The error came from trying to write the GraphQL query and fragments into the filesystem during index, which Vercel doesn't like obviously.
So the fix will be to skip that on the /api/graphiql API https://github.com/tinacms/tinacms.org/blob/8791c2264a95a2f7de2f30d9d9ea0bec5b43a1ed/pages/api/graphiql.ts#L20
```ts
await indexDB({ database, config, buildSDK: false })
```
Closes https://github.com/tinacms/tinacms.org/issues/1141
=> Allow indexDB to skip building the query and fragment generation files

.changeset/cuddly-cows-repeat.md, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchSwitcher.tsx
this will ensure the dropdown doesn't break the boundaries of the modal
when displaying long branch names
=> constrain width of simple branch selector dropdown

.changeset/eight-kangaroos-grow.md, experimental-examples/tina-cloud-starter/.tina/__generated__/_schema.json, packages/tinacms/src/admin/pages/CollectionListPage.tsx
I converted the `filename` column to use `flex` with `flex-shrink-1` on the `filename` portion to force longer filenames to truncate in the event they are too long.
Closes #2342
=> 2342 - [TinaAdmin] Truncates the `filename` column for the Document List View

.changeset/green-lobsters-sneeze.md, packages/tinacms/src/hooks/use-content-creator.tsx
Fixes https://github.com/tinacms/tinacms/issues/2320
@Enigmatical The issue was is that the from was being  re-created when the user selected a new "collection". This caused `initialValues`===`currentValues` this making the form ["pristine"](https://final-form.org/docs/react-final-form/types/FieldRenderProps#metapristine). When a form is pristine it can not be submitted or reset.
=> fixed 2320

.changeset/fifty-boxes-sparkle.md, packages/@tinacms/toolkit/src/packages/fields/plugins/BlocksFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx
Pointed out by Tina User, while we prevented navigation away from a form when the form was invalid, we did _not_ prevent navigation into objects (`block`, `group`, `group-list`).
This could result in a frustrating situation where the user could not navigate back to the invalid form to fix its invalid state after drilling down.
This is a more comprehensive fix than the adjustment I made in #2115.
Closes #2335
=> 2335 - Prevents navigation into objects when parent form is invalid 

.changeset/shiny-hornets-grow.md, packages/tinacms/src/admin/components/AuthTemplate.tsx, packages/tinacms/src/admin/pages/LoginPage.tsx
When in `local-mode`, `TinaAdmin` was using old messaging about logging into "Tina Cloud".
Ideally, we'd have a way to know if we're in `localMode` or not and alter the messaging on the Login page, but unfortunately, our indicator of `localMode` is attached to a `cms` instance that doesn't exist before you've logged in.
As a quick fix, I removed the message entirely and altered the `Log In` button's label to speak more about `edit-mode` - which exists in either scenario.
Closes #2374
=> 2374 - Incorrect messaging on admin when in local-mode

.github/workflows/publish.yml
I noticed a warning in some old publish logs that state we need to use `v1` instead of `master`. [See here for more details](https://github.com/changesets/action#without-publishing). I don't think this will fix the publishing issues but it should be what we use.
=> update changeset tag

packages/@tinacms/scripts/src/index.ts, packages/@tinacms/toolkit/src/styles.css, packages/tinacms/src/styles.css
This sets a font on the `tina-tailwind` wrapper so any chrome components will use the custom font stack as defined in the tailwind config instead of defaulting to whatever font stack is set on the HTML or Body element. Thanks @jamespohalloran for bringing this issue to my attention.
=> style: set font in tina reset wrapper

.changeset/popular-crabs-marry.md, packages/tinacms/src/tina-cms.tsx
Our playground does some mocking & manually uses the inner pieces of the TinaCMSProvider. We need to export this new component, so that our playground can use useTina
=> chore: Export data provider

.changeset/five-carrots-jam.md, packages/tinacms/src/tina-cms.test.tsx, packages/tinacms/src/tina-cms.tsx
Fixed an issue where if you were using render props with TinaCMS container, your child "data" prop would be overrided with null if there were no queries passed into the root container
=> Legacy-empty-query-fix

.changeset/tiny-cars-serve.md, packages/@tinacms/toolkit/src/packages/fields/components/Reference.tsx, packages/@tinacms/toolkit/src/packages/fields/components/Select.tsx
This adds the missing arrow icon to the reference field and adds text truncation to the select and reference fields. 
Just a minor issue I noticed while testing the new MDX editor.
=> Reference Arrow + Select Field Text Truncation 

.changeset/twenty-llamas-hang.md, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx
For a non-developer, the "Relative Path" field can be confusing.  In reality, this is just the "Filename" where the Document will reside (against the collection's `path` and `format`).
I've taken the old "Name" field from the `ContentCreator` and ported it over to the Collection Create Page, removing the need to specify the file extension, and adding some simple validation around the field.
https://www.loom.com/share/26019016d2ca41e0b7d3e8a2e2d36812
Related to #2530 
Closes #2535
=> 2535 - Updated relativePath field on Create Page

.changeset/chilly-cars-ring.md, packages/@tinacms/cli/src/cmds/start-server/index.ts
cc @kldavis4 
Also - this only affected `experimentalData`
=> Ensure experimental data builds during CI

.changeset/witty-mails-fix.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/FormList.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/SidebarBody.tsx, yarn.lock
- Fixes #2546 by rendering the form header when there's no label but with additional styling to account for the missing element.
- Adds form status to multiform header & matches styling so that it feels more 'form-like' vs. a group that doesn't need to be saved before closing.
- Adds entrance animation to multiform list to match animation on form entrance so it's less jarring.
Multi-form header:
Form with no label:
While the form name would be an okay fallback you actually get the ID and it's not very screen friendly, so I think dropping back to the form status alone is better.
=> Form Header Fixes

.changeset/two-sloths-hammer.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx, packages/tinacms/src/admin/components/Sidebar.tsx, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx
Right now if you don't provide a label for a collection, different parts of the UI appear broken or invisible. This makes everything fallback to the 'name' value, which is always provided.
=> Collection name as fallback in Admin UI

packages/@tinacms/sharedctx/src/edit-state-ctx.tsx, packages/@tinacms/toolkit/src/hooks/use-local-storage.ts, packages/tinacms/src/tina-cms.tsx
This PR looks to address issue #2481 leading to crash when `window.localStorage` access is denied.
=> chore: Adding defence against crash when localStorage access is denied

.changeset/large-garlics-push.md, packages/tinacms/src/client/index.ts
We recently pulled back how long it takes auth/id tokens to expire to 10 minutes. Having tokens expire more quickly has led 
to an increase in 400 errors from the content-api. This is probably because we aren't refreshing the tokens until _after_ they expire.
Made a quick update to refresh the tokens if they are going to expire within the next 2 minutes. This will hopefully cut back on clients sending us expired tokens.
=> fix: refresh token before it expires

.changeset/cyan-singers-smile.md, packages/@tinacms/graphql/src/database/index.ts
With the experimentalData flag enabled, adding a new document in the admin interface was failing with this error:
```
{
"errors": [
{
"message": "Unable to find '<filename>' in store for project <client_id>: '<owner>/<repo>', Ref: 'main'",
"locations": [
{
"line": 3,
"column": 9
}
],
"path": [
"createDocument"
],
"extensions": {
"status": 404
}
}
],
"data": null
}
```
I traced this issue to Database.indexDocument where was attempting to fetch an existing document from the store and not checking whether the document already existed. This PR adds an exception check to prevent this error from bubbling up. 
Ideally we'd probably be better off explicitly checking if a file exists (rather than checking if the get fails) _or_ if we know a request involves a new document, pass that info to this …
=> fix: #1452: update indexDocument to handle adding new docs

.changeset/dull-laws-hug.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Nav.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx, packages/tinacms/src/admin/components/GetCollection.tsx, packages/tinacms/src/admin/components/GetCollections.tsx, packages/tinacms/src/admin/components/GetDocument.tsx, packages/tinacms/src/admin/components/GetDocumentFields.tsx, packages/tinacms/src/admin/components/LoadingPage.tsx, packages/tinacms/src/admin/components/Sidebar.tsx, packages/tinacms/src/admin/index.tsx, packages/tinacms/src/auth/TinaCloudProvider.tsx
While locally, the Admin is snappy, in production or on Tina Cloud, there is some delay in loading a Collection List or Document.
Before, there was no way to tell that the request had even been made - resulting in potentially repeat clicking (which would further increase the delay) or a general lack of confidence that the Admin was even working.  This PR adds a simple acitivity indicator through the Admin for _most_ of the requests.
Closes #2548
=> 2548 - Adds loading indicators throughout TinaAdmin

.github/stale.yml
Config to enable the stale bot:
https://github.com/marketplace/stale
I kept the `daysUntilClose:` small so that we can clear out our big batch of stale issues initially, but we may want increase that after the first batch of issues are cleared out
=> Stale-ticket cleanup bot

.changeset/breezy-melons-carry.md, examples/basic/.tina/schema.ts, packages/tinacms/src/index.ts, packages/tinacms/src/types/SchemaTypes.ts, packages/tinacms/src/types/index.ts
This is the first step in the "Extending Tina work" this moves `defineSchema` and it's types to the `tinacms` package.
This is more to show that is it possible we will benefit from this work when we take on some of the extending tina work.
=> use defineSchema on the frontend

.changeset/fluffy-files-hope.md, packages/@tinacms/toolkit/src/packages/fields/components/Reference.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx, packages/tinacms/src/admin/index.tsx
A user can still disable `tina-admin` by setting the flag to `false`, but any lookups related to the flag will assume it is `true` if it isn't provided.
Closes #2612
=> 2612 - Sets the tina-admin flag to true by default

packages/@tinacms/toolkit/src/plugins/fields/markdown.tsx
The original link now 404s. Additionally, I don't think linking to the PR is necessary any longer.
=> update language on "unregistered field" placeholder

.changeset/five-beds-raise.md, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/cli/src/utils/script-helpers.test.ts, packages/@tinacms/cli/src/utils/script-helpers.ts
fixes [#2633](https://github.com/tinacms/tinacms/issues/2633)
Overrides existing script names instead of introducing new `tina-*` scripts
Docs here: https://github.com/tinacms/tinacms.org/pull/1251
=> feat: override existing scripts with cli init

packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx
Scott and I added the 30 second delay on **error** messaging because we felt the default timer for `alerts` is a bit short for something important like that.
For standard messages, like **success** toasts, we can stick to the default (we don't want a lingering message to be misleading if the user is navigating multiple Documents).
Related to #2635
=> 2635 - Minor change to the timeout for success messaging

.changeset/sixty-teachers-lie.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx, packages/tinacms/src/admin/api.ts, packages/tinacms/src/admin/components/GetCollection.tsx, packages/tinacms/src/admin/components/GetCollections.tsx, packages/tinacms/src/admin/components/GetDocument.tsx, packages/tinacms/src/admin/components/GetDocumentFields.tsx, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx
This was discovered during some dogfooding that the Global Nav attempts to retrieve the Collections list (via `GetCollections()`) _before_ the user is authenticated resulting in a misleading error message.
I've pulled `isAuthenticated()` into `TinaAdminApi` where it is simply calling `cms.api.tina.isAuthenticated()`.  I've wrapped the hooks in a check against that.
I also _fixed_ a bug with the loading animation not appearing (one I introduced, whoops).
Closes #2657
=> 2657 - Checks isAuthenticated() before making requests to GraphQL

packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/updated/plate/plugins/ui/combobox.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/updated/plate/plugins/ui/dropdown.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/updated/plate/plugins/ui/toolbar/toolbar-item.tsx
There was a double scrollbar always showing up in a few dropdown menus, this replaces it with a vertical scrollbar when needed.
Issue:
After change:
=> fix scrollbar ui bug

.changeset/dirty-peaches-greet.md, packages/@tinacms/toolkit/src/packages/fields/plugins/BlocksFieldPlugin/BlockSelector.tsx
Got the error:
```
Function components cannot have refs. Did you mean to use React.forwardRef()
```
I think the issue was that under the hood the `Popover.Button` was passing a ref to whatever was supplied in the `as` prop. Setting this to a `span` addresses it and seems ok from a UI perspective. 
cc @spbyrne
=> Fix console warning about a ref being passed to a function component

.changeset/brown-keys-hammer.md, packages/@tinacms/graphql/src/mdx/stringify.ts
Fix issue where un-normalized rich-text fields which send `null` values to the server on save would cause a parsing error
To reproduce this without the fix I think you just need the `rich-text` field to be nested inside an object list of some sort, add a new object and hit save.
=> Fix parsing error for `rich-text` fields with `null` values

.changeset/stupid-pumas-wait.md, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/updated/plate/plugins/ui/components.tsx, packages/@tinacms/toolkit/src/styles.css
This improves the spacing between elements in the rich text editor and adds styles for links.
=> Rich Text Styles

.changeset/loud-colts-jump.md, packages/tinacms/src/edit-state.tsx
Ensure client-side Tina code only runs on the browser. Without this check, we'd see a server/client mismatch like:
```
warning.js:33 Warning: Expected server HTML to contain a matching <div> in <body>.
```
cc @logan-anderson I know you've been around this area of the code a lot, do you see any potential issues in blocking this initially?
=> Ensure client-side Tina code only runs on the browser

.changeset/rude-seahorses-drop.md, .changeset/smart-starfishes-cross.md, packages/@tinacms/toolkit/package.json, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/updated/plate/hooks/use-resize.ts, packages/@tinacms/toolkit/src/packages/fields/plugins/wrapFieldWithMeta.tsx, packages/@tinacms/toolkit/src/packages/form-builder/fields-builder.tsx, packages/tinacms/src/rich-text.tsx
We've been getting a few messages in the console about these, most are benign but the one that does error in dev is the `error` message being an object.
The biggest change here is to `react-beautiful-dnd` which has gone from 11 to 13, though I haven't run into any issues, and from reading through them it doesn't look like we're relying on things that have broken https://github.com/atlassian/react-beautiful-dnd/releases.
=> Batch of console.error fixes

.changeset/angry-camels-appear.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Nav.tsx
This tiny change allows for the admin area to scroll for those with a large number of collections or a very short browser viewport (or both!).
=> Admin overflow fix

.changeset/eighty-jokes-kneel.md, packages/@tinacms/cli/src/cmds/compile/defaultSchema.ts, packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
Closes #2641 
This PR adds a simple MDX field to the example you get when you run `@tinacms/cli init`.
Nothing extremely beautiful. I considered pulling in the `CallOut` component that we have in some docs and blog posts but didn't want to add in that much boilerplate. But happy to make the component a bit more exciting it that seems desirable.
1. To test this I've been starting with a next-js starter `npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"`
2. Then you can use a dev version that I've pushed to npm `npx @tinacms/cli@0.0.0-2022221193751 init`
=> Add an MDX field to the CLI init example.

.changeset/famous-cheetahs-check.md, experimental-examples/tina-cloud-starter/.tina/__generated__/_schema.json, packages/@tinacms/sharedctx/src/edit-state-ctx.tsx
A small, but (potentially) significant change to the error message presented when TinaCMS is not found in the _app layout.
This updates the language to reference the new `TinaProvider` pattern and a link to the `Adding Tina` part of the setup docs:
```
Unable to find `TinaProvider`; did you forget to add the TinaCMS container to your _app layout?  See our setup docs: https://tina.io/docs/introduction/tina-init/#adding-tina
```
Closes #2590
=> 2590 - Improves no TinaEditProvider error message

.changeset/wicked-tips-itch.md, packages/@tinacms/datalayer/src/database/store/index.test.ts, packages/@tinacms/datalayer/src/database/store/index.ts
Closes #2734
Kelly correctly pointed out on that ticket that `0` was being evaluated as falsy so an operator was being returned as undefined.
=> fix: 0 no longer evaluated as false

.changeset/hot-tomatoes-speak.md, packages/@tinacms/graphql/src/database/index.ts
In the initial datalayer work for querying, the indexContentByPaths method was modified to take a Collection. This isn't available to all callers, so this change removes the parameter and uses the documentPath to determine the collection.
=> update Database.indexContentByPaths to not require collection parameter

.changeset/dry-mirrors-smile.md, packages/@tinacms/datalayer/src/database/store/index.test.ts, packages/@tinacms/datalayer/src/database/store/index.ts, packages/@tinacms/datalayer/src/database/store/level.ts, packages/@tinacms/datalayer/src/index.ts, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/spec/movies-with-datalayer/.tina/__generated__/_graphql.json, packages/@tinacms/graphql/src/spec/movies-with-datalayer/.tina/__generated__/_lookup.json, packages/@tinacms/graphql/src/spec/movies-with-datalayer/.tina/__generated__/_schema.json, packages/@tinacms/graphql/src/spec/movies-with-datalayer/.tina/__generated__/frags.gql, packages/@tinacms/graphql/src/spec/movies-with-datalayer/.tina/__generated__/queries.gql, packages/@tinacms/graphql/src/spec/movies-with-datalayer/.tina/__generated__/schema.gql, packages/@tinacms/graphql/src/spec/movies-with-datalayer/.tina/schema.ts, packages/@tinacms/graphql/src/spec/movies-with-datalayer/content/directors/francis.md, packages/@tinacms/graphql/src/spec/movies-with-datalayer/content/directors/george.md, packages/@tinacms/graphql/src/spec/movies-with-datalayer/content/movies/indiana-jones.md, packages/@tinacms/graphql/src/spec/movies-with-datalayer/content/movies/star-wars.md, packages/@tinacms/graphql/src/spec/movies-with-datalayer/content/movies/the-rock.md, packages/@tinacms/graphql/src/spec/movies-with-datalayer/content/relative/jett-lucas.md, packages/@tinacms/graphql/src/spec/movies-with-datalayer/content/relative/sofia-coppolla.md, packages/@tinacms/graphql/src/spec/movies-with-datalayer/requests.spec.ts, packages/@tinacms/graphql/src/spec/movies-with-datalayer/requests/getDirectorList/_query.movies-with-datalayer.gql, packages/@tinacms/graphql/src/spec/movies-with-datalayer/requests/getDirectorList/_response.json, packages/@tinacms/graphql/src/spec/movies-with-datalayer/requests/getMovieList/_query.movies-with-datalayer.gql, packages/@tinacms/graphql/src/spec/movies-with-datalayer/requests/getMovieList/_response.json, packages/@tinacms/graphql/src/types.ts
Update the datalayer movie tests in graphql and updates the data layer store code to fix these issues:
- properly escape the index field separate ('#') when it is present in a field and when used in a query
- pad numeric values for proper sorting. (NOTE: this hardcodes numeric values to 4 places. I'm currently thinking we can expose this as an optional field property in the schema but for now this should be sufficient for most use-cases)
- fix a bug in how fields were being ordered
- removes unused default property in the TinaIndex type
closes #2740 
You can test this by running `yarn dev-data` in the experimental examples tina-cloud-starter after adding a '#' character to the title of one of the blog posts and then executing a query like:
```
query GetPostsList(
$first: Float,
$after: …
```
=> fix: #2740: escape index field separator in input strings

.changeset/poor-elephants-sleep.md, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/updated/plate/plugins/ui/components.tsx, packages/@tinacms/toolkit/src/preflight.css
New list styles:
Previous, broken list styles:
Changes:
- Adds `li:before` reset to try and catch common user list styling.
- Adds left padding to lists.
- Resets padding on list elements.
- Explicitly sets list styling and positioning for both unordered and ordered lists.
=> Style Rich Text Input Lists

.changeset/curvy-socks-punch.md, cypress/integration/kitchen-sink/sidebar.spec.js, experimental-examples/kitchen-sink/.tina/__generated__/_graphql.json, experimental-examples/kitchen-sink/.tina/__generated__/schema.gql, experimental-examples/kitchen-sink/.tina/__generated__/types.ts, experimental-examples/kitchen-sink/content/page/home.mdx, experimental-examples/tina-cloud-starter/pages/_app.tsx, experimental-examples/unit-test-example/.tina/schema.tsx, packages/tinacms/src/hooks/use-graphql-forms.tsx, packages/tinacms/src/tina-cms.tsx
Should be merged after https://github.com/tinacms/tinacms/pull/2751
Closes https://github.com/tinacms/tinacms/issues/2417
You can disable this flag for now by specifying `cms.flags.set('use-unstable-formify', false)`.
=> Turn on new formify logic by default

.changeset/clean-panthers-sit.md, packages/@tinacms/graphql/src/database/index.ts
Fix issue where the store.clear() call was not being awaited which was causing the store to be in an inconsistent state after reindexing
=> fix: not awaiting call to store.clear() when indexing

packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx, packages/tinacms/src/admin/components/GetCollections.tsx, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx, packages/tinacms/src/hooks/use-graphql-forms.tsx, packages/tinacms/src/tina-cms.tsx
For #2519 
- This bubbles up errors that were previously being output as `cms.alerts` so that we instead display the error boundary.
- This also adds a link to the FAQ within the error boundary.
The messages that are shown within the error boundary are often not extremely useful, but it feels like there is probably another task to get these error messages sorted out.
To test:
I have a version `0.0.0-2022231135650` up with these changes.
=> Link to error faq in boundary and bubble errors to boundary

.changeset/cyan-bulldogs-judge.md, packages/@tinacms/graphql/src/database/index.ts
This change remove the whitespace when writing _graphql.json to help reduce the file size below the 1MB github api limit
Fix #2787
=> fix: reduce _graphql.json file size by eliminating whitespace

.changeset/pink-ads-jog.md, packages/@tinacms/graphql/src/mdx/parse.ts
Update the error message displayed when an unregistered MDX component is used to include link to documentation
=> fix: #2785: link to MDX docs when unregistered component is used

.changeset/giant-berries-glow.md, packages/@tinacms/datalayer/src/database/store/index.test.ts, packages/@tinacms/datalayer/src/database/store/index.ts
If you are filtering on a datetime field and the field is not indexed, the resolved value is a string date which needs to be converted. If the field is indexed, then it should just convert the string to a number
=> fix: non-indexed date values need to be converted from iso date format to number before comparison

.changeset/fluffy-feet-joke.md, packages/@tinacms/cli/src/cmds/baseCmds.ts, packages/@tinacms/cli/src/cmds/compile/index.ts, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/metrics/src/interfaces/index.ts, packages/@tinacms/metrics/src/telemetry/telemetry.ts
- Update tinacms CLI to support schemaFileType option (default 'ts') to allow user to specify the schema file type
- Update telemetry module to optionally check NO_TELEMETRY environment variable for disabling telemetry
=> feat: --schemaFileType cli option and NO_TELEMETRY env var

.changeset/little-dryers-smoke.md, packages/@tinacms/cli/src/cmds/compile/defaultSchema.ts, packages/@tinacms/cli/src/cmds/compile/index.ts, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/resolver/index.ts
Modify the schema generation in cli init to use the correct path separator depending on the platform and do some general refactoring of the database code which determines the collection based on the path.
=> fix: 2810: Database.put fails on windows

.changeset/spotty-poets-allow.md
Our latest release shows this error in the admin, but didn't surface as an issue in the monorepo.
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of `GetCollection`.
```
This is because the monorepo always uses the latest code from a given workspace. But a recent update that added the `OverflowMenu` as an export was missing a changeset
=> Add changeset which was missing when new export was added to the toolkit

.changeset/five-coats-protect.md, packages/@tinacms/toolkit/src/packages/fields/components/Select.tsx
Status Quo: The arrow icon on top of the HTML5 select element cannot be clicked by the user. There is also no hover effect.
The arrow icon is created using an react-icon svg which is moved on top of the dropdown.
Solution:
https://tailwindcss.com/docs/pointer-events
=> Improvement of select dropdown. Make arrow icon clickable

.changeset/rotten-teachers-divide.md, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx
Fixes part 1 of https://github.com/tinacms/tinacms/issues/2817
> Collections break if they implement multiple different templates (i.e. passing an array of templates rather than an array of fields). [...]
=> Fix issues with finding the template for multitemplate collections

.changeset/fifty-houses-confess.md, packages/@tinacms/toolkit/src/packages/styles/OverflowMenu.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx
This adjusts the list page overflow menu styling given the existing styling was designed for another context. This also removes the `showEmbed` prop given it was specific to the other context (MDX toolbar) and reverts to rendering the button as a button instead of a `<span>` (Maybe that was necessary for the toolbar?).
=> Style list page overflow menu

.changeset/six-geckos-decide.md, packages/@tinacms/toolkit/src/packages/styles/OverflowMenu.tsx
Adds a popover panel to the collection list page overflow menu based on @jeffsee55's fix #2861 for the MDX toolbar issue.
=> Popover panel

.changeset/famous-snails-refuse.md, experimental-examples/tina-cloud-starter/.tina/schema.ts, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/sidebar.ts
- Fixes sidebar 'overlay' mode
- Adds ability to set default sidebar state
```
cmsCallback: (cms) => {
cms.sidebar.position = "overlay";
cms.sidebar.defaultState = "closed";
...
```
=> Sidebar State

.changeset/fluffy-rocks-push.md, experimental-examples/tina-cloud-starter/.tina/schema.ts, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/SidebarBody.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/sidebar.ts
The sidebar nav requires context provided by the `TinaProvider` to work, making it break when it's used outside of that context. This allows the user to set `cms.sidebar.renderNav = false`, disabling the nav and adjusting other components to render accordingly.
=> Add ability to hide sidebar nav

.changeset/wild-poets-push.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/NoFormsPlaceHolder.tsx, packages/@tinacms/toolkit/src/packages/styles/Button.tsx, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchSwitcher.tsx
The branch switcher will now display a helpful message when running in local mode rather than simply appearing broken. 
I've adapted the button component to render as a link when needed. Previously we had a one-off component for doing this in the sidebar empty state component, which I've removed. 
Closes #2501.
=> Local Mode Branch Switcher Warning

.changeset/fair-chairs-search.md, packages/@tinacms/cli/src/cmds/start-server/server.ts, packages/@tinacms/graphql/src/resolve.ts, packages/@tinacms/graphql/src/resolver/index.ts, packages/@tinacms/graphql/src/types.ts
Part of the Repo-based Media push, this adds an extra `config` to `resolve()` that contains (for now) just `useRelativeMedia: true`.
Locally, this value will always be `true`.
In the future, a companion PR to `tina-cloud` will include a slightly different `config`:
```
{ useRelativeMedia: false, clientId: app.client_id }
```
which will be used to determine the location of the file on `assets.tinajs.io`. (https://github.com/tinacms/product-roadmap/issues/161)
> Note: This can merge without the sister PR.
Closes https://github.com/tinacms/product-roadmap/issues/50
=> Adds `useRelativeMedia` to local GraphQL

.changeset/bright-seahorses-warn.md, packages/@tinacms/cli/src/cmds/baseCmds.ts, packages/@tinacms/cli/src/cmds/start-server/index.ts, packages/@tinacms/graphql/src/build.ts, packages/@tinacms/graphql/src/index.ts
This adds a new CLI flag (`tinaCloudMediaStore`) and writes it to the _schema.json when present.
This will be used to activate sync from github to the tina media store
=> feat: add `tinaCloudMediaStore` cli flag

.changeset/chatty-olives-wink.md, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/ListFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/wrapFieldWithMeta.tsx, packages/@tinacms/toolkit/src/packages/form-builder/fields-builder.tsx
Fixes #2891 (error messages not wrapping) and replaces the remaining field meta styled components with tailwind components.
=> Replace field meta styled components with tailwind

.changeset/healthy-mangos-rule.md, .changeset/twenty-cats-bow.md, packages/@tinacms/cli/src/cmds/compile/defaultSchema.ts, packages/@tinacms/cli/src/cmds/compile/index.ts, packages/@tinacms/cli/src/cmds/start-server/index.ts, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/database/util.ts
- Addresses #2910 by calling close() on store db before regenerating the tina folder
- Fixes inconsistent path separator handling by normalizing the path whenever calling bridge or store functions that take a filepath
- Reverts changes to init which are causing #2920
=> fix experimental data on windows

.changeset/ninety-roses-cheer.md, packages/@tinacms/graphql/src/resolver/index.ts, packages/@tinacms/graphql/src/types.ts
Minor change that allows for `tina-cloud` to provide an override to `assetsHost` via a `config` value.
Right now, that override is provided via the environmental variable `TINA_CLOUD_MEDIA_STORE_ASSETS_HOST` (defaults to `assets.tina.io`).
Related to https://github.com/tinacms/tina-cloud/pull/1546
=> Determine `assetsHost` from `config` for Tina Cloud Media Store

.changeset/tame-nails-crash.md, packages/tinacms/src/auth/TinaCloudProvider.tsx
Addresses #2925. It appears that for contextual editing, the client was being configured with the default branch instead of the branch in local storage. This PR updates the logic in the tina cloud provider to update the branch when the value is read for local storage
=> fix: #2925: update current branch from local storage

.changeset/warm-adults-occur.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx
Because the CMS supports sub-directories, we need to account for the potential existence of those in any navigation.
The sublinks for items in the CMS were only using `filename` (which is only the `basename`).
In other places, we use `breadcrumbs` which is an array of all directories leading up to the `basename`).
Closes #2935
=> 2935 - Fixes subitem links to use breadcrumbs

.changeset/red-lemons-mate.md, packages/@tinacms/toolkit/src/packages/styles/Button.tsx, packages/tinacms/src/preflight.css, packages/tinacms/src/styles.css
The css preflight was only being included in `@tinacms/toolkit` and not `tinacms` given it was assumed that would always be wrapped in the toolkit's styles, but this isn't the case of at least the login screen. I just copied it over, but it's possible the `tinacms` package could import the preflight from the toolkit.
Before: 
After:
=> Fix Login Styles

.changeset/bright-tables-wave.md, packages/@tinacms/scripts/src/index.ts, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/index.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/ui/toolbar/toolbar-item.tsx, packages/@tinacms/toolkit/src/styles.css, packages/react-tinacms-editor/src/components/ProsemirrorEditor/index.tsx
This configures and uses a custom wrapper class for the Tailwind typography plugin that we're using to wrap our rich text field. This will prevent bleed-through to the user's site if they're also using the plugin.
Closes #2952 (Thanks to user [Webarkitekt](https://github.com/Webarkitekt) for providing a solution!)
=> Prose Wrapper Class Fix

.changeset/stale-cooks-obey.md, packages/@tinacms/cli/src/server/models/media.ts
It turns out out media manage expects the paths of dirs to be relative to the parent. The CLI was returning local media folders with full paths which was causing issues.
=> media manage uses relieve dir paths

.changeset/yellow-lies-fetch.md, packages/@tinacms/cli/src/server/models/media.ts, packages/@tinacms/cli/src/server/routes/index.ts, packages/@tinacms/toolkit/src/packages/core/media-store.default.ts, packages/@tinacms/toolkit/src/packages/fields/plugins/BlocksFieldPlugin/BlockSelectorBig.tsx
Basically uses `offset` and `limit` by treating the `offset` value like a `cursor`.
Tested with both 26 and 6 items and appears to be working correctly for both.
=> Enables pagination for local media `list` endpoint

.changeset/tiny-bobcats-jog.md, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/index.tsx
Given the rich text input styles are provided by a wrapper div, I've changed `focus` for `focus-within` so the styles will work properly.
=> Fix rich text focus styles

.changeset/long-planes-hide.md, packages/tinacms/src/internalClient/index.ts
`internalClient` was swallowing up an `error` and just using `statusText`.
I modified the error message to continue to do that, but also check the `res` for a `message` key and use that, as well.
This should result in more useful error messages (specifically, a `404` not only responds with `Not Found`, but also what document the server failed to find).
Before
After
Addresses part of https://github.com/tinacms/tinacms/issues/2917
=> 2917 - Surface `message` when available for errors from `client`

.changeset/quiet-chairs-lay.md, .github/workflows/danger.yml, packages/tinacms/src/hooks/formify/index.ts
When a few changesets of the same field are batched by React the changeset length doesn't change. The `useEffect` dependency here isn't quite right, but stringifying instead of relying on the length does the job
Closes https://github.com/tinacms/tinacms/issues/3023
=> Fix an issue where changes to a field weren't reflected on the page when typing quickly

.changeset/happy-kids-rest.md, packages/@tinacms/datalayer/src/database/store/index.test.ts, packages/@tinacms/datalayer/src/database/store/index.ts
- limit the index value to 100 characters (maximum) when generating keys for store
=> feat: ENG-412: limit index values in keys to 100 characters

.changeset/dull-ads-enjoy.md, packages/@tinacms/datalayer/src/database/store/index.test.ts, packages/@tinacms/datalayer/src/database/store/index.ts
This PR fixes handling of null / undefined values when generates index keys in data layer. With this change, if a field is defined as null / undefined, a key will not be generated and it won't be included in the index for that field.
=> fix: ENG-415: fix data layer handling of null/undefined values

.changeset/wicked-chefs-count.md, packages/@tinacms/cli/src/buildTina/index.ts
Add a `mkdirp` command to ensure generated folder is present before trying to access it.
=> ensure generated folder is created before building

.changeset/real-dots-build.md, experimental-examples/tina-cloud-starter/package.json, packages/@tinacms/cli/src/cmds/query-gen/genTypes.ts
-  We should only do that check when the `local` flag isn't set.
-  When local isn't set, throw an error instead of a warning.
- It would be helpful if it told you exactly what was not configured properly (E.g, clientId missing)
=> Throw an error when client not configured properly in production

.changeset/shy-crabs-retire.md, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
Fixes issue where init would setup the wrong path if the user had there app in a `src` dir
=> Example page accounts for apps that use the src dir

.changeset/moody-masks-confess.md, packages/tinacms/src/tina-cms.tsx
Remove one of the type options for defineConfig. 
Small breaking change for anyone using the fairly dated config. 
As a result of this, our types become more strict to that `client` will be required when `apiURL` isn't provided
=> BREAKING CHANGE: Deprecate dated defineConfig use

.changeset/unlucky-dots-end.md, packages/@tinacms/cli/src/cmds/compile/index.ts
Mkdir was causing anyone using the windows OS to crash. This PR uses mkdirp instead
fixes #3076
=> use mkdirp instead of mkdir

.changeset/red-moose-grin.md, .gitignore, packages/@tinacms/mdx/src/parse/index.ts
In `experimental-examples/tina-cloud-starter` new document creation was resulting in this error:
```
GraphQL request:3:9
2 |       mutation($collection: String!, $relativePath: String!, $params: DocumentMutation!) {
3 |         createDocument(
|         ^
4 |           collection: $collection,
More error context below
Error Parsing file test1.mdx collection posts. Please run "tinacms audit" or add the --verbose option  for more info
TypeError: Cannot read property 'valueOf' of undefined
at replaceAll (/Users/kldavis/projects/tinacms/packages/@tinacms/mdx/dist/index.js:244727:18)
at /Users/kldavis/projects/tinacms/packages/@tinacms/mdx/dist/index.js:244677:28
at Array.forEach (<anonymous>)
at markdownToAst (/Users/kldavis/projects/tinacms/packages/@tinacms/mdx/dist/index.js:244672:66)
at …
```
=> fix: ENG-484: null check in markdown to ast to fix new doc creation

.changeset/twenty-cups-grow.md, packages/@tinacms/scripts/src/index.ts
@logan-anderson I think the fix you've provided [here](https://github.com/tinacms/tinacms/pull/3105) works because Next splits the es module with properly so it removes the `handler.js` code. But I think that's only necessary because I'd changed the build target for node packages. 
This PR should fix that
ENG-485
=> Fix issue building node packages to non-index.js files

.changeset/many-gifts-dream.md, packages/@tinacms/mdx/src/parse/plate.ts, packages/@tinacms/mdx/src/stringify/index.ts
In some cases the an image is dropped it without being wrapped in a `<p>`, we weren't handling that properly so this
Closes https://github.com/tinacms/tinacms/issues/3108
=> Fix regression in handling images in rich-text

.changeset/fuzzy-students-trade.md, packages/@tinacms/mdx/src/stringify/marks.ts, packages/@tinacms/mdx/src/tests/autotest/kitchen sink.md, packages/@tinacms/mdx/src/tests/autotest/kitchen sink.test.ts
Add missing call to `linkifyTextNode` when handling `inlineCode` elements.
Also add a test case for #3078.
=> Fix stringification of code element nested in link

.changeset/quick-seas-eat.md, packages/tinacms/src/admin/components/GetCollection.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx
A collection doesn't have to have fields, so optional chain off the `fields` property.
This does mean collections with `templates` aren't sortable.
Fixes #3087.
=> Fix list page breaking for templates on collection

.changeset/tall-forks-travel.md, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/hooks/use-content-creator.tsx
Allows numeric characters at the start of filenames to facilitate existing practices which include storing blog posts with the date prefixed or date based folder hierarchies. (e.g. Jekyll style `2022-08-21-blog-title-slug.md` files)
also updated a regex that appeared to be malformed and did not match the error description by allowing `,` characters.
=> feat: allow paths to start with numeric characters

.changeset/clean-pets-poke.md, packages/@tinacms/datalayer/src/database/bridge/isomorphic.ts
Fix issue where if a subfolder exists in a collection that matches a document, editing that document creates null commits.
The logic in the git tree walker was treating a subfolder matching the path of the file as a parent path of that file. This is fixed by adding an additional check such that when the parent directories are the same, it requires an exact match instead of a startsWith.
=> fix: ENG-502: fix subfolder matching document name issue

.changeset/wild-cobras-beam.md, packages/@tinacms/toolkit/src/packages/alerts/alerts.ts, packages/@tinacms/toolkit/src/packages/react-alerts/Alerts.test.tsx, packages/@tinacms/toolkit/src/packages/react-alerts/Alerts.tsx, packages/tinacms/src/admin/components/GetCollection.tsx, packages/tinacms/src/admin/components/GetDocument.tsx, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx, packages/tinacms/src/hooks/formify/index.ts, packages/tinacms/src/hooks/formify/util.ts
- Fixes alerts so only the close button dismisses them (or the timeout) and text wraps, allowing for longer alert messages.
- Converts error alerts to a blocking modal that doesn't have a timeout.
- Error modal supports providing a component instead of a string so that formatting and links can be provided, but it will render out strings inside a paragraph so that it's compatible with existing errors.
Fixes #3101
Example:
Code: 
```
cms.alerts.error(() => {
return (
<>
<p className="text-base mb-3">
This is an example error with a link. You can click the link
without dismissing it.
</p>
<a
className="flex items-center transition-all duration-150 ease-out text-blue-600 hover:text-blue-400 hover:underline no-underline"
href="#"
>
Example Link{' '}
<MdArrowForward className="w-4 h-auto ml-1.5 …
```
=> Alert Improvements

.changeset/shy-mirrors-laugh.md, packages/tinacms/src/admin/components/GetCollection.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx
Fixes an issue where collections which used  would error on the admin list page due to the recent addition of filters. Filters will only work for collections with  at this time
Closes https://github.com/tinacms/tinacms/issues/3132
=> Fix admin list error on collections with templates

.changeset/spicy-poems-jog.md, experimental-examples/tina-cloud-starter/.tina/config.ts, packages/@tinacms/cli/src/cmds/query-gen/genTypes.ts, packages/@tinacms/schema-tools/src/types/config.ts, packages/tinacms/src/unifiedClient/index.ts, packages/tinacms/src/utils/parseUrl.ts
- remove the check for the correct domain name (we are generating this so it should never be incorrect)
- use the override url if it is provided
=> use Tina url override in generated client

.changeset/fair-horses-yell.md, packages/@tinacms/cli/src/cmds/start-server/index.ts
Fixes a few issues with the CLI error handling:
- Fixes issue where subprocess would still run if port was in use.
- Don't exist with success when initial build fails
=> port in use: CLI error handling

.changeset/polite-mails-smile.md, packages/@tinacms/toolkit/src/packages/core/media-store.default.ts
Fix issue where drag-n-drop on image fields wasn't working with the repo-based media on local dev.
I think some of us saw it working and not working at times, I assume that's because the `persist_cloud` returns a `src` attribute so things are fine there.
=> Fix drag-n-drop on local dev

.changeset/slow-clocks-play.md, packages/@tinacms/toolkit/src/packages/fields/plugins/wrapFieldWithMeta.tsx, packages/@tinacms/toolkit/src/packages/form-builder/fields-builder.tsx
Reverts tinacms/tinacms#3177
This seems to be causing some issues. The label is under the fields. 
I'd like to know a bit more context about this PR and why it's necessary to reverse the fields and handle the order with `flex-col-reverse`
cc @Phoenix-Alpha
=> Revert "Fix rich text dropdown overlap issue"

.changeset/gold-guests-notice.md, packages/@tinacms/cli/src/cmds/init/index.ts
Exit tinacms init when there's an error with dependency install
Exit with an error when a dependency error occurs:
Instead of:
=> fix: Exit init on dep install error

.changeset/tough-lemons-ring.md, packages/@tinacms/toolkit/package.json, packages/@tinacms/toolkit/src/packages/core/media-store.default.ts, pnpm-lock.yaml
The contentType function in mime-types is no longer working (suspect a bundling issue). This is not necessary, though, since the mime type is already supplied on the file object. This PR removes the library and switches to using that field.
=> fix: use type field on file object instead of mime-types library due to issue discovered via #3254

.changeset/wise-eels-hammer.md, packages/@tinacms/graphql/src/index.ts
Fix for "callback is not a function" when running tinacms dev
=> fix: fs.rm "callback is not a function"

.changeset/soft-forks-exist.md, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/ui/components.tsx
Fix #3253 bullet/numbered list items overflow out of text fields
- Add `w-full` class to list item content to prevent text overflow to the right of sidebar as shown in #3253.
- Also change `<ol></ol>` element class from `pl-2` to `pl-4` to fix numbered list's marker overflow to the left of text field.
=> fix: bullet/numbered list overflow out of text field (#3253)

.changeset/three-masks-sell.md, packages/@tinacms/app/package.json, pnpm-lock.yaml
Using the latest version of Vite (3.2.0), the setting in a tsconfig.json of `"jsx":"preserve"` causes the build to fail for `.tsx` files using `jsx` in them. 
I'm still trying to pin down the issue but this should resolve it for now.
=> Pin vite to 3.1.8

.changeset/nine-boxes-pretend.md, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/create-mdx-plugins/component.tsx
As reported on the following issue: #3309 When two blocks having the "DotMenu" are below each other, if you try to open the menu of the first block it will be shown below the second block.
The issue was solved by moving the classes that are defining the position of the element from the `div` that is setting its appearance to the `Popover.Panel` element.
Before: 
After:
=> Fix dot menu popover displayed under blocks

.changeset/strange-items-cheat.md, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/ui/toolbar/toolbar-item.tsx
As described in the issue opened earlier #3324 : The toolbar "embed" button shows a wrong background when opened and hovered.
Under these conditions the background turns blue and hides the text, since the text has the same color.
The issue was solved by removing the `hover:bg-blue-500` class from the always applied classes of the button, since it has the `bg-blue-500` class when the open state is `false`. 
Let me know if this behavior is the correct one, if not, I will fix it by changing the text color.
Before: 
This is a GIF click on it please.
After:
This is a GIF click on it please.
=> Fix wrong background when hovering "Embed" button inside the toolbar

.changeset/neat-readers-pull.md, packages/tinacms/package.json, pnpm-lock.yaml
`fetch-ponyfill` has `node-fetch` as a dependency, but `node-fetch` requires `encoding` which printed a warning to the console. Might be more to the story but seemed like an easy fix cc @logan-anderson
=> Fix warning about missing "encoding" dependency

.changeset/pretty-mails-pay.md, packages/@tinacms/schema-tools/src/schema/TinaSchema.ts
We weren't calling tthe transform recursively so deeper shapes didn't receive the transformed shape.
Closes https://github.com/tinacms/tinacms/issues/3338
=> Fix issue saving deeply nested objects in visual mode

.changeset/eleven-donkeys-allow.md, examples/kitchen-sink/.tina/queries/documents.gql, examples/kitchen-sink/content/post/tinacms-v0.69.7.mdx, examples/kitchen-sink/pages/collection/[collection]/[filename].tsx, examples/kitchen-sink/pages/documentation/index.tsx, examples/kitchen-sink/pages/node/[...filename].tsx, examples/kitchen-sink/pages/node/[filename].test.ts, examples/kitchen-sink/pages/node/blueprints.json, examples/kitchen-sink/pages/node/formified-query.gql, examples/kitchen-sink/pages/page/index.tsx, examples/kitchen-sink/pages/post/index.tsx, packages/@tinacms/app/appFiles/src/lib/formify/index.ts, packages/@tinacms/app/appFiles/src/lib/machines/document-machine.ts, packages/@tinacms/app/appFiles/src/lib/machines/query-machine.ts, packages/@tinacms/app/appFiles/src/preview.tsx
The PR removes all of the logic around generating blueprints, and instead just calls the GraphQL `graphql` function client-side. This is the same function from GraphQL that we use on the backend, but instead of resolving the content from the database, we resolve it from the Tina forms. I realized I was basically recreating this logic with the blueprint stuff, and this is a much simpler approach which I think is a lot less error-prone. 
This should improve performance on formifying pages, which isn't really noticeable locally but makes a big difference on Tina cloud. Previously we were making the following queries before the user could see the forms in the sidebar:
Old pipeline
- Introspection query (we need the schema from the server)
- Optimize the query (this basically inlines fragments …
=> Simplify formify resolve

.changeset/slow-eyes-pretend.md, packages/@tinacms/mdx/package.json, packages/@tinacms/mdx/src/parse/index.ts, packages/@tinacms/mdx/src/parse/remarkToPlate.ts, packages/@tinacms/mdx/src/tests/autotest/image.test.ts, packages/@tinacms/mdx/src/tests/autotest/kitchen sink.test.ts, pnpm-lock.yaml
Closes https://github.com/tinacms/tinacms/issues/3310
closes ENG-3310
Treat images as block-level when they're isolated in a paragraph.
Previously all images were nested inside `<p>` elements when coming from the server, but treated as block level by the rich-text editor. This resulted in a scenario where new paragraphs adjacent to images were nested
in parent `<p>` tags, which caused an error.
=> Unwrap image block

.changeset/calm-planes-join.md, examples/kitchen-sink/package.json, packages/@tinacms/app/package.json, packages/@tinacms/app/src/index.ts
Previously we were running a special `npm install` command whenever we started the Tina dev server to get the `@tinacms/app` dependencies in the right location. However that command has failed for some users for reasons that aren't super clear. It also feels a little bit brittle to run `npm install` and aside from a larger bundle for the `@tinacms/app` I don't see any downsides.
=> Include node_modules as part of the build in @tinacms/app

.changeset/small-rings-knock.md, packages/@tinacms/toolkit/src/packages/form-builder/FormBuilder.tsx, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx
As reported in the issue #3362 the creation of a post having a filename that already exists fails without giving a message to the user. After the failed submission if the user tries to edit the filename the submit button remains disabled.
In debugging why the button remains disabled, I found that: in case the submit response is an error the `invalid` property remains `true`.
In order for the button to be enabled again, I modified the condition for which it is considered disabled.
The new rule is: 
```
disabled={pristine ||  submitting || hasValidationErrors || (invalid && !dirtySinceLastSubmit)}
```
It will always be disabled in case there is a client validation error on one of the fileds. But it will be enabled if the form is invalid and after the last submission the user does some edits …
=> Fix ux for failed document creation 

.changeset/three-phones-fix.md, packages/@tinacms/toolkit/src/packages/styles/OverflowMenu.tsx
The `OverflowMenu` of collection items is not correctly placed on top of the other elements.
When the popover is open, some of the elements that should be under it are visible and clickable.
You can see the issue here: https://www.loom.com/share/f0fcb48284374cbe889da8bda0ae1ba2
I have fixed the issue by moving the classes that are defining the position of the element from the div that is setting its appearance to the `Popover.Panel` element.
You can see the working solution here: https://www.loom.com/share/c6011fe901794771a784419d8e45bc9a
This issue was similar to the one I have already solved in this PR #3317
=> fix OverflowMenu of collection items not correctly placed on top of other elements

.changeset/perfect-dragons-flash.md, packages/@tinacms/app/appFiles/src/preview.tsx
This simplifies the preview markup and removes the wrapping divs around the iFrame. This removes extra scrollbars that displayed if you were using an external mouse.
=> remove iframe wrapper

packages/@tinacms/app/appFiles/src/preview.tsx
The `formifyCallback` is expected by the `<QueryMachine />` machine as you can see on this line, which accesses the `props.formifyCallback` value: https://github.com/tinacms/tinacms/blob/main/packages/@tinacms/app/appFiles/src/preview.tsx#L86. And that `formifyCallback` function is a valid option on the `Config` object: https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/index.ts#L96-L109, however it wasn't being passed through to the component that was attempting to use it. This update fixes that bug by ensuring the `formifyCallback` function is properly passed through, making it available within the `context` for the `query-machine` and `document-machine` respectively.
Using the latest version of TinaCMS, you can see this issue by setting a `formifyCallback` like the …
=> Pass `config.formifyCallback` to `<QueryMachine>`

.changeset/swift-pens-bow.md, packages/@tinacms/app/appFiles/src/lib/machines/query-machine.ts
How we're using graphql in the client is unconventional, and we actually need to look at `info.fieldNodes` to determine where the data might actually be. This isn't usually the way things work, but since we're resolving data from a _previous_ query (that ran before being passed to the `useTina` hook, our needs are a bit different, hence the awkward workaround.
=> Fix issue resolving alias fields when passing through the `useTina` hook

.changeset/gorgeous-donkeys-itch.md
I see a line in the latest changeset may have blocked the builds. (Mixing ignored and unignored changesets?)
https://github.com/tinacms/tinacms/actions/runs/3586233293/jobs/6035177827#step:12:42
Not 100% if removing that line retroactively fixes things or not.
=> rm broken line from changeset

.changeset/lazy-cherries-serve.md, packages/@tinacms/app/appFiles/src/lib/machines/query-machine.ts
Fix issue with formify logic that returned undefined for falsy values like "" or 0
=> Fix issue with formify logic that returned undefined for falsy values

.changeset/fast-apples-promise.md, packages/tinacms/src/rich-text/index.tsx
This enables the consumer to post-process the text before rendering.
For context, I'd like to enable `smartypants` on the text but there isn't a great place to hook into the text to call the function. Feasibly, I could walk the tree myself & call it on the text elements, but this seemed simpler. Obviously, totally understandable if you don't want this added upstream.
=> Enable custom text component

.changeset/red-moose-search.md, packages/@tinacms/cli/src/cmds/statusChecks/checkClientInformation.ts
Add's more context to the error message.
This will tell the user the `.tina/__generated__/_schema.json` is not on Github. 
Looks like this.
=> added more context to error message

.changeset/afraid-lions-stare.md, examples/basic-iframe/pages/index.js, packages/@tinacms/app/appFiles/src/preview.tsx
Previously, `useEditState` would not work if called before `useTina`. This PR fixes it so that `useEditState` work no matter what.
=> fix useEdit state from requiring querys to be active

.changeset/twelve-geese-prove.md, packages/@tinacms/toolkit/src/tina-cms.ts
The cloud project UI received an update that added semantic routing, so the old `/0` and `/3` type links don't work, this updates them.
=> Fix Cloud Sidebar Links

.changeset/young-turtles-check.md, packages/@tinacms/schema-tools/src/types.ts, packages/@tinacms/scripts/src/index.ts, packages/@tinacms/toolkit/src/packages/fields/plugins/BlocksFieldPlugin/index.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/ListFieldMeta.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/ListFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/index.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/wrapFieldWithMeta.tsx, packages/@tinacms/toolkit/src/packages/form-builder/FormBuilder.tsx
https://user-images.githubusercontent.com/5075484/211587949-a19681e1-f8c9-4f91-820a-f7f55eeb0e6d.mp4
The List, Group List and Block fields weren't displaying errors. I've created a list meta wrapper component that provides the label, description, and error UI. It accepts an 'actions' prop that allows each field to control that logic.
This also updates the error styles to give it a bit more whitespace and a quick slide-in animation.
Fixes #3495
The field UI object now accepts a min and max when the field is `list: true`. If the list/group list/block field is at the max or min value, the add or remove buttons are disabled. If the min and max values are the same, the field is considered 'fixed length' and the add/remove buttons are removed entirely, unless the data is invalid (you can still …
=> List Field Meta Wrapper, Form Improvements

.changeset/brown-scissors-sneeze.md, packages/@tinacms/schema-tools/src/schema/TinaSchema.ts
Fix issue where deeply nested template objects inside field objects weren't transformed on save properly
=> Fix issue with deeply nested object transforms

.changeset/smooth-jokes-work.md, packages/@tinacms/graphql/src/resolver/index.ts
Fixes an issue that @jeffsee55 found where a user could not save a top level array that was empty.
Potential fix for #3536
=> Allow user to save an empty array

packages/@tinacms/app/appFiles/src/fields/rich-text/monaco/index.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/index.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/create-invalid-markdown-plugin/index.tsx
Currently, when you make a change in raw-mode with an error, when you switch to the rich-text editor, your changes are quietly wiped. Saving also quietly omits any changes after you introduced a rich-text editor. 
This changes that behaviour a bit:
- Changes to raw-mode / rich-text-editor are always persisted in the form state (even with an error)
- The form now gets a validation error when we can't parse rich-text (to block saving)
- I added a button to jump to the raw mode if there's an error (@spbyrne may want to take a look at the styling)
https://www.loom.com/share/040cbb84408a442b93f60c9b0731cca6
fixes ENG-778
fixes ENG-784
fixes ENG-776
fixes ENG-781
=> Set input value even with errors in rawmode

.changeset/nasty-tigers-own.md, packages/@tinacms/app/src/index.ts
Fixes #3579 by exposing `NODE_ENV`, `NEXT_PUBLIC_*`, `TINA_PUBLIC_*`, and `HEAD` (for integration with Netifly) environment vars in the admin.
=> no long express all env vars to the frontend

.changeset/beige-brooms-camp.md, packages/@tinacms/graphql/src/database/index.ts
Fixes issue where database was failing to check if a level instance was set resulting in null error. This catches the condition and throws a more user friendly error.
=> fix: detect LevelDB initialization error and throw a meaningful error

.changeset/five-socks-argue.md, packages/@tinacms/graphql/src/database/index.ts
Fix `Could not get value` error when querying non-existent content
=> fix: handle LEVEL_NOT_FOUND when fetching from level

.changeset/eleven-mice-kneel.md, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/database/level.ts
- use proxy to centralize the LEVEL_NOT_FOUND errors
- fix the database versioning logic
=> refactor: centralize LEVEL_NOT_FOUND error handling

.changeset/plenty-bottles-attend.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx
This fixes the error that happens when a user clears the date input from a valid date.
=> Only format filter date when valid

.changeset/flat-terms-fail.md, packages/tinacms/src/admin/index.tsx
Only redirect when the user has a `ui.router` in there collection.
See [this video](https://www.loom.com/share/69345c21c3f94c57997ac0a19c9768a8) for more details.
=> Do not redirect by to contextual editing by default. 

.changeset/poor-wasps-cough.md, packages/@tinacms/app/appFiles/src/fields/rich-text/monaco/error-message.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/monaco/error-message.tsx
https://www.loom.com/share/cea9252a5c074f289fd4c84bef7c8ba0
The error wasn't always visible.
@spbyrne may want to take a peek
=> fix: make rich text errors scrollable

.github/workflows/publish.yml
This PR adds a Github action that automates the creation of PRs to the starters. I am not 100% sure that this works (I am not sure of a good way to test it) but we can test it on the next release.
=> Automate Creating PRs to bump the Tina version

.changeset/polite-poets-collect.md
There was a changeset that was added that included the starter packages. This caused an error to occur during publish. This PR should fix the error.
=> remove starters from changeset

.changeset/pink-wolves-boil.md, packages/@tinacms/toolkit/src/components/media/breadcrumb.tsx
- Previously the `dirname` function had a return value of type `RegExpMatchArray | null` - the result of calling `String.prototype.match()`
- However the `prevDir` variable must be of type `string` (or undefined or null) as it is passed directly to the `setDirectory` function
- Previously the media manager crashed when clicking the back link and threw a `TypeError` with the message `directory.replace is not a function` (given you can't call `replace` on a `RegExpMatchArray`)
- This fix extends the regex in the `dirname` function to use a capturing group and ensure it always returns a `string` or `undefined`
=> fix: previous directory link in Tina MediaManager

.changeset/dull-zebras-develop.md, packages/tinacms/src/tina-cms.tsx
This warning shows up regardless of your config, it's also been a while since the alternate setup was used so probably safe to remove this.
Closes https://github.com/tinacms/tinacms/issues/3639.
=> Remove warning about TinaProvider

.changeset/sour-gifts-double.md, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchSwitcher.test.tsx, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchSwitcher.tsx, packages/tinacms/src/admin/components/FullscreenError.tsx, packages/tinacms/src/admin/components/GetCollection.tsx, packages/tinacms/src/admin/components/GetDocument.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx
Previously, when our locally cached branch doesn't exist, things kind of blow up in the CMS.
I added a minimal error screen, but more importantly, the toolbar stays accessible (so the user can change branches and resolve the issue).
closes ENG-802
=> fix: When current branch doesn't exist, don't blow up

.changeset/silver-pianos-joke.md, packages/@tinacms/graphql/src/database/index.ts
I'm not sure what the circumstances are for when `collection` is null, but I ran into it calling `database.indexContentByPaths`, and it looks like Tina Cloud would see the same issue [here](https://github.com/tinacms/tina-cloud/blob/16e2d4e8db11201874ac7b7753cf1e1aaecdf083/js/content-api/src/database/index.ts#L164)
=> Fix issue where `getTemplatesForCollectable` was being called with a nullable value

.changeset/clever-emus-notice.md, packages/@tinacms/graphql/package.json, packages/@tinacms/scripts/package.json, pnpm-lock.yaml
This bumps the esbuild versions used by @tinacms/graphql and @tinacms/scripts to match that used by @tinacms/cli.  The version currently used is affected by an installation bug on Ubuntu 20.04, resulting in @tinacms/cli being uninstallable.
Fixes #3668.
=> Bump esbuild versions in graphql/scripts

.changeset/quiet-points-hammer.md, packages/@tinacms/mdx/src/next/stringify/pre-processing.ts, packages/@tinacms/mdx/src/next/tests/image-at-block-level/field.ts, packages/@tinacms/mdx/src/next/tests/image-at-block-level/index.test.ts, packages/@tinacms/mdx/src/next/tests/image-at-block-level/node.json, packages/@tinacms/mdx/src/next/tests/image-at-block-level/out.md, packages/@tinacms/mdx/src/stringify/index.ts
We recently updated a bunch of our mdast dependencies which is the only thing I can think of at the moment which might have broken this. Previously we allowed an `image` block to pass through as flow content, even though it's not. Still trying to track down what changed but I _think_ it was from an external dependency bump. Tests didn't catch this because the backend tests assume a valid ast going in and out, and our rich-text editor sometimes needs to fudge things a bit for compatibility. Still looking into it but this should fix the immediate need.
=> Update handling of top-level images during stringify

.changeset/curly-rules-flow.md, examples/kitchen-sink/.tina/config.tsx, packages/@tinacms/mdx/src/next/parse/markdown.ts, packages/@tinacms/mdx/src/next/shortcodes/lib/factory-tag.ts, packages/@tinacms/mdx/src/next/shortcodes/lib/jsx-flow.ts, packages/@tinacms/mdx/src/next/shortcodes/lib/syntax.ts, packages/@tinacms/mdx/src/next/shortcodes/lib/util.ts, packages/@tinacms/mdx/src/next/shortcodes/mdast/index.ts, packages/@tinacms/mdx/src/next/tests/block-with-html-children-1/field.ts, packages/@tinacms/mdx/src/next/tests/block-with-html-children-1/in.md, packages/@tinacms/mdx/src/next/tests/block-with-html-children-1/index.test.ts, packages/@tinacms/mdx/src/next/tests/block-with-html-children-1/node.json, packages/@tinacms/mdx/src/next/tests/block-with-html-children-1/out.md, packages/@tinacms/mdx/src/next/tests/block-with-html-children-2/field.ts, packages/@tinacms/mdx/src/next/tests/block-with-html-children-2/in.md, packages/@tinacms/mdx/src/next/tests/block-with-html-children-2/index.test.ts, packages/@tinacms/mdx/src/next/tests/block-with-html-children-2/node.json, packages/@tinacms/mdx/src/next/tests/block-with-html-children-2/out.md
HTML is tokenized in a way that treats the next line as part of the html block. So the following code:
```
<div>
Item
```
Is parsed as 
```
{
"type": "root",
"children": [
{
"type": "html",
"value": "<div>\nItem"
}
],
}
```
This creates an issue when child elements of shortcodes are html, since the next line is the closing shortcode:
```
{{ myshortcode }}
<div>
{{ /myshortcode }}
```
The shortcode tokenizing logic doesn't even get a chance to run on the line `{{ /myshortcode }}`, it's consumed as HTML. The result is `<div>\n{{ /myshortcode }}` is shown in the rich-text editor for that node, and we print an extra closing tag during stringify:
```
{{ myshortcode }}
<div>
{{ /myshortcode }}
{{ /myshortcode }}
```
For now I think it makes sense to turn off the html tokenizer entirely when …
=> Skip tokenizing html when parser is configured for skipping it

.changeset/eight-stingrays-shout.md, packages/@tinacms/toolkit/src/packages/fields/plugins/BlocksFieldPlugin/index.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/ListFieldMeta.tsx
This fixes an issue where the active field indicator isn't working for fields inside objects. This is happening because of how our form builder stacks forms instead of replaces them. We wrap a group list in `ListFieldMeta` , which has a hover listener so we can show the active field on that list. But when you click into the list item, you're still inside that `ListFieldMeta` wrapper, so hovering on a text field in your block correctly triggers a hover event for `blocks.1.title`, but it also still triggers a hover event for blocks, and that happens after the title one, so the active field gets set as blocks, when it should be `blocks.1.title`. This is also why active field works on the blog post page, because there's no block to step into.
The fix, for now, is to disable the hover event in …
=> Dont trigger hover events for ListFieldMeta when wrapping objects

.changeset/two-insects-deny.md, packages/@tinacms/mdx/package.json, packages/@tinacms/scripts/src/index.ts
`@tinacms/mdx` now exports 3 things:
```
"main": "dist/index.js",
"browser": "dist/index.browser.es.js",
"module": "dist/index.es.js",
```
The CLI is using `dist/index.js`, the rich-text "raw" view is using `dist/index.browser.es.js` and Tina Cloud is using `dist/index.es.js`.
=> Provide browser-specific version of @tinacms/mdx

.changeset/sour-chicken-watch.md, packages/@tinacms/cli/src/next/commands/build-command/index.ts, packages/@tinacms/cli/src/next/commands/build-command/waitForDB.ts, packages/@tinacms/cli/src/utils/sleep.ts
Moves the checking of if a branch is valid or not to a separate check. 
We now do the following
1. Check clientId and token are correct
2. Check that Tina Cloud known about a branch
3. Check that Indexing succeeds.
If branch comes back as `status: "unknown"` (after waiting for 30 seconds)  this error will occur 
Contains logic from https://github.com/tinacms/tinacms/pull/3713 and https://github.com/tinacms/tinacms/pull/3705
=> Move branch check to its own check

.changeset/witty-turkeys-dress.md, packages/@tinacms/graphql/src/database/index.ts
Message will now say:
```
Error: Unable to find template "blockPag". Possible templates are: "showcase", "blockPage".
```
Closes ENG-865
=> Improve error message when a _template property isn't one of the templates in the collection

.changeset/plenty-dots-give.md, packages/@tinacms/app/package.json, packages/@tinacms/cli/src/next/config-manager.ts, packages/@tinacms/cli/src/next/vite/index.ts
Found this late yesterday but didn't have time to fix until now. Windows wasn't resolving the `main` field since it was html. This just exports `src/main.tsx` as the main field, which I guess it likes. 
Closes https://github.com/tinacms/tinacms/issues/3741
=> Fix main export field for @tinacms/app

.changeset/late-peaches-change.md, packages/@tinacms/graphql/src/database/index.ts
Skip ambiguous from indexing, so we log a warning instead of failing.
This led to some friction when importing Forestry sites with missing templates
closes https://linear.app/tina/issue/ENG-874/spike-can-we-handle-ambiguous-templates-a-bit-better-when-importing
=> Handle ambiguous templates from indexing

.changeset/shiny-rings-kneel.md, packages/@tinacms/cli/src/cmds/forestry-migrate/index.ts, packages/@tinacms/cli/src/cmds/init/index.ts
Fixes two issue brought up in office hours
- Migration was not probably matching when path is `""` or `"/"`
- Better message for Asking about typescript
=> Better match for Forestry migrate

.changeset/few-ears-decide.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx
If sort key and order is stored in local storage (from a previous page load) and order is desc, the sort order will be different than the value in the react state which will cause the next button to be disabled.
=> fix: Fix the initialization of sort order in collection list when previous desc sort order in local storage

.changeset/nine-rings-double.md, packages/@tinacms/graphql/src/database/index.ts
When using versioned indexes, the current index status logic will wait until after the old version is cleaned up before firing the status complete event. This may significantly delay reindexing. This update modifies the logic to fire the status complete as soon as the new version is ready and before the delete of the old index occurs.
=> feat: invoke index status callback once new version is ready

.changeset/great-starfishes-drop.md, packages/@tinacms/cli/src/next/config-manager.ts, packages/@tinacms/graphql/src/database/index.ts
IndexAllContent takes the tina schema as a parameter and writes it to the level database and then immediately fetches it from the level database at the start of indexing. If the level implementation uses an eventually consistent model, the schema may not yet be available for reading. This can lead to an error like:
```
ERROR	TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at addNamespaceToSchema (/var/task/js/content-api/src/event-queue/index.cjs:533497:23)
at validateSchema (/var/task/js/content-api/src/event-queue/index.cjs:533719:19)
at createSchema (/var/task/js/content-api/src/event-queue/index.cjs:533974:29)
at Object.getSchema (/var/task/js/content-api/src/event-queue/index.cjs:534880:31)
at processTicksAndRejections …
```
=> fix: reuse schema on full reindex

.changeset/forty-planets-reply.md, packages/@tinacms/cli/src/cmds/forestry-migrate/index.ts, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/graphql/src/database/util.ts
Handle frontmater format in forestry migration of hugo sites.
Fixes ENG-911
=> Handle frontmatter format

.changeset/two-schools-fry.md, packages/@tinacms/graphql/src/resolver/index.ts
Exporting dates as dates, instead of ISO strings
gray-matter / js-yml automatically parses the date appropriately given the format type
Mdx/mdx with yaml formats them like so:
json like so:
Our GraphQL API still returns fields as string:
=> Export date format

.changeset/tricky-colts-live.md, packages/@tinacms/cli/src/next/config-manager.ts
Discord user reported error on save: https://discord.com/channels/835168149439643678/1096106617184985240
Issue was due to config-manager not transforming the windows path separators
=> fix: normalize windows paths in config-manager

.changeset/calm-lions-smell.md, packages/tinacms/src/index.ts
Fixes #3799 
Fixes ENG-920
Add one a media store [as described in the docs](https://tina.io/docs/reference/media/external/cloudinary/) and confirm that no type errors appear.
(The tina-cloud-starter-iframe example already has this setup but commented out)
=> Fix media store types

.changeset/thick-dancers-rush.md, packages/tinacms/src/internalClient/index.test.ts, packages/tinacms/src/internalClient/index.ts
Previously, if token was not set, Authorization header was being set with value of `Bearer null` which will generate an incorrect 403 status. The correct status should be 401.
=> fix: update internal client to only set Authorization header when token is available

.changeset/honest-baboons-wonder.md, packages/@tinacms/graphql/src/database/index.ts
The character used for the upper range in data layer filtering didn't encompass cyrillic characters, so index values constructed using these characters were getting filtered out incorrectly
Fix #3608
=> fix: #3608: max value character using for queries did not encompass cyrillic characters

packages/@tinacms/cli/src/next/codegen/index.ts, packages/@tinacms/cli/src/next/commands/audit-command/index.ts, packages/@tinacms/cli/src/next/commands/build-command/index.ts, packages/@tinacms/cli/src/next/commands/dev-command/index.ts, packages/@tinacms/graphql/src/build.ts, packages/@tinacms/graphql/src/builder/index.ts, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/index.ts
Builder keeps an in memory lookup map. buildDotTinaFiles returns the lookup,  along with the schema files. codegen handles writing the config file (_lookup.json) (instead of having that handled separately in bridge / database)
=> refactor: pull out the lookup map creation so the database / bridge don't need to be concerned with it

.changeset/witty-timers-attack.md, packages/@tinacms/cli/src/next/vite/index.ts
Fixes  #3871
Fixes regression where the host from config was not getting passed to vite. 
cc @wommy @steffkes
=> fix issue with build.host in defineConfig

.changeset/serious-schools-punch.md, packages/@tinacms/graphql/src/database/index.ts
The hydrator in the database was failing on folders when calling getCollectionAndTemplateByFullPath() when templates are defined on a collection. This was being surfaced as a TinaQueryError but the folder object was present, just missing the _templates key.
=> Fix Database.get on folders within collections that have templates

.changeset/strong-cheetahs-brake.md, packages/@tinacms/graphql/src/database/datalayer.ts, packages/@tinacms/graphql/src/database/index.ts
If a collection has a match property, collection lookup for folders using getCollectionbyFullPath fails, because the filepath is '<collectionRoot>/sha.<filetype>' and not the actual full path. 
Fix is to attach the collection to the folder virtual entry and skip collection lookup by path.
=> fix: issue where collection lookup fails with folder having match property

.changeset/large-kids-sin.md, packages/@tinacms/graphql/src/database/bridge/filesystem.ts, packages/@tinacms/graphql/src/database/datalayer.ts, packages/@tinacms/graphql/src/database/index.ts
- glob was matching "-[ext]". A script named `node_modules/.bin/concat-md` was matching when a collection was configured at the root which was not a valid markdown. Updated to match literally ".[ext]".
- When configured with a root level collection, tina was scanning node_modules in dev mode and was causing a `ENAMETOOLONG` error. This change excludes node_modules folders entirely.
- the folder construction logic doesn't properly handle root level paths causing a '.' folder to be created instead of '' (root)
=> fix: folder root collection issues

.changeset/flat-files-mate.md, packages/@tinacms/graphql/src/resolver/media-utils.ts
Fixes ENG-958
this issue was caused because {publicFolder: ""} was set. The old function would check `publicFolder` and not `type of publicFolder === 'string'`. 
This needs to be tested on TinaCloud
- pull down code
- update @tinacms/graphql-1.4 deps to the snapshot release 0.0.0-20230503154010
(I was able to test and the issue was fixed)
=> Fix has tina config function

.changeset/curly-cycles-run.md, packages/@tinacms/app/index.html, packages/@tinacms/cli/src/next/commands/dev-command/html.ts
Add admin placeholder screen if assets fail to load.
closes #ENG-972
=> Add placeholder screen to admin

packages/@tinacms/toolkit/src/packages/core/media-store.default.ts
Because of the use of a Bitwise OR operator instead of a Logical OR operator, unexpected behavior occurred when changing the pageSize of the media manager. This PR fixes this operator so it works as expected.
Before:
After:
=> fix: Bitwise OR operator to Logical OR operator in media store limit

.changeset/soft-ladybugs-joke.md, packages/next-tinacms-s3/src/handlers.ts
Adds the `mediaRoot` option to the s3 media store. 
EX
```ts
// pages/api/s3/[...media].ts
import {
mediaHandlerConfig,
createMediaHandler,
} from 'next-tinacms-s3/dist/handlers'
import { isAuthorized } from '@tinacms/auth'
export const config = mediaHandlerConfig
export default createMediaHandler({
config: {
credentials: {
accessKeyId: process.env.NEXT_PUBLIC_S3_ACCESS_KEY || '',
secretAccessKey: process.env.S3_SECRET_KEY || '',
},
region: process.env.NEXT_PUBLIC_S3_REGION,
},
mediaRoot: 'tina',
bucket: process.env.NEXT_PUBLIC_S3_BUCKET || '',
authorized: async (req, _res) => {
if (process.env.NODE_ENV === 'development') {
return true
}
try {
const user = await isAuthorized(req)
return user && user.verified
} catch (e) {
console.error(e)
return false
}
},
})
```
=> Add media root to s3

.changeset/cuddly-steaks-share.md, packages/@tinacms/graphql/src/database/datalayer.ts
Fixes #3938 where `path` module was generating paths with windows sep char that needed to be escaped.
=> fix: #3938: issue with folder paths on windows

.changeset/red-peaches-move.md, packages/tinacms/src/admin/pages/utils.tsx
Fix #3952 
Special characters in the folder name from the url were url encoded, causing queries to use incorrect folder name
=> fix: #3952: use uri decoder on folder name from url

.changeset/light-ties-fail.md, packages/@tinacms/cli/src/next/commands/build-command/index.ts, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/resolve.ts
- Update build-command to prevent ugly `Invalid or incomplete introspection result` when there isn't a graphql schema in tina cloud. Display a more user friendly error instead.
- Update initLevel to not throw an error if unable to write _metadata when it doesn't currently exist. This condition should only occur when calling a get function on the database when the branch has not been indexed. By adding this, the api won't throw an unexpected exception and return a 500 error.
- Add a check to the resolver to verify that the graphql schema returned from the database is not undefined. We can catch this and throw a user friendly error (and return a 200 status code).
=> fix: invalid or incomplete introspection error

.changeset/healthy-ants-know.md, packages/@tinacms/cli/src/next/commands/baseCommands.ts, packages/@tinacms/cli/src/next/commands/build-command/index.ts
When debugging some self hosting issues I noticed that we don't index the self hosted DB when building. We need to index on build so that they DB can get the newest markdown data. 
This may have been a regressing with our larger CLI PR a month or two ago.
=> Index the content before a build when self hosting

.changeset/sharp-masks-double.md, packages/@tinacms/app/src/lib/graphql-reducer.ts, packages/@tinacms/cli/src/next/commands/dev-command/index.ts, packages/@tinacms/graphql/src/database/datalayer.ts, packages/@tinacms/graphql/src/database/index.ts
Fixes ENG-1014. dev command now works on the reproduction repo and output is now:
```
Error: Unable to determine template
at getTemplateForFile (/Users/kldavis/projects/support/ethswarm-blog-hugo/node_modules/@tinacms/graphql/dist/index.js:5995:9)
at /Users/kldavis/projects/support/ethswarm-blog-hugo/node_modules/@tinacms/graphql/dist/index.js:5848:24 {
name: 'TinaFetchError',
collection: undefined,
file: 'content/foundation/_index.md',
originalError: Error: Unable to determine template
at getTemplateForFile (/Users/kldavis/projects/support/ethswarm-blog-hugo/node_modules/@tinacms/graphql/dist/index.js:5995:9)
at /Users/kldavis/projects/support/ethswarm-blog-hugo/node_modules/@tinacms/graphql/dist/index.js:5848:24
}
Error: Unable to determine template
at getTemplateForFile …
```
=> fix: ENG-1014: prevent unhandled promise rejection when unable to determine collection for file

.changeset/real-lies-study.md, packages/@tinacms/toolkit/src/components/media/media-manager.tsx
Fix regression where we check for Tina media status (and disable media manager) for external media setups.
We should only do this when tina media is configured
=> fix: Skip media status check on external media

.changeset/little-cycles-matter.md, packages/@tinacms/vercel-previews/package.json, packages/@tinacms/vercel-previews/src/index.ts, pnpm-lock.yaml
The udpated functionality has some logic to avoid encoding URLs and dates
=> Use `vercelStageCombine` for Vercel preview helper

.changeset/odd-fireants-share.md, .changeset/tender-pots-sit.md, packages/@tinacms/cli/src/next/commands/dev-command/index.ts, packages/@tinacms/graphql/src/database/util.ts
- Fix issue where the any changes to content in local dev were not being reflected in the local search
- Fix bug in the scanContentByPaths where callback was being invoked when there were no non-collection paths (found while fixing the previous issue)
=> fix: ENG-1035: local search index updates on changes

packages/@tinacms/toolkit/src/packages/styles/Message.tsx, packages/@tinacms/toolkit/src/packages/styles/index.ts, packages/tinacms/src/admin/pages/CollectionListPage.tsx
Add placeholder UI for when search isn't configured, linking to docs.
closes ENG-1029
=> Search placeholder

.changeset/slow-rockets-shake.md, packages/@tinacms/schema-tools/src/validate/tinaCloudSchemaConfig.ts
When specifying the `search.tina.stopwordLanguages` in the tina config, zod throws `Unrecognized key(s) in object: 'stopwordLanguages'`. This is due to the strict constraint on the tina object and the lack of a stopwordLanguages key.
=> fix: search configuration for tina was throwing zod error for stopwordLanguages key

.changeset/nine-eagles-fail.md, packages/@tinacms/cli/src/next/commands/dev-command/index.ts, packages/@tinacms/cli/src/next/config-manager.ts, packages/@tinacms/cli/src/next/vite/index.ts, packages/@tinacms/cli/src/next/vite/tailwind.ts, packages/@tinacms/schema-tools/src/schema/TinaSchema.ts
Change the way the Tina config file is built, so dependencies with Tailwind classes are picked up automatically
- The `tina/config` file and all of it's imports, including external deps are bundled into the prebuild (at `tina/__generated__/config.prebuild.jsx`)
- Tailwind is given this path as one of it's `content` values so that it scans this directory
This PR also does some clean up
- No longer relying on Vite to handle reloads on config. There was already some buggy behavior here since the SPA didn't wait for the new config to re-index the database, now it does. Reloads should still happen when working on modules like `tinacms` or `@tinacms/toolkit`
- Removes duplicated `indexContent` calls
- Improves logging for errors from the dev server.
- Suppresses some warnings from the CLI that …
=> Prebuild Tina config file

.changeset/chatty-ravens-collect.md, .changeset/cool-teachers-run.md, .changeset/purple-students-deny.md, packages/@tinacms/cli/src/next/commands/dev-command/index.ts, packages/@tinacms/cli/src/next/commands/dev-command/server/searchIndex.ts, packages/@tinacms/schema-tools/src/types/index.ts, packages/@tinacms/schema-tools/src/validate/tinaCloudSchemaConfig.ts, packages/@tinacms/search/package.json, packages/@tinacms/search/src/client/index.ts, packages/@tinacms/search/src/index.ts, packages/tinacms/src/admin/pages/CollectionListPage.tsx, pnpm-lock.yaml
- fix bug where collections that had names with underscores were not searchable
- allow the tokenizer regexp to be customizable (to accommodate other characters)
- refactor search indexing clients a bit and add a debug output cli flag for dev mode
- fix UI issue where search state was not reset after changing selected collection
- switch to the official `search-index` library
=> fix: fixes for search

.changeset/dull-knives-wonder.md, packages/@tinacms/toolkit/src/tina-state.tsx
Fixes 2 issues:
The cleanup process during unmount didn't clear the active form.
Also, when choosing an active form we were choosing the last form item instead of the first.
=> Fix issue with visual editing choosing right form

.changeset/clean-roses-think.md, .changeset/cyan-moons-peel.md, .changeset/empty-birds-press.md, packages/@tinacms/app/src/lib/util.ts, packages/@tinacms/cli/src/next/vite/index.ts, packages/tinacms/src/react.tsx
- Noticed that when the schema is changed the Vite app was showing a schema mismatch error
- For nullable fields (eg `tinaField(post.author, 'name')`) the `tinaField` function was showing a Typescript error
- Using `tinaField` on a reference was resulting in the referenced form being selected instead of the parent form's reference select field.
=> Various bug fixes

.changeset/forty-readers-begin.md, packages/tinacms/package.json, packages/tinacms/src/rich-text/prism.tsx, pnpm-lock.yaml
Fixes Next build error:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: [missing argument].[missing argument]
```
I got mixed results here, have no idea why but I was able to break this on previous tina versions as well as the latest beta. Ultimately upgrading to a more modern build of the prism library seems to have fixed things. I suspect our `cjs` builds aren't playing well with default exports in some cases but can't pin it down with this
Bonus is that we can now provide a `theme` prop:
```jsx
code_block: (props) => <Prism {...props} theme="palenight" />,
```
=> Upgrade prism

.changeset/wet-spies-sip.md, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchBanner.tsx
This brings over the styles used for the branch button component when a protected branch is selected so the branch banner has the same behaviour. The button should appear blue with a lock icon when you're on a protected branch, otherwise it's white with a git branch icon.
=> Branch Banner Button Protected Styles

packages/@tinacms/search/src/client/index.ts, packages/@tinacms/search/src/index-client.ts, packages/@tinacms/search/src/index.ts, packages/@tinacms/search/src/indexer/utils.ts, packages/tinacms/src/auth/TinaCloudProvider.tsx, packages/tinacms/src/internalClient/index.ts
Fixes issue where copying the full text of a title into a search query would result in no results because of the stopwords used in the query not existing in the search index
=> fix: use stopwords to filter the search query

.changeset/orange-snails-notice.md, .changeset/ten-countries-sort.md, packages/@tinacms/cli/src/utils/spinner.ts, packages/@tinacms/graphql/src/database/index.ts
Fixes:
- errors were getting swallowed inside the spinner
- when we aren't able to load content due to the ambiguous template error it was still indexing
=> fix: indexing error handling

.changeset/cyan-trees-happen.md, packages/@tinacms/graphql/src/resolver/index.ts, packages/@tinacms/mdx/src/next/stringify/acorn.ts, packages/@tinacms/mdx/src/next/tests/util.ts, packages/@tinacms/mdx/src/stringify/acorn.ts
- import isValid from 'date-fns/isValid/index.js' instead of date-fns/isValid
- in the mdx package use the esm version of prettier
=> Fix issues with ESM

.changeset/metal-rats-tap.md, packages/@tinacms/mdx/src/parse/remarkToPlate.ts
Partially closes https://github.com/tinacms/tinacms/issues/4011.
The plate vulnerability is addressed [here](https://github.com/tinacms/tinacms/pull/4029). Though I don't think it affects us directly since we're not using their built-in link logic
=> Ensure urls are sanitized in a tags for rich-text

.changeset/fuzzy-mangos-perform.md, packages/@tinacms/toolkit/src/components/media/media-manager.tsx, packages/@tinacms/toolkit/src/packages/core/media.ts
Use clean page sizes, so it's more obvious media is paginated
closes ENG-1083
=> Clean media grid

.changeset/soft-glasses-watch.md, examples/basic-iframe/content/page/home.mdx, examples/basic-iframe/tina/config.js, packages/@tinacms/schema-tools/src/types/index.ts, packages/tinacms/src/toolkit/form-builder/form-builder.tsx
Fixes ENG-1081
Add a `beforeSubmit` hook function on a collection.ui. This give users the ability to run a function before the form is submitted. 
If the function returns values those values will be used will be submitted instead of the form values.
If the function returns a falsy value the original form values will be submitted.
```js
// tina/config.{ts.js}
export default defineConfig({
schema: {
collections: [
{
ui: {
// Example of beforeSubmit
beforeSubmit: async ({ values }) => {
return {
...values,
lastUpdated: new Date().toISOString(),
};
},
//...
},
//...
},
//...
],
},
//...
});
```
=> Add Before Submit function

.changeset/six-moles-fail.md
Since toolkit packages does not exist it is causing our publish to fail.
=> fix changeset

.changeset/angry-chairs-kneel.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx
Previously, collections with templates instead of fields weren't getting the option to filter/search/sort
https://www.loom.com/share/9fa1adec08504274855a9216f0574f69?sid=524d5849-29ae-4e5b-9467-4fad42d17afe
fixes ENG-1103
=> Filterable templates

.changeset/five-shirts-remember.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx
For collections with only no text fields, we previously omitted the search input, and the filters
Now we only omit the filters:
=> Show search even with no filterable fields

.changeset/blue-zoos-drive.md, packages/@tinacms/schema-tools/src/types/index.ts, packages/tinacms/src/admin/pages/CollectionListPage.tsx
Update the router function to work asynchronously. This means that a user can now fetch data or perform other async operations in the router function.
Example:
```ts
router: async ({ document }) => {
const res = await client.queries.post({
relativePath: document._sys.relativePath,
})
return `/posts/${res.data.slug}`
},
```
=> feat: router async

packages/@tinacms/cli/src/next/codegen/index.ts
We were treating this as a property instead of a function
=> Fix `hasSelfHostedConfig` checks

.changeset/silent-balloons-beg.md, packages/@tinacms/schema-tools/src/schema/TinaSchema.ts
Fix regression from https://github.com/tinacms/tinacms/commit/bcc0b25b32c6cb6d9f0d72c9e755dffc8cec91a3
Previously, isMatch always returned true, so we would fetch the wrong collections and fail in unexpected ways
=> Fix matches

.changeset/silent-shoes-smash.md, packages/@tinacms/cli/src/next/commands/baseCommands.ts, packages/@tinacms/graphql/src/git/index.ts, packages/@tinacms/graphql/src/index.ts
Detect whether the stored last commit sha used for partial reindexing exists before attempting to find changed files. Handles case where the stored sha gets removed or lost somehow.
=> fix: verify sha exists before partial reindexing

.changeset/odd-hounds-draw.md, packages/@tinacms/cli/src/next/commands/dev-command/index.ts
Update the "Content in a separate repo" workflow to export tina-lock in the external local repo.
(I don't think this has been working since we switched from pushing up a `__generated__` directory to a pushing a `tina-lock.json`)
=> Separate repo lockfile

packages/@tinacms/cli/src/utils/script-helpers.test.ts, packages/@tinacms/cli/src/utils/script-helpers.ts
When we generate new scripts in the users package.json for next.js sites we don't need to wrap the start script in tinacms build since it is assumed that the build script has all ready been run.
=> Remove start script

.changeset/late-vans-wash.md, .prettierignore, packages/@tinacms/graphql/src/resolver/index.ts, packages/@tinacms/graphql/src/spec/forestry-sample/mutations/updateDocument/_response.md, packages/@tinacms/graphql/src/spec/movies/mutations/updateDocument/_response.md, packages/@tinacms/graphql/src/spec/movies/mutations/updateDocument/_variables.json
Update mutation logic so that existing markdown values aren't overwritten by the Tina form, only if the schema has not defined that field. 
Eg:
```
title: Hello
tags:
- a
- b
```
And a schema:
```
{
//...
fields: [
{type: 'string', name: 'title'},
]
}
```
`tags` won't be changed, but if there is a field defined for `tags`, whatever value is sent in from the Tina form will be used, even `null`:
```
title: Hello
tags: null
```
=> Only preserve legacy values if no field is defined for them

examples/tina-self-hosted-demo/pages/api/tina/auth/[...nextauth].ts, examples/tina-self-hosted-demo/pages/api/tina/gql.ts, examples/tina-self-hosted-demo/tina/config.tsx, packages/@tinacms/schema-tools/src/types/index.ts, packages/tinacms-authjs/src/tinacms.ts, packages/tinacms-clerk/package.json, packages/tinacms/src/auth/TinaCloudProvider.tsx, packages/tinacms/src/auth/defaultSessionProvider.tsx, packages/tinacms/src/internalClient/authProvider.ts
support custom next-auth path (`/api/tina/auth/*`) to support consolidated api without rewrite
=> feat: custom next-auth api endpoint path

packages/@tinacms/datalayer/src/backend/index.ts, packages/tinacms-authjs/src/index.ts
Add a warning on backend api initialization when using a custom provider with the /api/tina/* catch-all
Demo: https://www.loom.com/share/af508f26eb6543e5a5012923e8724c6d?sid=cf83351e-99e6-4673-800f-de93443ce9e2
Note that this doesn't know whether a separate next-auth api handler has been configured, so the warning will show whenever the tina backend is initialized.
=> feat: warn nextauth custom provider

.changeset/pink-mirrors-wave.md, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/error.ts, packages/@tinacms/graphql/src/resolve.ts
When a document is not found I don't think that should be logged to the GraphQL console. It's not necessarily something the user cares about.
cc @logan-anderson
=> Don't log 'not found' errors to the console from the GraphQL server

.changeset/long-cows-happen.md, packages/@tinacms/search/src/indexer/index.ts, packages/@tinacms/search/src/indexer/utils.ts
There was a small bug in the search indexing logic which only surfaced under the circumstances in #4201. The fields being the same name was a bit of a red herring, though. The problem was that it was using the collection field definitions on nested objects due to a logic error.
=> fix: #4201: correctly handle search indexing of list objects

.changeset/empty-countries-drive.md, .changeset/sharp-dragons-ring.md, packages/@tinacms/cli/src/next/commands/build-command/index.ts, packages/@tinacms/cli/src/next/commands/dev-command/index.ts, packages/@tinacms/cli/src/utils/spinner.ts, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/database/util.ts
Address issues with parse errors no getting logged at index time
demo: https://www.loom.com/share/e7de458ca8c240baa515249c0028a9d4?sid=56a8d346-1fe3-44d6-be86-b6a40f11dce8
Also confirmed that any parse errors while editing in dev mode are handled the same - error is logged and when the file is corrected the dev server restarts itself
=> fix: exit and log when parse errors occur during indexing

.changeset/ninety-rings-peel.md, packages/@tinacms/app/src/App.tsx, packages/@tinacms/app/src/Playground.tsx, packages/@tinacms/app/src/vite-env.d.ts, packages/@tinacms/cli/src/next/vite/index.ts, packages/tinacms/src/admin/index.tsx
Previously you needed to provide either a `TINA_` prefixed env var or a hardcoded one for the Tina SPA to recognize it, now the value is always available regardless of env variable name.
Also removes token being passed to graphiql ui
=> Add support for build.basePath to be an environment variable

.changeset/eighty-socks-search.md, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/unifiedClient/index.ts
When we transform the form values we append the `_template` value to the payload, but since the editorial workflow throws the form values into local storage, when it pulls them out the `_template` value doesn't get passed in. This PR just appends the `_template` value to the "create" form's initial values so they're always there
cc @logan-anderson
=> Fix template collection branch create

.changeset/eighty-weeks-rule.md, packages/tinacms/src/toolkit/core/media-store.default.ts, packages/tinacms/src/toolkit/tina-cms.ts
Handle 412 response from assets api by displaying the error to the user. Will now indicate when the issue is due to an existing file.
Demo: https://www.loom.com/share/0b1af46f5c9546de9ee88dc63ffd9f57?sid=db8ba5f9-b80a-4982-806e-1b7ca89df593
=> fix: media manager to pass back error when generating upload_url fails due to existing file

.changeset/blue-cherries-hug.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx, packages/tinacms/src/toolkit/styles/button.tsx
Fix #4240 by removing type='submit' from the search button which was causing the body style from overriding the background color. Also fix the button component to not add `undefined` to the class when no className is specified (although it didn't seem to cause any issues)
=> fix: #4240: fix issue where background color of search button was being overridden

.changeset/seven-grapes-retire.md, packages/@tinacms/graphql/src/database/util.ts
Add's error link for ambiguous templates.
Docs PR: https://github.com/tinacms/tina.io/pull/1672
=> add error link

packages/tinacms-authjs/src/index.ts, packages/tinacms-authjs/src/tinacms.ts
Credentials provider name wasn't getting set so the following warning was being shown:
```
WARNING: Catch-all api route ['/api/tina/*'] with specified Auth.js provider ['Credentials'] not supported. See https://tina.io/docs/self-hosted/overview/#customprovider for more information.
```
=> fix: bogus warning

packages/@tinacms/cli/src/next/codegen/index.ts
fix this error:
```
Error occurred prerendering page "/posts". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error serializing `.errors` returned from `getStaticProps` in "/posts".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
at isSerializable (/Users/kldavis/projects/tina-self-hosted-demo/node_modules/next/dist/lib/is-serializable-props.js:52:19)
at /Users/kldavis/projects/tina-self-hosted-demo/node_modules/next/dist/lib/is-serializable-props.js:59:66
at Array.every (<anonymous>)
at isSerializable (/Users/kldavis/projects/tina-self-hosted-demo/node_modules/next/dist/lib/is-serializable-props.js:56:39)
at isSerializableProps (/Users/kldavis/projects/tina-self-hosted-demo/node_modules/next/dist/lib/is-serializable-props.js:79:1 …
```
=> fix: errors can not be undefined

packages/@tinacms/cli/src/cmds/init/apply.ts, packages/@tinacms/cli/src/cmds/init/templates/config.ts
If a user ran `tinacms init backend` without having a tina config already it would be generated incorrectly. (it would get two user collections and extra imports).
This PR updates the code so that the code transformations only get applied if the config was not just generated.
=> Fix generated config file

packages/@tinacms/cli/src/cmds/init/prompts/databaseAdapter.ts
namespace is only specified when calling createDatabase and not set on the adapter
=> fix: remove namespace from db adapter

.changeset/moody-rockets-admire.md, packages/@tinacms/cli/src/cmds/init/prompts/askTinaCloudSetup.ts
The key for the read only token did did not match the env var used in the config. This causes an issue when a user runs `tinacms init backend` and uses Tina Cloud
=> Fix read only token name

.changeset/perfect-feet-help.md, packages/tinacms/src/admin/pages/LogoutPage.tsx, packages/tinacms/src/auth/TinaCloudProvider.tsx, packages/tinacms/src/toolkit/components/account/update-password.tsx, packages/tinacms/src/toolkit/react-sidebar/components/nav.tsx
Fixes https://github.com/tinacms/tinacms/issues/4356 by adding a timeout that waits for browser events to finish before refreshing the page.
=> Fix onLogout

.changeset/loud-panthers-check.md, packages/@tinacms/schema-tools/src/types/index.ts, packages/tinacms/src/auth/TinaCloudProvider.tsx, packages/tinacms/src/index.ts, packages/tinacms/src/internalClient/authProvider.ts
Based on #4349 with some fixes
PoC:
Add the following to `examples/tina-self-hosted-demo`:
```
import * as React from 'react'
import { LoginStrategy, LoginScreenProps } from 'tinacms'
class MyAuthProvider extends UsernamePasswordAuthJSProvider {
getLoginScreen(): React.FC<LoginScreenProps> {
return (props: LoginScreenProps) =>
<div>Custom Login Screen: <button onClick={
() => props.handleAuthenticate({ username: 'tinauser', password: 'tinarocks' })}>Login</button> </div>
}
getLoginStrategy(): LoginStrategy {
return 'LoginScreen'
}
}
```
and replace the UsernamePasswordAuthJSProvider with MyAuthProvider.
To test, setup .env in the self hosted example and run `pnpm run dev:prod`. Clear cookies and login.
Demo: https://www.loom.com/share/f56a2d1fc9ca4bbb8a01e38a7049f877
=> Add get login screen to auth provider

.github/stale.yml
Closes #4282
Not going as far as to remove Stalebot, but increase the timer to 6ish months for something to be stale, and 14 days for it to be autoclosed afterwards
=> Increase stalebot timer

.changeset/thin-carpets-marry.md, packages/@tinacms/cli/src/cmds/init/prompts/databaseAdapter.ts, packages/@tinacms/cli/src/cmds/init/prompts/index.ts
Noticed an issue where when using the mongo adapter on windows, it is bundling the non-windows version of the mongodb driver which doesn't work (instead of building it for windows). This updates the cli init to add mongodb as a separate dependency so that the correct version of the driver is used.
=> fix: add mongodb library as a dependency when using the mongo level adapter

.changeset/twenty-dodos-protect.md, packages/tinacms/src/toolkit/forms/form.test.ts, packages/tinacms/src/toolkit/forms/form.ts
This PR fixes an issue where it was impossible to navigate to nested fields (e.g. object fields or list items) when editing the values for a rich-text template when that template was configured to be `inline: true`
https://www.loom.com/share/085f1aa40af742a5a7d8b8168760c52b
- This PR resolves #4074 and adds tests to prevent regressions
- I think the bug from the original issue was resolved for non-inline rich-text templates by this PR: #4044. However, the bug remained for inline rich-text templates
- Specifically the issue broke the editing process for rich-text templates that:
- were designated to be `inline: true`
- had a nested list field OR a nested object field
=> Fix inline rich-text templates with nested object or list fields

.changeset/silly-ducks-shake.md, packages/@tinacms/cli/src/next/commands/build-command/index.ts
For tina cloud projects configured as content repos (with an upstream project holding the schema), adds a step to the build process which synchronizes the upstream schema to the content repo project and reindexes (if necessary).
=> feat: update build command to detect tina cloud projects configured with upstream and conditionally synchronize schema

.changeset/eighty-doors-visit.md, packages/@tinacms/cli/src/next/codegen/codegen/plugin.ts, packages/tinacms/src/unifiedClient/index.ts
You can now pass through `fetchOptions` to the generated client request. This is especially useful for working with the [Next.js app router](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-server-with-fetch).
```ts
const tinaProps = await client.queries.contentQuery(
{
relativePath: `${params.filename}.md`,
},
{
fetchOptions: {
headers: { 'x-hello': 'world' },
cache: 'force-cache'
},
}
)
```
=> Add fetch options to generated client

.github/workflows/main.yml, .github/workflows/publish.yml
Using a GitHub App to generate tokens on demand - this will allow the bot to create/rebase release PRs and emit the push/pull_request events as required.
Tokens will have:
- Repo - Contents: R+W
- Repo - Pull requests: R+W
- Org - Maintainers: R
=> Publish workflow - use github app generated token to allow bot to fire push/pull_request events

.github/workflows/publish.yml
This should fix app token generation, following the same steps as for `SSWConsulting/SSW.Rules.Content` - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/.github/workflows/main-trigger-rules-deploy.yml
=> publish workflow - fix app token generation

.changeset/early-drinks-smoke.md, packages/tinacms/src/tina-cms.tsx
same fix as #4601
Nick found a good replacement for this broken link https://tina.io/docs/tina-cloud/overview
=> cms - fix broken link in error

.changeset/nasty-cherries-pump.md, packages/tinacms/src/admin/components/Page.tsx, packages/tinacms/src/admin/components/Sidebar.tsx, packages/tinacms/src/admin/index.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx, packages/tinacms/src/toolkit/fields/components/select.tsx, packages/tinacms/src/toolkit/react-sidebar/components/sidebar.tsx, packages/tinacms/src/toolkit/styles/message.tsx
Fixes #4613. 
Also fixed some pages that had the h-screen issue and wasn't rendering properly on mobile.
**Figure: Collections header on xs screens (320px - 559px)**
**Figure: Collections header on sm screens (560px - 719px)**
**Figure: Collections header on md screens (720px - 1029px)**
**Figure: Collections header on lg screens (1030px - 1279px)**
**Figure: Collections header on xl screens (1280px + )**
=> 🐛 TinaCMS - Collections - Fix header styling for smaller screens

.changeset/big-seahorses-marry.md, packages/tinacms/src/toolkit/form-builder/form-builder.tsx
- removed 'no changes' text as it was misleading if you were working on a branch with some saved commits
- move save/unsaved indicator to the right
- change 'unsaved' indicator color to red to make it more prominent
=> 💄 UI/UX - modify form saved indicator

.changeset/tidy-hornets-cross.md, examples/basic-iframe/tina/config.js, packages/@tinacms/schema-tools/src/types/index.ts, packages/tinacms/src/toolkit/components/media/media-item.tsx, packages/tinacms/src/toolkit/components/media/media-manager.tsx, packages/tinacms/src/toolkit/components/media/utils.ts, packages/tinacms/src/toolkit/core/media-store.default.ts, packages/tinacms/src/toolkit/core/media.ts
- Add media config option to allow overriding the default accepted media types
- Set a default size limit of 100MB on the tina media store
- Update UI to show movie icon for video files
TODO
=> feat: allow customization of media type in media manager

.changeset/nasty-gifts-cheat.md, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx, packages/tinacms/src/admin/pages/ScreenPage.tsx, packages/tinacms/src/toolkit/plugin-branch-switcher/branch-banner.tsx, packages/tinacms/src/toolkit/react-sidebar/components/sidebar.tsx
Fixes #4627.
There were a few places where @react-hook/window-size was being used to alter styling that could have been done using css. These have been reduced down to one line of css styling. 
Note: It has been kept in places when the conditional rendering is complex (e.g. sidebar.ts and Sidebar.ts)
I have also converted the remainding navBreakpoints from 1000px to 1279px to be inline with our xl screen breakpoint.
=> ♻️ TinaCMS - Remove unnecessary use of @react-hook/window-size

.changeset/rude-adults-pay.md
Removes `'@tinacms/sharedctx': patch` as sharedctx is no longer available
=> update changeset packages

.changeset/tame-mirrors-begin.md, packages/next-tinacms-cloudinary/src/handlers.ts
Fixes #4657. 
Cloudinary was only accepting image uploads and the error message given to the user was very bad.
**Figure: MKV video uploaded to Cloudinary using the Media Manager**
**Figure: Fixed error message**
=> 🐛 Media Manager - Fix Cloudinary not accepting video uploads

.changeset/giant-snakes-work.md, packages/@tinacms/app/src/fields/rich-text/monaco/index.tsx
Fixes #4678.
I have opted to keep the behaviour of the raw markdown button inline (sticky) with the rich-text editor toolbar for consistency.
**Figure: Markdown button styling fixed and refactored**
**Figure: Rich-text editor toolbar being sticky**
=> 🐛 Media Manager - Fix raw markdown button styling

packages/next-tinacms-s3/README.md
I was following the [custom media store for S3 docs](https://tina.io/docs/reference/media/external/s3/) and noticed four things:
Otherwise the production deployment on tina.cloud will continue to prefix all media files with `https://asset.tina.io/` + `clientId`. See [discussion in discord](https://discord.com/channels/835168149439643678/1256612728257384511).
As the `tina-lock.json` file in general seems to be pretty crucial but the first time I actually came across it was while running [into the issue described in discord](https://discord.com/channels/835168149439643678/1256612728257384511) I think there might even be better places to mention it. For the time being I have added it to the relevant part of the documentation via a seperate PR here: …
=> Add missing `s3:ListBucket` policy

.changeset/rare-phones-exercise.md, packages/@tinacms/graphql/src/database/index.ts
Discord user `jcole` reported `.gitkeep.md` files were being included in query results which was then breaking because they did not conform to the collection schema.
Filter .gitkeep files during indexing
=> fix: filter gitkeep

.changeset/grumpy-horses-talk.md, packages/@tinacms/cli/src/next/commands/build-command/server.ts, packages/@tinacms/cli/src/next/commands/dev-command/server/index.ts, packages/@tinacms/scripts/src/index.ts
Hides warnings about `MODULE_LEVEL_DIRECTIVE` that are being spammed in the console.
=> Add rollup option to ignore "MODULE_LEVEL_DIRECTIVE"

.changeset/hungry-eggs-leave.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx
When hitting the search button, the page redirects instead of loading the search results
Prevent default to avoid submitting the form
=> fix: prevent form submission when searching

.changeset/popular-bulldogs-heal.md, packages/@tinacms/cli/src/next/codegen/index.ts
Discord user reported search indexer token is being written to tina-lock.json
Filter search config from output
=> fix: @tinacms/cli: prevent search config from getting written to lock file

.changeset/brave-eagles-live.md, examples/kitchen-sink/package.json, package.json, pnpm-lock.yaml
~Temporary override peer dependency packages ws and micromatch~
~Reason: To fix vulnerabilities, as the parent packages dependency used in tinacms haven't get the latest upgrade of both packages~
Update some packages
=> Fix peer dependency vulnerable packages

.changeset/olive-roses-burn.md, packages/@tinacms/cli/src/cmds/init/templates/config.ts
Fix [issue](https://discord.com/channels/835168149439643678/1283410305753288756) reported on discord
When executing self-hosted init, the auth user collection is inserted incorrectly.
=> fix: cli init generating broken collections definition

.changeset/plenty-ants-argue.md, packages/@tinacms/cli/src/next/codegen/index.ts
Fix #4779 caused by not escaping backslashes on windows
=> fix: normalize cache dir to avoid unescaped characters breaking esbuild

.changeset/tender-hounds-smell.md, packages/tinacms/src/internalClient/index.ts, packages/tinacms/src/toolkit/components/media/modal.tsx, packages/tinacms/src/toolkit/core/media-store.default.ts
Leverage the new request-status endpoint in TinaCloud media manager for upload and delete requests so that async errors are surfaced to the user.
Also fixes media manager UI to close the delete confirmation modal regardless of whether an error occurs (instead of it staying open when an error occurs)
=> feat: media-manager: add async error handle for media upload

.editorconfig, .github/workflows/main-generate-release-notes.yml, .github/workflows/publish.yml
`publish.yml` - simplifies the "latest" strategy + creates GitHub releases
`main-generate-release-notes.yml` | when new tinacms@* tags are created - grab the release notes and publish them on Tina.io
=> release - publish GitHub releases + release notes to Tina.io

.github/workflows/build-starter-templates.yml
PNPM isn't installed within the GitHub action and therefore when it's used the action will fail.
=> Add PNPM to the "build all templates" GitHub action

.changeset/poor-pears-joke.md, packages/tinacms/src/unifiedClient/index.ts
The following error message is seen when attempting to build [tina-cloud-starter](https://github.com/tinacms/tina-cloud-starter/) with the `tinacms` 2.2.8:
```
Collecting page data  ...ReferenceError: window is not defined
at i.init (/home/ncn/Source/Tina/tina-cloud-starter/.next/server/chunks/631.js:3:93620)
at i.request (/home/ncn/Source/Tina/tina-cloud-starter/.next/server/chunks/631.js:3:93848)
at /home/ncn/Source/Tina/tina-cloud-starter/.next/server/chunks/752.js:384:143
at Object.postConnection (/home/ncn/Source/Tina/tina-cloud-starter/.next/server/chunks/752.js:384:703)
at Object.d [as generateStaticParams] (/home/ncn/Source/Tina/tina-cloud-starter/.next/server/app/posts/[...filename]/page.js:1:94459)
at buildParams (/home/ncn/Source/Tina/tina-cloud-starter/node_modules/.pnpm/next@1 …
```
=> 🐛 Bug - Protect 'window' reference

.github/workflows/build-starter-templates.yml
Add project build tokens to build all templates action. This allows the projects to build against TinaCloud instead of locally fixing a series of NextJS issues we ran into due to the Tina `--local` build flag not working for SSR
=> Add project build tokens to build all templates action

.changeset/violet-kings-occur.md, packages/tinacms/package.json, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/mermaid-element.tsx, pnpm-lock.yaml
- Fixes issue with `mermaid` version 10+ moving to pure esm output. (can't use require to import)
```js
Module not found: ESM packages (mermaid) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
``` 
[Read more about pure esm](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)
=> lock mermaid to 9.3.0 to allow cjs

.changeset/great-ties-rescue.md, packages/@tinacms/schema-tools/src/types/index.ts
Found and reported via https://discord.com/channels/835168149439643678/1299509772395085845
- renames `toolbarItemName` to `ToolbarOverrideType` to make it consistent
- Adds `table` to the ToolbarOverrideType
=> Add `table` to the Schema Tools ToolbarOverrideType list

.changeset/small-ways-switch.md, packages/@tinacms/cli/src/next/commands/build-command/index.ts
If there is a change to the tina schema that doesn't change the graphql schema (changes to a collection path for example) and that change is not pushed to the remote GitHub repository, there can be inconsistent behavior between local dev and production.
Compare the local tina schema to the remote tina schema and build time. If differences are detected, alert the user.
Fix #5221
=> feat: cli verification of tina schema mismatch between remote and local

.changeset/sharp-beans-change.md, packages/tinacms/src/toolkit/fields/plugins/group-list-field-plugin.tsx
Fixes #5261
**Figure: Delete Icon correctly showing on Safari**
=> Fix delete Block Icon not showing up in Safari

.changeset/brave-apes-breathe.md, packages/@tinacms/cli/src/next/commands/build-command/index.ts
- Output @tinacms/graphql local and remote graphql version 
- Output timestamp of last indexing event
Example output when graphql schema doesn't match:
```
Starting Tina build
Checking clientId and token. ✅
Checking branch is on Tina Cloud. ✅
Checking indexing process in Tina Cloud... ✅
Checking local GraphQL Schema matches server. ❌
Error: The local GraphQL schema doesn't match the remote GraphQL schema. Please push up your changes to GitHub to update your remote GraphQL schema.
Additional info:
Branch: main, Client ID: 7700bd76-ee7b-4676-aab6-361dea3d30d4
Local GraphQL version: 1.5 / Remote GraphQL version: 1.5
Last index: Sat, 26 Oct 2024 01:15:39 GMT
```
=> feat: more detailed error logging

.changeset/little-penguins-bow.md, packages/tinacms/src/toolkit/fields/components/number-input.tsx, packages/tinacms/src/toolkit/fields/plugins/date-field-plugin.tsx
=> fix: set null for empty values in NumberInput and DateField

.changeset/friendly-pants-drop.md, packages/@tinacms/cli/src/next/codegen/index.ts, packages/@tinacms/cli/src/next/commands/build-command/index.ts, packages/@tinacms/cli/src/next/config-manager.ts, packages/@tinacms/cli/src/next/vite/index.ts
This PR adds the patch version into the graphql errors when building a project.
This PR relies on the changes made in https://github.com/tinacms/tinacloud/pull/2459
=> Log graphql patch versions on error

.github/workflows/build-starter-templates.yml
- Fixes https://github.com/tinacms/tinacms/issues/5376 (Hugo Failing Build) 
- Related Issue: https://github.com/peaceiris/actions-hugo/issues/652
Changes the **hugo-version**: from `latest` to `0.139.4`
✅ Tested and is working again ([See the Action](https://github.com/tinacms/tinacms/actions/runs/12363482399/job/34504881805))
=> ♻️ Remove `latest` - set to specific version

packages/@tinacms/mdx/package.json
This PR fixes an issue where the mdx tests would hang after completion due to `vitest` by default watching.
=> Stop mdx tests from hanging

.changeset/afraid-yaks-live.md, packages/@tinacms/graphql/src/database/index.ts
Fix #4018
Database delete was not normalizing the key when deleting indices causing deleted items to not be removed.
"Normalization" replaces windows file separator characters with unix separator characters. By failing to normalize when constructing the key during delete, the indexes for the file that was removed were not updated and the subsequent query against the indexes included the file that was removed.
=> fix: error when deleting file on windows

.changeset/stupid-radios-jump.md, experimental-examples/tina-cloud-starter/components/layout/footer/rawRenderer.tsx, packages/tinacms/src/toolkit/react-datetime/DateTime.jsx, pnpm-lock.yaml
- fix import "react-use" from name import to default import, as per https://stackoverflow.com/questions/78361013/getting-this-error-syntaxerror-named-export-useclickaway-not-found-in-nextj
- fix deprecated API in example project
=> fix import for react-use

.changeset/curvy-planes-invite.md, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/transforms/is-url.test.ts, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/transforms/is-url.ts
jadenadams124124 on discord reports that a bare hash like `#foobar` can not be inserted as a link for links to anchor tags in the same document
Add support for inserting bare hash
=> feat: allow bare hash string to be inserted as url

.changeset/green-trees-join.md, packages/create-tina-app/src/util/preRunChecks.ts
as per my conversation with @JackDevAU, we will only display a message if you're outside of the supported versions as opposed to specific versions.
relates to https://github.com/tinacms/tinacloud/issues/2422
=> refactor: support a range of node versions instead of specific versions.

.changeset/famous-planes-yell.md, packages/@tinacms/cli/src/next/commands/dev-command/index.ts
The change is intended to prevent builds from failing due to the initial indexing process failing to read a complete lookup file.
It does this by ensuring that the watch process is started *after* the initial indexing process has completed. This prevents:
- A changed file (e.g. frags.gql and queries.gql)...
- Triggering a re-creation of the lookup file...
- While the indexing process is running...
- When it may read an incomplete lookup file and fail.
=> 🐛 Bug - Reordered indexing to be before watching

.changeset/plenty-dingos-tickle.md, packages/tinacms/package.json, packages/tinacms/src/cache/node-cache.ts, packages/tinacms/src/unifiedClient/index.ts, pnpm-lock.yaml
This change fixes a bug where partial files were being read from the request cache during builds, resulting in failed builds.
It fixes the bug by doing the following:
- Adding a direct dependency on [async-lock](https://www.npmjs.com/package/async-lock) package. Note that there was already an indirect dependency.
- Removing the error throwing when the cache fails to read or write, to improve the resilience of builds.
- Adding locking to the request method based on the cache key generated from the query. This locking performs 2 functions:
- Prevents the near-simultaneous transmission of 2 or more copies of the same request, by forcing later requests to wait for the result of the first request.
- Prevents the reading of partially written cache files.
=> 🐛 Bug - Race condition in the request cache

.changeset/witty-buses-film.md, packages/tinacms/src/toolkit/core/media.ts
Update MediaManager to encode image paths in the list() function to prevent broken links.
Fixes #5449
=> fix: encode media urls to prevent invalid characters from breaking links

.changeset/ten-frogs-wait.md, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/templates-toolbar-button.tsx
As reported in #5395 when adding an embed in the rich text editor, the browser window sometimes closes. Instead of calling `[window.]close()`, we should be calling `setOpen(false)`
=> fix: #5395 call setOpen instead of window.close

.changeset/spicy-queens-flow.md, packages/tinacms/src/toolkit/core/media.ts
Remove the console.error that occurs after not parsing a url. 
**Figure: Console error in browser**
=> Remove the console.log for failing to encode a url

.changeset/four-seals-develop.md, packages/@tinacms/graphql/src/database/index.ts
Fixes: https://github.com/tinacms/tinacloud/issues/2603
Fix issue where existing indexes are not removed prior to reindexing via the `indexContentByPaths` database method
=> fix: ensure existing indexes for doc are removed before reindexing

.changeset/metal-meals-fail.md, packages/@tinacms/cli/src/next/commands/baseCommands.ts, packages/@tinacms/cli/src/next/commands/dev-command/index.ts
I have an email: Solliance: Installing TinaCMS - 🌸 improving the command prompt #2
Adam had some comments about the CLI updates:
```
Hey Isaac 👋 
See while Paul was installing TinaCMS, when he looked at his Command Prompt - he thought he was blocked when he was not. In the history you will see Paul said:
>got these warnings attached in pic below.
>Paul
I think it should make it clearer what the next step is. These changes should help.
1. Arrow #1 - Change from
Starting Tina Dev Server
To
TinaCMS 🦙 Dev Server is initialing...
2. Arrow #2 - Change from
Tina Dev Server is running...
To
TinaCMS 🦙 Dev Server is starting:
3. Arrow #3 - Change from
Starting subprocess:
To
✅ TinaCMS 🦙 is up and running...
4. Do you think the green tick is enough? (I think so)
Or do we need more of what to do …
```
=> ℹ️ CLI Prompts – Superficial CLI updates email task

.changeset/rude-pigs-pretend.md, packages/tinacms/src/toolkit/core/media.ts
Media manager urls with special characters are broken #5513
Fix encoding function. The URL object already encodes url parts, so the function can just return the url from the object
=> fix: double encoding media urls

.changeset/late-sheep-buy.md, packages/@tinacms/graphql/src/database/datalayer.ts, packages/@tinacms/graphql/src/resolver/index.test.ts, packages/@tinacms/graphql/src/resolver/index.ts
Fix #5534  Root cause was the wrong collection was being used on the update call when updating documents containing references. 
- Also added logic to only perform updates when reference changes were made to avoid unnecessary updates.
- Fixed bug where null values were being inserted due to [null] values returned by JSONPath
=> fix: #5534 to use correct collection when updating docs with references

.changeset/healthy-elephants-impress.md, .github/workflows/main.yml, packages/tinacms/src/auth/TinaCloudProvider.tsx
Fixes #5557 
When using editorial workflow and accessing the admin and the last accessed branch no longer exists, branch switcher should reset instead of trying to load the branch that doesn't exist
=> fix: branch switcher bug when branch has been deleted

packages/@tinacms/cli/src/next/commands/build-command/index.ts
This pr fixes the comparison during the schema diff check. Previously, the remote was considered the new schema and local the old. This has been reversed in this pr.
=> fix: consider the remote schema to be the old and local to be new.

.github/workflows/main.yml, examples/empty/package.json, examples/kitchen-sink/package.json, examples/next-2024/package.json, examples/tina-self-hosted-demo/package.json, experimental-examples/tina-cloud-starter/package.json, packages/@tinacms/app/package.json, packages/@tinacms/cli/package.json, packages/@tinacms/datalayer/package.json, packages/@tinacms/graphql/package.json, packages/@tinacms/search/package.json, packages/@tinacms/vercel-previews/package.json, packages/next-tinacms-azure/package.json, packages/next-tinacms-cloudinary/package.json, packages/next-tinacms-dos/package.json, packages/next-tinacms-s3/package.json, packages/tinacms-authjs/package.json, packages/tinacms-clerk/package.json, packages/tinacms-gitprovider-github/package.json, packages/tinacms/package.json
I Accidentally published packages by tagging the 'Version Packages' PR, so I deprecated the published versions.
This pull request includes a series of version bumps across multiple `package.json` files and a modification to a GitHub workflow. The changes ensure that dependencies are up to date and refine the workflow conditions.
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L90-R91): Added a condition to exclude pull requests with the title 'Version Packages' from triggering the workflow.
=> Rev-package-versions

.changeset/ten-years-cheat.md, packages/create-tina-app/src/index.ts, packages/create-tina-app/src/util/checkPkgManagers.ts, packages/create-tina-app/src/util/install.ts
This PR adds the `bun` package manager to the `create-tina-app` CLI tool.
It also cleans up a bunch of dead code related to the package manager install
command.
=> feat: Added `bun` package manager

.changeset/popular-adults-marry.md, packages/@tinacms/graphql/src/database/index.ts
https://github.com/tinacms/tinacms/pull/5481 introduced an performance issue when performing full reindex due to unnecessary querying of every item.
Querying only needs to happen for a partial reindex so add a parameter to limit deletion to only partial reindexing
=> fix: only delete existing items when partial indexing

packages/@tinacms/graphql/package.json, pnpm-lock.yaml
While documenting the @tinacms/graphql package, I found that the `pnpm serve` command no longer works.
This change:
- Removes the `pnpm serve` command
- Removes the dev dependency on `nodemon` within the @tinacms/graphql package
=> 🔥 Deletion - Remove 'pnpm serve' from @tinacms/graphql package

.changeset/config.json, examples/basic-iframe/package.json, examples/empty/package.json, examples/kitchen-sink/package.json, examples/next-2024/package.json, examples/tina-self-hosted-demo/package.json, experimental-examples/kitchen-sink/package.json, experimental-examples/tina-cloud-starter/package.json
This pull request introduces changes to organize and namespace example projects more effectively by updating their package names and configuring the changeset tool to ignore specific namespaces. The most important changes include renaming packages under `examples` and `experimental-examples` directories and updating the `.changeset/config.json` file to exclude these namespaces from versioning.
* Updated package names in the `examples` directory to use the `@examples` namespace. This change affects the following files:
- `examples/basic-iframe/package.json` (`starter-basic-iframe` → `@examples/starter-basic-iframe`)
- `examples/empty/package.json` (`starter-empty` → `@examples/starter-empty`)
- `examples/kitchen-sink/package.json` (`e2e-next` → `@examples/e2e-next`)
- …
=> Changeling - ignore example projects

.changeset/orange-bottles-agree.md, packages/@tinacms/cli/src/next/vite/index.ts, packages/@tinacms/scripts/src/index.ts
This pull request includes changes to modify the source map generation settings and fix formatting issues in the codebase. The most important changes are grouped below by theme.
* [`packages/@tinacms/cli/src/next/vite/index.ts`](diffhunk://#diff-b1fda4e536e3c44a60ad0d8b39e7c8922e76a9d25745084ae2d5140042719e8dL242-R242): Changed `sourcemap` setting in the `build` configuration from `true` to `false` to disable source map generation.
* [`packages/@tinacms/scripts/src/index.ts`](diffhunk://#diff-a9a90706203d9df28f641832cd8977957afe053167ca6c9b92240cd6431e87ebL442-R441): Updated the `sourcemap` setting in the `buildIt` function to `false`, disabling source map generation for builds.
* [`packages/@tinacms/scripts/src/index.ts`](diffhunk://#diff-a9a90706203d9df28f641832cd8977957afe053167ca6c9b92 …
=> Disable sourcemap generation 

.changeset/itchy-apricots-sort.md, packages/next-tinacms-azure/src/azure-media-store.ts
This PR fixes a bug where structured values like thumbnailSizes in the MediaListOptions would be serialized as `[object Object]` in the query string. Now, objects are correctly passed as JSON strings using `encodeURIComponent(JSON.stringify(...))`.
=> fix(next-tinacms-azure): properly serialize thumbnailSizes in media queries

.changeset/hungry-moles-allow.md, packages/@tinacms/cli/src/next/commands/build-command/index.ts, packages/@tinacms/cli/src/utils/sleep.ts
This pull request introduces enhancements to the `BuildCommand` in `@tinacms/cli`, focusing on better branch handling, improved error reporting, and code cleanup. The changes include adding branch detection for bot branches, improving error logging, and refactoring functions for better readability and maintainability.
Relates to: https://github.com/tinacms/tinacloud/issues/2777
* Added logic to detect "bot" branches (e.g., dependabot) and use the default branch schema/content instead, with warnings logged for clarity.
* Improved error handling with a `try-catch` block to log errors more effectively and exit gracefully when issues occur. Verbose mode now outputs full error details.
* Enhanced branch checking by introducing retries for unknown branch statuses, with a maximum retry limit and …
=> refactor: improve build output for 'bot' branches

.changeset/brave-bobcats-flash.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx, packages/tinacms/src/toolkit/form-builder/form-builder.tsx
This change:
- Corrects the spelling of `CreateBranchModel` to `CreateBranchModal` throughout TinaCMS.
- Renames the `relativePath` property to `path` - this is to minimize future confusion about the path, which is not relative to any collection.
As the original `CreateBranchModel` was publicly exposed, a wrapper type is added with a deprecated warning.
=> ✏️ Typo - Rename CreateBranchModel to CreateBranchModal

.changeset/metal-spies-wonder.md, packages/@tinacms/cli/src/cmds/forestry-migrate/index.ts, packages/@tinacms/cli/src/cmds/init/apply.ts, packages/@tinacms/cli/src/cmds/init/detectEnvironment.ts, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/cli/src/cmds/init/prompts/index.ts, packages/@tinacms/cli/src/cmds/init/prompts/types.ts, packages/@tinacms/graphql/src/database/util.ts, packages/@tinacms/schema-tools/src/types/index.ts, packages/@tinacms/schema-tools/src/validate/schema.ts, pnpm-lock.yaml
This PR dedupes format and content types by moving them into `@tinacms/schema-tools`.
This superseeds #5633
=> feat: dedupe format types by moving them into schema-tools

.changeset/polite-pans-scream.md, packages/tinacms/src/internalClient/index.ts, packages/tinacms/src/toolkit/react-sidebar/components/VersionInfo.tsx, packages/tinacms/src/toolkit/react-sidebar/components/nav.tsx
This pull request introduces a feature to display the latest version information for TinaCMS in the sidebar, enhancing user awareness of updates. The main changes include adding a new API method to fetch version data, creating a `VersionInfo` component for the UI, and integrating it into the sidebar navigation.
Closes #5735
* Added a `getLatestVersion` method in the `internalClient` to fetch the latest version information from the production content API. This method handles API requests and error management. (`packages/tinacms/src/internalClient/index.ts`, [packages/tinacms/src/internalClient/index.tsR571-R591](diffhunk://#diff-e02e8af8c0fef23bc974a290d85cd5e497cc4169cebb545ddac9b9499da4f352R571-R591))
* Introduced new TypeScript types: `PackageVersionInfo` and `LatestVersionResponse`, to …
=> feat: Sidebar - show whether there are updates available

.changeset/four-colts-protect.md, packages/@tinacms/app/src/lib/graphql-reducer.ts, packages/tinacms/src/react.tsx
https://github.com/tinacms/tinacms/issues/5831
Fixes a loading state issue when using webpack on local dev. HMR refreshes page which triggered a loading state that was is never set to false.
=> 🐛 FIX - Visual Editor Webpack HMR loading issue

packages/@tinacms/graphql/tests/pending-document-with-template/addPendingDocument-article-response.json, packages/@tinacms/graphql/tests/pending-document-with-template/addPendingDocument-product-response.json, packages/@tinacms/graphql/tests/pending-document-with-template/index.test.ts, packages/@tinacms/graphql/tests/pending-document-with-template/new-article-content.md, packages/@tinacms/graphql/tests/pending-document-with-template/new-product-content.md, packages/@tinacms/graphql/tests/pending-document-with-template/tina/config.ts
This change adds a basic automated test to ensure that `addPendingDocument` can be successfully called with a template selection.
=> 🧪 GraphQL Test - addPendingDocument mutation with template

.changeset/lucky-cups-give.md, packages/create-tina-app/src/index.ts
This pull request addresses compatibility issues with the CLI for `create-tina-app`, specifically improving support for CommonJS environments. 
* Changed the import of `ora` in `packages/create-tina-app/src/index.ts` to use a dynamic import, ensuring compatibility with both CommonJS and ES modules
Fixes: #5938
Can be run with `npx create-tina-app@0.0.0-d795c47-20250806022207`
=> fix: CLI ora import

.changeset/twenty-yaks-sell.md, .vscode/settings.json, packages/@tinacms/cli/src/next/vite/plugins.ts, packages/tinacms/src/toolkit/components/media/media-item.tsx, packages/tinacms/src/toolkit/components/media/media-manager.tsx
This pull request improves the media manager in the `tinacms` package, focusing on better handling and display of images—especially those with transparency—and enhancing the user experience in grid view. It also includes minor configuration updates for development tooling.
closes #5930
**Media Manager UI Improvements:**
* Transparent images are now displayed with a checkerboard background in both grid and preview views, making them easier to identify visually. (`media-item.tsx`, `media-manager.tsx`) [[1]](diffhunk://#diff-e656e9a630ce8ab182c9708cd34fbb8d2b2bfaf5f31b7d20e42469795642795dL36-R59) [[2]](diffhunk://#diff-e656e9a630ce8ab182c9708cd34fbb8d2b2bfaf5f31b7d20e42469795642795dL91-R137) [[3]](diffhunk://#diff-78421bfdaed7860cfed1b864d9d38c17242919f6376dd9fcc54a01a7e7679654L562-R563)
* …
=> Media manager - improve handling of transparent images

packages/@tinacms/cli/src/cmds/init/apply.ts, packages/@tinacms/cli/src/cmds/init/prompts/index.ts, packages/@tinacms/cli/src/cmds/init/prompts/types.ts
This PR adds support for the Bun package manager to the `tinacms init` command. 
The `create-tina-app` package already supports Bun, so this update brings parity between the two tools.
- Added "Bun" option to the interactive package manager prompt (`prompts/index.ts`).
- Extended TypeScript union type in `prompts/types.ts` to include `'bun'`.
- Added Bun command mappings in `apply.ts`:
- Regular dependencies: `bun add <deps>`
- Dev dependencies: `bun add -D <devDeps>`
- Next.js projects: `bun run dev`
- Other frameworks: `bunx tinacms dev -c "<your dev command>"`
- No breaking changes.
- Existing npm, yarn, and pnpm flows remain unchanged.
- Bun support follows the same conventions used for other package managers.
- Verified locally:
- Bun commands generate correctly for dependencies and …
=> feat(cli): add Bun support to `tinacms init` package manager options

packages/tinacms/src/toolkit/components/media/media-item.tsx
Overlay position was a child of the image, so it looked weird 
**Figure: Before**
**Figure: After**
=> Improve position of title overlay
