tinacms/tinacms

README.md
=> content: add tip to readme

packages/demo-gatsby/gatsby-config.js, packages/gatsby-plugin-tinacms/README.md, packages/tinacms/src/components/Tina.tsx
=> fix: SidebarPosition can be displace/overlay

packages/@tinacms/core/src/cms-forms/form.ts, packages/@tinacms/form-builder/src/final-form-builder.tsx, packages/demo-gatsby/src/templates/blog-post.js
=> Feature: add custom validate functions to fields

packages/@tinacms/api-git/src/commit.ts, packages/@tinacms/api-git/src/router.ts, packages/@tinacms/api-git/src/show.ts
=> Fix git file creation

CONTRIBUTING.md
=> fix: Correct minor typos on contributing.md

packages/@tinacms/api-git/src/commit.ts, packages/@tinacms/api-git/src/router.ts, packages/@tinacms/git-client/src/git-client.ts
/cc #209 
@ncphillips Does this approach make sense to you?
=> feat(git): implement pushOnCommit option

packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/Menu.tsx
closes https://github.com/tinacms/tinacms/issues/360
=> fix: remove margin from wysiwyg menu buttons

package-lock.json, packages/@tinacms/fields/package.json, packages/@tinacms/styles/package.json, packages/tinacms/package.json
Addresses part of the issue in #362
=> fix: styled-components is a peerDependency

packages/gatsby-tinacms-git/gatsby-browser.ts
=> chore: improve error if missing window.tinacms

packages/@tinacms/api-git/src/commit.ts
fix(git): fix `no upstream branch` error while pushing on Tina Teams
fixes #163
=> fix(git): fix no-upstream branch on push on cloud

packages/tinacms/src/tina-cms.ts
=> chore(global menu): remove placeholder items

README.md
=> added tweet button to readme

packages/react-tinacms/src/use-form.ts
=> fix: early return for empty watch values

README.md
Replacing `Tina CMS` with an image and adding the icon to bring a bit more Tina brand into the readme. [See what it looks like here](https://github.com/tinacms/tinacms/blob/ebcb405e188554408636aa88c6e4fcd1f8779e1d/README.md)
=> Branding README with wordmark and icon

packages/tinacms/src/components/FormView.tsx, packages/tinacms/src/components/LoadingDots.tsx
This PR is connected to the [ticket](https://github.com/tinacms/tinacms/issues/4490). 
feat: Add loading indicator on saving
- create new LoadingDots components
- add submitting props to the component (coming from final-form library)
- add conditional content rendering in save button
---
There were also a conversation about adding some kind of 'Saved' indicator, but I think that might be a separate PR if the team agrees on that.
=> Add loading indicator on save proccess

package-lock.json, package.json, packages/@tinacms/styles/src/Button.tsx, packages/tinacms/src/components/FormView.tsx
@maciekgrzybek created a loading dots component that can be used to indicate something is happening after a button press for asynchronous actions and implemented it on the form save button.
I also added a `busy` state to the button component. Right now it only sets `cursor: wait;`, but we could add to that in the future.
=> Add saving indicator for save button

packages/react-tinacms/src/use-cms.ts, packages/tinacms/package.json
=> Hotfix ssr window access

packages/gatsby-tinacms-json/src/use-json-form.ts
This is a chore because it is a regression that was not yet introduced into master.
=> chore: fix committing json files

packages/@tinacms/api-git/src/commit.ts, packages/demo-gatsby/content/blog/toottoot/index.md
fix(git): Simplegit deprecated passing a string into revparse, but the arguments should be individual elements in the array
=> Revparse fix

package-lock.json
=> chore(package): update package lock

.github/workflows/release-canary.yml
=> chore(canary): cleanup lock files after build

packages/@tinacms/api-git/src/commit.ts
=> chore(git): trigger git commit

packages/@tinacms/teams/README.md, packages/@tinacms/teams/package.json, packages/@tinacms/teams/src/authMiddleware.ts, packages/gatsby-tinacms-teams/README.md
Updating README files for Teams packages.
=> Teams Docs

packages/gatsby-tinacms-json/package.json
=> fix(typescript): Corrected path to type definitions

packages/@tinacms/core/src/plugins.test.ts
A small test which behaves the same as the `add plugin` test to check that a plugin is removed
=> Test: Add test for removing plugin

packages/react-tinacms-blocks/src/blocks.spec.tsx, packages/react-tinacms-blocks/src/blocks.tsx, packages/react-tinacms-blocks/src/inline-blocks.tsx
Might want to step through the commits. There was some formatting issues.
=> Give blocks the form

packages/@tinacms/form-builder/src/Form.tsx
=> Tinafield proptypes

packages/gatsby-tinacms-remark/gatsby-node.js
=> fix: remove unused argument from schema

packages/gatsby-tinacms-remark/package.json
Updated peer dependency in gatsby-tinacms-remark to `=> 2.1.1`
Closes #484
=> Update gatsby-transformer-remark peer dep

packages/@tinacms/api-git/src/file-writer.ts
This should help with multi-user mode
closes #305
Works as a single user. Needs to be tested with multiple users at once.
=> feat(file-writer): queue changes per-file

packages/@tinacms/forms/src/form.ts, packages/react-tinacms-blocks/src/inline-blocks.tsx, packages/tinacms/src/components/FormView.tsx, packages/tinacms/src/plugins/fields/BlocksFieldPlugin.tsx, packages/tinacms/src/plugins/fields/GroupListFieldPlugin.tsx
Add `form.mutators` adapter so clients do not hve to do `form.finalForm.mutators`.
=> Form mutators

packages/gatsby-tinacms-json/gatsby-node.js
=> Import correct GraphQLString type from gatsby

package-lock.json, packages/next-tinacms-json/package-lock.json, packages/next-tinacms-json/src/use-json-form.ts
Updates `useJsonForm` to write all form values to disk, rather than just title 🤠
=> Fix next-tinacms-json writeToDisk values

package-lock.json, package.json, packages/@tinacms/api-git/package-lock.json, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/Menu.tsx, packages/@tinacms/react-core/package-lock.json, packages/demo-gatsby/content/blog/toottoot/index.md, packages/demo-gatsby/src/templates/blog-post.js, packages/react-dismissible/package-lock.json, packages/react-tinacms-blocks/package-lock.json
Hey. 
This may seem a little much for this functionality. But check it out. I think it's necessary as the structure on things are now. It isn't possible to just set the positioning to "sticky"
Thomas
=> Fixed sticky menu on inline editing

packages/gatsby-tinacms-remark/src/remark-creator-plugin.ts
=> fix: make Field interface accept extra properties

packages/@tinacms/fields/src/Wysiwyg/ProseMirrorCss.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Table/index.ts, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Table/utils.ts
=> feat: adding highlighting to table selection

package.json, scripts/nuke.sh
make the command more comprehensive
=> build: add nuke script

packages/@tinacms/fields/src/Wysiwyg/ProseMirrorCss.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/FloatingTableMenu.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/Menu.tsx
Delete option for selected columns / rows in table.
=> Adding delete column/row option to table.

packages/tinacms/src/plugins/fields/ColorFieldPlugin.tsx, packages/tinacms/src/plugins/fields/ImageFieldPlugin.tsx, packages/tinacms/src/plugins/fields/MarkdownFieldPlugin.tsx, packages/tinacms/src/plugins/fields/SelectFieldPlugin.tsx, packages/tinacms/src/plugins/fields/TextareaFieldPlugin.tsx, packages/tinacms/src/plugins/fields/textFormat.test.ts, packages/tinacms/src/plugins/fields/textFormat.ts
This PR fixes #632 .
I label it as a fix, but, I'm not sure if it's the correct label.
=> fix: FieldPlugins for text have a default to empty string

packages/gatsby-tinacms-json/package.json
tinacms should be a peer
the others aren't actually used
=> fix(deps): stripped out unnecessary deps

packages/tinacms/src/components/FormView.tsx
Updated link in form setup guide to https://tinacms.org/docs/getting-started/introduction/#get-started 
Fix #656
=> chore: updated link to form setup guide in sidebar

CONTRIBUTING.md, README.md, RELEASE.md
Just made a few updates to the top-level docs in the repo
=> Minor updates to README, CONTRIBUTING, and RELEASE

packages/@tinacms/form-builder/package.json, packages/@tinacms/form-builder/src/Form.tsx, packages/@tinacms/form-builder/src/fields-builder.tsx, packages/@tinacms/form-builder/src/form-builder.tsx, packages/@tinacms/form-builder/src/index.ts
- split form-builder and field-builder into separate files
- update peerDeps
=> Minor Maintenance to @tinacms/form-builder 

packages/@tinacms/fields/src/Wysiwyg/plugins/index.ts, packages/@tinacms/fields/src/Wysiwyg/plugins/keymap.ts, packages/@tinacms/fields/src/Wysiwyg/state/buildKeymap.ts, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/FloatingTableMenu/AddColumnMenu.tsx
PR fixes use of Tab and Arrow keys inside table.
More work is still needed for arrow up/down keys.
=> Fix in table keymap.

packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/FloatingTableMenu/TableOptionsMenu.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/FloatingTableMenu/index.tsx, packages/demo-gatsby/content/blog/toottoot/index.md
=> Adding table delete option.

packages/demo-next/components/BlogList.js, packages/demo-next/components/Layout.js, packages/demo-next/data/config.json, packages/next-tinacms-json/src/inline-json-form.hoc.tsx
Resolves: #700 
I didn't test this as much as I would have liked, but I think it will probably work. Mostly posting this for thoughts and happy to address any feedback!
Apologies that I picked this up after the good first issue was added! I had already done the digging to try to see what was up and wrote the code when I noticed @ncphillips added the label.
=> fix: having next tinacms json respect passed down props in getInitialProps

packages/@tinacms/core/src/cms.ts, packages/demo-gatsby/gatsby-browser.js, packages/demo-gatsby/gatsby-config.js, packages/gatsby-plugin-tinacms/gatsby-browser.tsx, packages/gatsby-plugin-tinacms/gatsby-ssr.tsx, packages/tinacms/src/components/Tina.tsx, packages/tinacms/src/index.ts, packages/tinacms/src/react-tinacms/with-tina.tsx, packages/tinacms/src/tina-cms.ts
Original work by @DaniTulp.
Merged into this branch to run CI and do one more change.
=> Gatsby tinacms manual init

packages/demo-gatsby/src/pages/about.js, packages/gatsby-tinacms-mdx/src/mdxFormHoc.tsx
The purpose of this branch is because we have multiple people contributing to this feature
=> Mdx testing

packages/@tinacms/fields/src/NumberInput.tsx, packages/tinacms/src/plugins/fields/NumberFieldPlugin.tsx
the purpose of this pull request is for weibenfalk's number input feature to use the same styling as text input field.
=> Use Tina styles for NumberInput component

dangerfile.ts
Update script to reflect that the docs site is in a new repo
=> build(danger): update url for new docs issues

.github/CODEOWNERS
I wonder if having a `@tinacms` in the path is an issue.
=> fix: Codeowners

packages/gatsby-plugin-tinacms/gatsby-browser.tsx, packages/gatsby-plugin-tinacms/gatsby-ssr.tsx, packages/gatsby-plugin-tinacms/options.ts, packages/tinacms/src/components/Tina.tsx, packages/tinacms/src/index.ts, packages/tinacms/src/tina-cms.ts
Some recent "refactoring" actually broke APIs for hiding and theming the sidebar. This PR corrects that.
=> Tinacms constructor corrections

packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/ImageMenu/index.tsx
Fixing issues detailed here: https://github.com/tinacms/tinacms/issues/749
Hey @DirtyF : I could not replicate point-2 `when updating alt or title on an image, it saves properties for all images`
=> fix: image modal issues

packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/ImageMenu/index.tsx, packages/demo-gatsby/src/components/edit-toggle.js
More small fixes in image modal.
=> More fixes

packages/@tinacms/forms/src/form.ts, packages/@tinacms/react-core/src/use-form.ts, packages/gatsby-tinacms-json/src/use-json-form.ts, packages/gatsby-tinacms-remark/src/useRemarkForm.tsx, packages/next-tinacms-json/src/use-json-form.ts, packages/next-tinacms-markdown/src/use-markdown-form.ts
Let's you load the initialValues using a function
For example
```ts
new Form({
id: "blog/hello-world.md",
label: "Hello World",
loadInitialValues() {
return loadMarkdownFile("blog/hello-world.md")
}
})
```
=> Inline form initial values promise

packages/@tinacms/forms/src/form.ts, packages/@tinacms/react-core/src/use-form.ts, packages/demo-next/pages/blocks.tsx, packages/demo-next/pages/info.js, packages/demo-next/server.js, packages/gatsby-tinacms-json/src/use-json-form.ts, packages/gatsby-tinacms-remark/src/useRemarkForm.tsx, packages/next-tinacms-json/src/use-json-form.ts, packages/next-tinacms-markdown/src/use-markdown-form.ts
Several updates to correct Inline Editing
=> Inline form updates

packages/@tinacms/react-core/src/use-form.ts
Last piece that makes `react-tinacms-inline` work with tinacms.org
I made sure to check that both the development and built version of the site still work. I think it's clear sailing from here. 🤞
=> Use form default initial values

packages/tinacms/src/components/FormView.tsx, packages/tinacms/src/components/ResetForm.tsx, packages/tinacms/src/tina-cms.ts
closes #620
Based off work prototyped in #647
Co-authored-by: weibenfalk <thomas.weibenfalk@gmail.com>
=> feat(Sidebar): set the text of save/reset buttons

packages/tinacms/src/components/CreateContent.tsx, packages/tinacms/src/components/sidebar/Sidebar.tsx
- change sidebar header to display: grid with named areas
- add grid area names to hamburger menu and creat button
- add correct justify properties
- that will ensure that lack of either hemburger nor action button will not break the layout
fix https://github.com/tinacms/tinacms/issues/780
=> fix(sidebar): fix layout issue with sidebar header

packages/@tinacms/fields/package.json, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/ImageMenu/index.tsx
Noticed some warnings coming from danger. Fixed up a couple imports.
=> chore: fix lodash deps

packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/Menu.tsx
Blockquote menu option to toggle.
=> fix: blockquote option to toggle and not nest.

packages/@tinacms/fields/src/Wysiwyg/Wysiwyg.tsx, packages/@tinacms/fields/src/Wysiwyg/state/index.ts, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/Menu.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/index.tsx, packages/@tinacms/fields/src/Wysiwyg/useProsemirror.tsx, packages/tinacms/CHANGELOG.md
Using menu component and removing plugin.
This refactor is still remaining on link modal.
=> Removing menu plugin.

package-lock.json, package.json, packages/@tinacms/scripts/bin/scripts.js
- install and add typescript-plugin-styled-components to the rollup config
- the plugin creates better developer experience by adding meaningful class names
PR - https://github.com/tinacms/tinacms/issues/130
=> feat(rollup) Add ts plugin for better style components experience

packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/Menu.tsx, packages/demo-gatsby/src/templates/blog-post.js
```js
<Wysiwyg sticky="16px" />
```
=> feat(wysiwyg): change top-offset of sticky wysiwyg

packages/@tinacms/fields/src/Wysiwyg/Wysiwyg.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/FloatingTableMenu/FloatingTableAddMenu.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/FloatingTableMenu/FloatingTableColumnMenu.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/FloatingTableMenu/TableOptionsMenu.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/FloatingTableMenu/index.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/ImageMenu/index.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/Menu.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/index.tsx, packages/@tinacms/fields/src/Wysiwyg/useProsemirror.tsx
After my last PR to refactor menu I found there were issues in Image and Table menus. This PR fixes those.
=> Fix re-rendering in table and image menus.

packages/@tinacms/fields/src/Wysiwyg/state/index.ts, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Common/index.tsx
Fix for scroll issue in inline toolbar.
=> Inline toolbar scroll fix.

packages/@tinacms/fields/src/Wysiwyg/ProseMirrorCss.tsx, packages/@tinacms/fields/src/Wysiwyg/Wysiwyg.tsx, packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/ImageMenu/index.tsx, packages/@tinacms/fields/src/Wysiwyg/utils.ts
Fix for modal position for image and links.
=> Fix for modal positioning.

packages/react-tinacms-blocks/src/inline-blocks.tsx, packages/tinacms/src/components/form/FormActions.tsx, packages/tinacms/src/components/form/FormView.tsx, packages/tinacms/src/components/sidebar/CreateContentMenu.tsx, packages/tinacms/src/components/sidebar/SidebarBody.tsx, packages/tinacms/src/plugins/fields/BlocksFieldPlugin.tsx, packages/tinacms/src/plugins/screens/index.tsx
* Simplifies FormView to only accept a form prop
* Renders a form label for single forms
* Fixes z-index issues on some popups
Fixes #831
Fixes #800
=> Form Header Improvements

CONTRIBUTING.md
Spelling & grammatical error fix
=> fix: Update CONTRIBUTING.md - spelling & grammatical fix

packages/demo-cra/src/index.tsx
Update demo-cra to use TinaProvider and the cms object
=> fix: use TinaProvider and TinaCMS with demo-cra

packages/demo-gatsby/gatsby-browser.js, packages/gatsby-plugin-tinacms/gatsby-browser.tsx, packages/gatsby-plugin-tinacms/gatsby-ssr.tsx
=> fix: use TinaProvider instead of Tina

packages/react-tinacms-editor/src/Wysiwyg.tsx, packages/react-tinacms-editor/src/node-views/ImageView/index.ts, packages/react-tinacms-editor/src/node-views/index.ts, packages/react-tinacms-editor/src/state/plugins/Menu/Image/ImageMenu.tsx, packages/react-tinacms-editor/src/state/plugins/Menu/Menu.tsx, packages/react-tinacms-editor/src/useProsemirror.tsx, packages/react-tinacms-editor/stories/wysiwyg.stories.tsx
Support for image upload in editor as detailed here: https://github.com/tinacms/tinacms/issues/166
=> Image support in wysiwyg

packages/gatsby-tinacms-git/package.json
=> fix(gatsby-tinacms-git): include src in npm package

README.md, RELEASE.md
=> Docs updates

packages/@tinacms/react-modals/src/ModalProvider.tsx, packages/tinacms/src/components/TinaProvider.tsx, packages/tinacms/src/components/sidebar/Sidebar.tsx
Fixes #941 
Also prepares `TinaProvider` for the Toolbar, by moving the sidebar components into their own `SidebarProvider` function.
=> Refactor TinaProvider

packages/@tinacms/fields/src/components/ColorPicker/ColorPicker.tsx, packages/tinacms/src/plugins/fields/reactDatetimeStyles.ts
* Fix color picker popup z-index, 
* Uses Tina theme colors for date picker popup
closes #906
=> UI Bug Fixes

README.md
A fair warning to users.
props @ncphillips
=> docs: add disclaimer

packages/react-tinacms-editor/src/state/plugins/Common/index.tsx
If user is in code mark at end of line a arrow right will bring him out of it.
Fix #922
=> fix: not possible to come out of code mark which is at end of line

packages/@tinacms/fields/src/plugins/GroupListFieldPlugin.tsx
=> style: fix add block ddl position

packages/react-tinacms-editor/src/state/plugins/Image/index.ts
When using delete / backspace button image should be deleted only after selection.
@DirtyF : is it possible to get this tested on windows box also, is there a browserstack account for forestry ?
=> fix: image should be deleted only after selection

packages/@tinacms/react-sidebar/src/components/Sidebar.tsx, packages/@tinacms/react-toolbar/src/components/Toolbar.tsx
* Resets margin on status message <p>
* Sets box-sizing for Sidebar & Toolbar components.
=> Toolbar Style Fixes

dangerfile.ts, packages/@tinacms/react-alerts/jest.config.js, packages/@tinacms/react-alerts/src/Alerts.test.tsx, packages/@tinacms/react-alerts/src/Alerts.tsx
Added a few simple tests of logic.
Next Steps: test that the alerts are rendered in the correct order.
=> test: @tinacms/react-alerts

packages/@tinacms/alerts/src/alerts.test.ts, packages/@tinacms/alerts/src/alerts.ts
=> test: alerts collection functions

packages/react-tinacms-editor/src/commands/codeblock-commands.ts
=> fix: deleting code block

packages/react-tinacms-github/package.json
react-tinacms-github had this as a peer
Since it's not used anywhere else it can be a regular dep
=> chore: final-form-submit-listener dep

packages/react-tinacms-github/src/github-client/index.ts, packages/react-tinacms-github/src/toolbar-plugins/pull-request/PRModal.tsx, packages/react-tinacms-github/src/toolbar-plugins/pull-request/PRPlugin.tsx, packages/react-tinacms-github/src/toolbar-plugins/useGithubToolbarPlugins.tsx
Move baseBranch config out of Github context, so that it can be configurable outside of an env variable.
Also default it to master
=> Base branch config

packages/@tinacms/react-core/src/use-form.ts, packages/demo-gatsby/src/components/bio.js, packages/demo-gatsby/src/pages/index.js, packages/demo-gatsby/src/templates/blog-post.js, packages/gatsby-tinacms-json/src/use-json-form.ts, packages/gatsby-tinacms-remark/src/RemarkForm.tsx, packages/gatsby-tinacms-remark/src/remark-form-hoc.tsx, packages/gatsby-tinacms-remark/src/useRemarkForm.tsx, packages/next-tinacms-json/src/inline-json-form.hoc.tsx, packages/next-tinacms-json/src/inline-json-form.rc.tsx, packages/next-tinacms-json/src/json-form.hoc.tsx, packages/next-tinacms-json/src/use-global-json-form.ts, packages/next-tinacms-json/src/use-local-json-form.ts, packages/react-tinacms-github/src/form/useGithubFileForm.ts, packages/tinacms/src/react-tinacms/use-form.ts
Implemeting [RFC 0006](https://github.com/tinacms/rfcs/pull/7)
=> Deprecate local global keywords

packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx
After you authenticate with Github, fix issue where you had to click the authenticate button again
=> fix(github): fix issue where you need to click authenticate twice

packages/react-tinacms-github/src/github-error/github-interpeter.ts
Tweak error message on Github 404
=> Update error message on Github 404

packages/@tinacms/fields/src/components/Select.tsx
=> feat: added Option type for Select/SelectField

packages/react-tinacms-github/src/github-editing-context/GithubAuthModal.tsx, packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx
=> Fix auth modal close

packages/react-tinacms-github/src/github-client/github-client.ts
If the user is authorized to write to the repository then there's no need to fork created
=> react-tinacms-github: support working from origin

packages/react-tinacms-github/src/github-client/index.ts, packages/react-tinacms-github/src/github-media-store/base64File.ts, packages/react-tinacms-github/src/github-media-store/index.ts
Adds the GithubMediaStore to store media in Github.
=> Adding GithubMediaStore

packages/react-tinacms-editor/src/components/Editor/styles/ProseMirror.tsx, packages/react-tinacms-editor/src/plugins/Table/Popup/AddColumn.tsx, packages/react-tinacms-editor/src/plugins/Table/Popup/AddRow.tsx, packages/react-tinacms-editor/src/plugins/Table/Popup/ColumnPopup.tsx, packages/react-tinacms-editor/src/plugins/Table/Popup/OptionsPopup.tsx, packages/react-tinacms-editor/src/plugins/Table/plugin.ts
Fixes issue with click event on table floating menus not working correctly.
=> fix: issue with table menu click event not trigerred

packages/react-tinacms-github/src/github-client/github-client.ts, packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx
Happens when trying to set cookies in SSR
fixes #1109
=> fix: callstack exceeded when accessing branchName

packages/react-tinacms-github/src/form/useGithubFileForm.ts
Allows for:
```ts
useGithubFileForm({
actions: [ SomeAction ]
})
```
=> fix: use-github-form accepts actions

packages/react-tinacms-editor/src/schema/marks/code.ts, packages/react-tinacms-editor/src/schema/marks/em.ts, packages/react-tinacms-editor/src/schema/marks/link.ts, packages/react-tinacms-editor/src/schema/marks/strong.ts, packages/react-tinacms-editor/src/schema/nodes/blockquote.ts, packages/react-tinacms-editor/src/schema/nodes/code-block.ts, packages/react-tinacms-editor/src/schema/nodes/doc.ts, packages/react-tinacms-editor/src/schema/nodes/hard-break.ts, packages/react-tinacms-editor/src/schema/nodes/heading.ts, packages/react-tinacms-editor/src/schema/nodes/hr.ts, packages/react-tinacms-editor/src/schema/nodes/image.ts, packages/react-tinacms-editor/src/schema/nodes/list-bullet.ts, packages/react-tinacms-editor/src/schema/nodes/list-item.ts, packages/react-tinacms-editor/src/schema/nodes/list-ordered.ts, packages/react-tinacms-editor/src/schema/nodes/paragraph.ts, packages/react-tinacms-editor/src/schema/nodes/tables.ts, packages/react-tinacms-editor/src/schema/nodes/text.ts, packages/react-tinacms-editor/src/types.ts
Cleanup of prosemirror editor schema.
---
Closes #1090 — Just realized that the [closing keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) have to be put in the PR description to work properly
=> chore: cleanup of schema

packages/demo-gatsby/src/templates/blog-post.js
=> gatsby-demo-fix: add previewSrc and render props to blog thumbnail

README.md, dangerfile.ts, package.json
It's flaky and will make your computer explode
=> docs: removed references to the watch commands

packages/next-tinacms-github/src/next/preview.ts, packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx
=> fix: fixed setting github working branch

packages/react-tinacms-github/src/github-client/github-client.ts
=> feat: added a fetch file method to the github client

packages/gatsby-tinacms-remark/gatsby-browser.js, packages/gatsby-tinacms-remark/package.json
this is done dynamically to help reduce bundle size
=> feat: register markdown and html fields

packages/react-tinacms-inline/src/fields/inline-image-field.tsx
Would be great if we could give more specific feedback based on network responses, but this is a better first step.
=> Adds error alert for inline image 

packages/demo-gatsby/src/components/blog-blocks.js, packages/demo-gatsby/src/templates/blog-post.js, packages/demo-next/pages/blocks.tsx, packages/demo-next/pages/blog/[slug].tsx, packages/demo-next/pages/info.js, packages/react-tinacms-inline/src/blocks/inline-block-image.tsx, packages/react-tinacms-inline/src/blocks/inline-block-text.tsx, packages/react-tinacms-inline/src/blocks/inline-block-textarea.tsx, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx, packages/react-tinacms-inline/src/fields/inline-image-field.tsx, packages/react-tinacms-inline/src/fields/inline-text-field.tsx, packages/react-tinacms-inline/src/fields/inline-textarea-field.tsx, packages/react-tinacms-inline/src/index.tsx
`Inline${Input}Field` 👉 `Inline${Input}`
=> Refactor: Rename inline fields

packages/@tinacms/core/src/cms.ts
this is THE source of truth for whether or not the CMS content should be editable
_Note: this is a prototype_
=> feat(cms): add new first-class enabled state

README.md
=> Add note on node version to README

packages/@tinacms/fields/src/plugins/BlocksFieldPlugin.tsx, packages/@tinacms/forms/package-lock.json, packages/demo-gatsby/package-lock.json, packages/demo-next/pages/nesting.tsx, packages/react-tinacms-inline/package.json, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx, packages/react-tinacms-inline/src/inline-group/inline-group-settings.tsx, packages/react-tinacms-inline/src/inline-group/inline-group.tsx
This PR addresses several issues around inline editing w.r.t. nesting components
See commit messages for details
=> Inline nesting

packages/demo-next/pages/info.js, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/inline-group/inline-group-controls.tsx, packages/react-tinacms-inline/src/styles/focus-ring.tsx, packages/react-tinacms-inline/src/styles/index.ts, packages/react-tinacms-inline/src/styles/input-focus-wrapper.tsx
Also adds controls for `offset` & `borderRadius`
=> (react-tinacms-inline): Consolidates focus ring

commitlint.config.js
Thanks @IronSean for reminding me how annoying that was.
=> build: more leniant message casing

packages/react-tinacms-inline/src/blocks/add-block-menu.tsx, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
moved focus setting up to the main blocks field
=> chore: adding more blocks sets focus to the new block

package-lock.json, packages/@tinacms/fields/package.json, packages/react-tinacms-editor/package-lock.json, packages/react-tinacms-editor/package.json
@jhuggett experienced build failures on Node 12.17, appears to be due to https://github.com/storybookjs/storybook/issues/10477
this resolves the issue
=> chore: bump storybook version

packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
This potentially fixes @kendallstrautman's "'Tall' block menu items" UI glitch.
=> style: add block flex menu

packages/@tinacms/react-core/src/use-form.ts, packages/gatsby-tinacms-git/src/use-git-form.ts
=> Load initial values when enabled

packages/@tinacms/fields/src/components/ImageUpload/ImageUpload.tsx, packages/@tinacms/fields/src/plugins/ImageFieldPlugin.tsx
=> feat(ImageFieldPlugin): support async previewSrc

ROADMAP.md
Updated ROADMAP to describe the core team's general process and to show the current projects
[Rendered Text](https://github.com/tinacms/tinacms/blob/18866c568dd571db0d143ebd2345b5b3f96c8b14/ROADMAP.md)
=> docs: updated ROADMAP

packages/demo-gatsby/data/author.json, packages/gatsby-tinacms-git/src/use-git-form.ts, packages/gatsby-tinacms-json/src/use-json-form.ts, packages/gatsby-tinacms-remark/src/use-remark-form.tsx
Fixes issue brought up in [forum](https://community.tinacms.org/t/image-preview-src-is-undefined/197)
=> fix: jsonNode should be in form values

packages/react-dismissible/README.md, packages/react-dismissible/src/Dismissible.tsx
Removes the need to add extra divs.
Thanks to @weibenfalk for doing the necessary refactoring months ago!
[Updated Documentation](https://github.com/tinacms/tinacms/blob/9d88cee0a175a769d345b8150e3114e87da485d9/packages/react-dismissible/README.md)
=> feat: useDismissible hook without a component

packages/react-tinacms-inline/src/inline-settings.tsx
=> fix: block/group panels now stay within the settings modal

packages/react-tinacms-editor/src/components/ProsemirrorEditor/index.tsx, packages/react-tinacms-editor/src/plugins/CodeBlock/plugin.ts
Fix for code block not using code mirror.
This appears to be regression from recent refactoring.
=> fix: code block node view

packages/@tinacms/react-sidebar/src/components/NoFormsPlaceHolder.tsx, packages/@tinacms/react-sidebar/src/components/Sidebar.tsx, packages/@tinacms/react-sidebar/src/components/SidebarBody.tsx, packages/@tinacms/react-sidebar/src/sidebar.ts, packages/demo-next/pages/_app.js
=> refactor: changed way internal logic works and the exposed api

packages/react-tinacms-editor/src/components/BaseMenubar/index.tsx, packages/react-tinacms-editor/src/components/MarkdownEditor/index.tsx, packages/react-tinacms-editor/src/components/Wysiwyg/index.tsx
Fix scrolling in editor when changing mode.
Fixes https://github.com/tinacms/tinacms/issues/1225
=> fix: editor scrolling while changing mode

packages/react-tinacms-inline/src/fields/inline-textarea-field.tsx
=> chore: inline textarea shows focus ring by default

packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx, packages/react-tinacms-github/src/toolbar-plugins/BranchSwitcherPlugin.tsx
Automatically close auth & branch switching modals on success
=> Fix GitHub modal dismiss

packages/react-tinacms-github/src/github-client/authenticate.ts, packages/react-tinacms-github/src/github-client/github-client.ts
Changing the name of the new authentication token to something less generic and updated the old auth flow deprecation link to the new post title.
=> Changed token name and updated deprecation link

packages/demo-next/pages/blocks.tsx, packages/demo-next/pages/nesting.tsx, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
changed the direction of inline blocks from row and col to vertical and horizontal and also updated the next-demo
=> changed the direction of inline blocks from row and col to vertical and horizontal

README.md
I updated the readme so that the "community" link went to the community page instead of the doc pages. Not sure why it was linked to the docs was kinda confusing for me at least.
=> fix: update readme to correct links

packages/react-tinacms-editor/src/schema/nodes/code-block.ts
Fixes https://github.com/tinacms/tinacms/issues/1138
=> fix: fenced code blocks

packages/next-tinacms-github/README.md
when trying to update packages i didn't immediately see why my build was failing - this was the reason
=> fix: adjust readme to new signature

packages/next-tinacms-github/src/next/preview.ts
Changing an error message for the previews route to help when setting up authentication.
=> chore: updated previews error message

packages/react-tinacms-github/src/github-client/github-client.ts
added ability to delete files with github client
=> feat: added ability to delete files with github client

packages/react-tinacms-github/src/github-client/GithubFile.ts
=> fix(react-tinacms-github): added check for empty sha

packages/react-tinacms-github/README.md
The image currently doesn't work.
=> feat: added github delete action docs to readme

packages/gatsby-plugin-tinacms/README.md, packages/gatsby-tinacms-git/README.md, packages/gatsby-tinacms-json/README.md, packages/gatsby-tinacms-remark/README.md
Mainly copied over helper info from the guides
=> docs: Gatsby packages

packages/react-tinacms-date/README.md, packages/react-tinacms-editor/README copy.md, packages/react-tinacms-editor/README.md, packages/react-tinacms-github/README.md
=> Package README Updates

dangerfile.ts, packages/react-tinacms-github/src/form/useGithubFileForm.ts
=> Danger readme check

ROADMAP.md
=> typo: fix date in Cycle 2 table

packages/react-tinacms-editor/src/components/EditorModeMenu/index.tsx, packages/react-tinacms-editor/src/components/MenuHelpers/MenuButton.tsx, packages/react-tinacms-editor/src/components/MenuHelpers/MenuDropdown.tsx, packages/react-tinacms-editor/src/components/MenuHelpers/MenuOption.tsx, packages/react-tinacms-editor/src/components/MenuHelpers/commandControl.tsx, packages/react-tinacms-editor/src/components/MenuHelpers/markControl.tsx, packages/react-tinacms-editor/src/plugins/Block/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/plugins/Block/Menu/blockTool.tsx, packages/react-tinacms-editor/src/plugins/CodeBlock/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/plugins/History/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/plugins/Image/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/plugins/Inline/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/plugins/Link/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/plugins/List/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/utils.ts
Adding tooltip with keyboard shortcut information:
=> feat: tooltips for menubar options

packages/@tinacms/react-sidebar/src/components/Sidebar.tsx, packages/tinacms/src/components/TinaProvider.test.tsx, packages/tinacms/src/components/TinaProvider.tsx
=> fix: enabling CMS does not remount children

packages/react-tinacms-inline/src/fields/inline-text-field.tsx
example
```html
<h1>
<InlineText name="thisIsnotHEre" placeholder="text" />
</h1>
```
=> feat(react-tinacms-inline): InlineText now accepts a placeholder prop

packages/demo-gatsby/gatsby-config.js, packages/demo-gatsby/src/templates/blog-post.js, packages/react-tinacms-editor/README.md, packages/react-tinacms-editor/src/components/ProsemirrorEditor/utils/buildEditorState.ts, packages/react-tinacms-editor/src/plugins/Image/nodeView.ts, packages/react-tinacms-editor/src/plugins/Image/plugin.ts, packages/react-tinacms-editor/src/types.ts
previewUrl prop now supports async functions.
This is to make the props of the WYSIWYG more consistent with InlineImage prop
=> feat: wysiwyg async preview src

.github/workflows/build-test-lint.yml, .github/workflows/master.yml
on master build for all OS
This should greatly speed up the time for PR builds to finish
=> build: only build for ubuntu on PRs

package-lock.json, packages/tinacms/package.json
Product is neat but immature. Currently doesn't provide enough value for us to get past the slightly "icky" feeling.
=> chore: remove scarf

packages/react-tinacms-github/src/github-error/GithubErrorModal.tsx, packages/react-tinacms-github/src/github-error/github-interpeter.ts
This case checks all the reasons there may have been a 404:
- Unauthorized
- Private Repo => Cancel
- Missing Fork => Create Fork or Cancel
- Missing Branch => Switch to base branch (i.e. master)
- Missing File => Switch to base branch
Each of those have their own custom text
=> react-tinacms-github: improve error handling around 404s

packages/demo-next/pages/index.js, packages/demo-next/pages/info.js
This demo was using outdated form helpers
=> Updates `demo-next`

packages/react-tinacms-editor/src/components/MenuHelpers/markControl.tsx, packages/react-tinacms-editor/src/plugins/Common/keymap.ts, packages/react-tinacms-editor/src/plugins/Link/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/plugins/Link/Popups/Form.tsx, packages/react-tinacms-editor/src/plugins/Link/commands/index.test.ts, packages/react-tinacms-editor/src/plugins/Link/commands/index.ts, packages/react-tinacms-editor/src/plugins/Link/plugin.ts, packages/react-tinacms-editor/src/plugins/Table/commands/index.ts
@DirtyF : the pR fixes 2 issues that we discussed:
1. as table is created focus is set to first cell in it
2. link modal does not open as link is clicked but only after link menu option is clicked
=> fix: table and link focus

packages/@tinacms/fields/src/plugins/ImageFieldPlugin.tsx, packages/@tinacms/media/src/media.ts, packages/react-tinacms-editor/src/tinacms-inline/inline-wysiwyg.tsx, packages/react-tinacms-inline/src/fields/inline-image-field.tsx
It just delegates all actions to the media store.
Future work will have it dispatch events.
=> Media Manager adheres to the MediaStore interface

package-lock.json, packages/@tinacms/alerts/src/alerts.ts, packages/@tinacms/forms/src/form.ts, packages/demo-next/pages/_app.js, packages/react-tinacms-github/README.md, packages/react-tinacms-github/package.json, packages/react-tinacms-github/src/events.ts, packages/react-tinacms-github/src/form/useGithubFileForm.ts, packages/react-tinacms-github/src/github-client/GithubFile.ts, packages/react-tinacms-github/src/github-client/github-client.ts, packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx, packages/react-tinacms-github/src/github-error/GithubErrorModal.tsx, packages/react-tinacms-github/src/github-error/github-interpeter.ts, packages/react-tinacms-github/src/toolbar-plugins/BranchSwitcherPlugin.tsx, packages/tinacms/src/tina-cms.ts
This PR implements [RFC 0010](https://github.com/tinacms/rfcs/blob/master/0011-mapping-events-to-alerts.md).
It also refactors `react-tinacms-github` to use this new API
=> Mapping Events to Alerts

packages/@tinacms/react-modals/src/FullscreenModal.tsx, packages/tinacms/src/components/media/breadcrumb.tsx, packages/tinacms/src/components/media/media-item.tsx, packages/tinacms/src/components/media/media-manager.tsx, packages/tinacms/src/plugins/screens/media-manager-screen.tsx
- adds visual feedback when dragging a file onto the dropzone
- swaps out the screen plugin icon
- the fullscreen modal goes 100% width on screens < 720px
=> Media Manager style updates

packages/react-tinacms-github/src/github-client/github-client.ts, packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx, packages/react-tinacms-github/src/github-error/github-interpeter.ts, packages/react-tinacms-github/src/toolbar-plugins/BranchSwitcherPlugin.tsx
=> Fix double login

packages/tinacms/src/components/media/breadcrumb.tsx, packages/tinacms/src/components/media/media-item.tsx, packages/tinacms/src/components/media/media-manager.tsx
=> style(tinacms): reset media breadcrumb button style

packages/@tinacms/api-git/src/repo.ts, packages/@tinacms/api-git/src/router.ts, packages/@tinacms/api-git/src/utils/paths.ts, packages/@tinacms/core/src/media.ts, packages/@tinacms/fields/src/plugins/ImageFieldPlugin.tsx, packages/@tinacms/git-client/src/git-client.ts, packages/@tinacms/git-client/src/git-media-store.ts, packages/demo-next/pages/blocks.tsx, packages/react-tinacms-inline/src/fields/inline-image/editable-image.tsx, packages/tinacms/src/components/media/breadcrumb.tsx
=> Git media store

packages/tinacms/src/components/media/breadcrumb.tsx, packages/tinacms/src/components/media/media-item.tsx, packages/tinacms/src/components/media/media-manager.tsx
=> Media mgr style tweaks

packages/react-tinacms-github/src/github-client/github-client.ts
=> Make default commit message configurable

packages/react-tinacms-github/src/github-media-store/index.ts
=> chore(react-tinacms-github): show previewSrc for svg in list

packages/@tinacms/core/src/media-store.default.ts, packages/@tinacms/core/src/media.ts, packages/tinacms/src/components/media/media-manager.tsx
=> Media UI Edgecases

packages/demo-next/next-git-media-store.js
=> chore(demo-next): nextGitMediaStore can preview more image types

ROADMAP.md
=> Update ROADMAP.md with cycle 3

packages/react-tinacms-inline/src/fields/inline-image/dropzone-wrapper.tsx, packages/react-tinacms-inline/src/fields/inline-image/inline-image-upload.tsx, packages/tinacms/src/components/media/media-manager.tsx
I went to style the inline image placeholder and noticed that the placeholder wasn't set up to open the media manager or accept images on drop, so I fixed that as well.
=> Inline image placeholder updates

packages/@tinacms/react-core/src/use-cms-event.ts, packages/react-tinacms-github/src/github-editing-context/TinacmsGithubProvider.tsx, packages/react-tinacms-strapi/src/strapi-provider.tsx, packages/tinacms/src/react-tinacms/index.ts
=> feat: add a useCMSEvent hook

packages/react-tinacms-editor/src/tinacms-inline/inline-wysiwyg.tsx, packages/react-tinacms-inline/src/fields/inline-text-field.tsx, packages/react-tinacms-inline/src/fields/inline-textarea-field.tsx
=> fix(react-tinacms-inline): some fields were mis-handling focus

packages/react-tinacms-editor/README.md, packages/react-tinacms-editor/editor-docs/README.md
Also copied over some media docs updates.
=> docs(react-tinacms-editor): tweaks contributing docs

packages/gatsby-tinacms-json/src/create-json-plugin.ts, packages/gatsby-tinacms-remark/src/remark-creator-plugin.ts
=> Commit newly created files

packages/@tinacms/fields/src/plugins/ImageFieldPlugin.tsx, packages/gatsby-tinacms-json/src/create-json-plugin.ts, packages/gatsby-tinacms-remark/src/remark-creator-plugin.ts, packages/react-tinacms-editor/src/components/Wysiwyg/index.tsx, packages/react-tinacms-editor/src/types.ts, packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/block.ts, packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx, packages/react-tinacms-inline/src/fields/inline-image/editable-image.tsx, packages/react-tinacms-inline/src/fields/inline-image/inline-image-field.tsx
=> feat(react-tinacms-inline): block components are given their name

packages/react-tinacms-editor/src/components/ProsemirrorEditor/Menubar/index.tsx, packages/react-tinacms-editor/src/components/ProsemirrorEditor/index.tsx, packages/react-tinacms-editor/src/components/Wysiwyg/index.tsx, packages/react-tinacms-editor/src/plugins/Image/Menu/ProsemirrorMenu.tsx, packages/react-tinacms-editor/src/types.ts
=> refactor(react-tinacms-editor): menu is passed mediaDir string

packages/react-tinacms-github/src/github-client/github-client.ts
=> fix(react-tinacms-github): dispatch event on delete failure

packages/react-tinacms-editor/src/components/ProsemirrorEditor/Menubar/index.tsx, packages/react-tinacms-editor/src/components/ProsemirrorEditor/index.tsx, packages/react-tinacms-editor/src/plugins/Image/Menu/ProsemirrorMenu.tsx
previewSrc is generated by the nodeView and should not mutate content
=> chore(react-tinacms-editor): don't insert previewSrc into content body

packages/react-tinacms-github/README.md
=> docs(react-tinacms-github): add docs on supported image formats

packages/react-tinacms-editor/package.json
=> fix(react-tinacms-editor): correct typedef path

packages/next-tinacms-github/package.json, packages/next-tinacms-json/package.json
fixes remaining issues discovered in #1573
=> Fix paths to build artifacts

packages/react-tinacms-inline/src/inline-settings.tsx
Export `SettingsModal` outside package so we can use it for various use cases. Also add `title` prop, optional and falling back to `Settings` text.
Fixes #1583
=> feat(react-tinacms-inline): Export SettingsModal

packages/react-tinacms-editor/package.json
=> chore(react-tinacms-editor): adds react-tinacms-inline as peerDep

packages/@tinacms/fields/src/components/Toggle.tsx
Closes #1579.
I was not able to test this locally as I think `npm run bootstrap && npm run build` was pulling the latest from the published packages and not from my changes.
So if you could give me some pointers on how to test this PR locally, i wouldn't mind doing.
Also, I didn't see any unit tests written for the component so I also haven't tested my changes. If you'd like me to write test, let me know.
=> Add true/false toggle labels to Toggle plugin

packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
proposed fix for #1394 
may incidentally address #1368 and #1398 
we should investigate all these cases to see what improves and what doesn't
=> fix(react-tinacms-inline): better control InlineBlocks rerenders

packages/@tinacms/fields/src/components/Toggle.tsx, packages/demo-next/pages/nesting.tsx
[Original PR](https://github.com/tinacms/tinacms/pull/1585) by @canrozanes
---
=> Feat(@tinacms/fields): add labels to toggle field

packages/@tinacms/fields/src/plugins/ImageFieldPlugin.tsx, packages/demo-gatsby/src/templates/blog-post.js, packages/demo-next/pages/info.js
=> Fix(@tinacms/fields): onClear resets the image input

packages/demo-next/pages/_app.js, packages/demo-next/plugins/CustomPaginator.tsx, packages/tinacms/src/components/media/index.ts, packages/tinacms/src/components/media/media-manager.tsx, packages/tinacms/src/components/media/pagination.tsx, packages/tinacms/src/index.ts, packages/tinacms/src/tina-cms.ts
Experimental.
`custom-paginator.tsx`:
```tsx
import { MediaPaginatorPlugin } from 'tinacms'
const CustomPaginatorComponent = ({ list, setOffset }) => {
const numPerPage = list.limit
const currentPage = Math.floor(list.offset / numPerPage)
const numPages = Math.ceil(list.totalCount / numPerPage)
return (
<ol className="paginator">
{[...Array(numPages)].map((_, index) => {
return (
<li key={index} className={index == currentPage ? 'current' : ''}>
<button onClick={() => setOffset(numPerPage * index)}>
{index + 1}
</button>
</li>
)
})}
</ol>
)
}
export const CustomPaginatorPlugin: MediaPaginatorPlugin = {
__type: 'media:ui',
name: 'paginator',
Component: CustomPaginatorComponent,
}
```
`_app.tsx`:
```tsx
import { CustomPaginatorPlugin } from './custom-paginator'
const cms = new TinaCMS({ …
```
=> Pluggable media pagination

packages/react-tinacms-inline/src/styles/focus-ring.tsx
=> chore(react-tinacms-inline): add min-height to focus ring

packages/tinacms/src/components/media/breadcrumb.tsx, packages/tinacms/src/components/media/media-manager.tsx
Addresses some concerns from #1589
=> feat(tinacms): media manager dropzone accepts multiple files for upload

CONTRIBUTING.md, packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
=> Support `defaultItem` as a function inside `add-block-menu.tsx`

packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
=> Fix(react-tinacms-inline): add block `defaultItem` accepts function

packages/react-tinacms-github/src/github-client/github-client.ts
=> fix(react-tinacms-github): restore original functionality for github:branch:checkout

packages/next-tinacms-github/README.md
Just adds a bit more context based on my confusing points on recently setting this up.
=> docs: update NextGithubMediaStore docs

packages/react-tinacms-github/src/github-client/github-client.ts
fixes https://github.com/tinacms/tina-starter-blocks/issues/17
=> chore(react-tinacms-github): fix conditional for firing reload-form-data

packages/next-tinacms-github/README.md
=> (docs): correct example of getGithubFile usage with incorrect parameters

README.md
😢 we're gonna miss you @kendallstrautman
=> docs: update maintainers

.github/CODEOWNERS
=> chore: fix CODEOWNERS syntax

packages/@tinacms/react-sidebar/src/components/Sidebar.tsx
Reverts tinacms/tinacms#1690
Fix #1713
=> Revert "fix(@tinacms/react-sidebar): fixed site elements relative to SiteWrapper"

packages/react-tinacms-inline/package.json
=> fix(react-tinacms-inline): dep constraint syntax

packages/react-tinacms-date/README.md
Following #1717 
@all-contributors please add @notjosh for docs
=> docs: typo

packages/react-tinacms-editor/README.md
=> docs: Add cleanup function to 'useEffect' example of dynamic imports.

packages/react-tinacms-editor/README.md
The code example introduced docs update in #1720 fails if the hook runs before state is ready. This revision will check to see if the editor was loaded before trying to unload it.
=> fix docs: check if cleanup is needed before cleaning up

dangerfile.ts
=> chore(build): use `head` content ref if PR is a draft

packages/react-tinacms-github/src/github-media-store/index.ts
=> fix: typo in GithubUploadResponse type

CONTRIBUTING.md
=> docs(contributing): add note about CLA

CONTRIBUTING.md
Current active LTS version is v14.
=> docs: link to current active LTS

CONTRIBUTING.md
=> Added reason for CLA

packages/react-tinacms-github/src/components/ActionableModal.tsx
Fix missing unique "key" prop in modal actions.
Also replace deprecated ModalPopup with PopupModal.
Closes #1557
=> fix(react-tinacms-github): fix missing unique "key" prop in modal actions

packages/tinacms/src/components/TinaCMSProvider.test.tsx, packages/tinacms/src/components/TinaCMSProvider.tsx, packages/tinacms/src/components/TinaProvider.tsx, packages/tinacms/src/components/TinaUI.test.tsx, packages/tinacms/src/components/TinaUI.tsx, packages/tinacms/src/index.ts
https://github.com/tinacms/rfcs/pull/15
=> feat(tinacms): export independent components for CMS provider and UI

packages/next-tinacms-markdown/src/use-markdown-form.ts
=> fix(next-tinacms-markdown): Fixes fileRelativePath for useMarkdownForm

CONTRIBUTING.md, package-lock.json, package.json, scripts/nuke.sh, scripts/prerelease.sh, scripts/release.sh
=> chore: ensure lerna's local version is used in all scripts

packages/react-tinacms-strapi/README.md
Easy navigation and easy reading for others
=> Fix broken url in docs

scripts/prerelease.sh, scripts/release.sh
=> chore(build): fix lerna commands in release scripts

dangerfile.ts
=> fix danger script

packages/react-tinacms-inline/README.md, packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
Solves: https://community.tinacms.org/t/get-block-count-from-outside-inlineblocks/596
=> feat(react-tinacms-inline): InlineBlocks children

packages/@tinacms/auth/readme.md, packages/@tinacms/auth/src/index.ts, packages/next-tinacms-cloudinary/src/cloudinary-tina-cloud-media-store.ts, packages/tinacms/src/auth/authenticate.ts, packages/tinacms/src/client/index.ts, packages/tinacms/src/utils/index.ts
Copied from https://github.com/tinacms/tina-graphql-gateway/pull/285
=> Use new auth endpoints for Tina cloud

packages/@tinacms/cli/src/cmds/start-server/server.ts
=> fixed altair endpoint

packages/@tinacms/cli/src/cmds/compile/defaultSchema.ts, packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
Fixes https://github.com/tinacms/tinacms/issues/1894
=> updated tina init to use primitive types work

.changeset/config.json
=> set `main` as base branch for changesets

.github/workflows/publish.yml, CONTRIBUTING.md, package.json
This sets up the action that publishes `beta` versions and makes a PR for the release like this PR https://github.com/tinacms/tina-graphql-gateway/pull/358
=> Add publish workflow

.changeset/witty-plums-dance.md, packages/@tinacms/cli/src/cmds/compile/defaultSchema.ts, packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
=> updated generate files from CLI

.changeset/little-suns-ring.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/NoFormsPlaceHolder.tsx
=> fix: link to forms guide

.changeset/strong-grapes-wonder.md, packages/tinacms/src/hooks/use-graphql-forms.tsx
Fixed issue found here: https://github.com/tinacms/tina-cloud-starter/pull/136
=> fixed deps in useGraphql forms

packages/@tinacms/graphql/src/index.ts, packages/@tinacms/graphql/src/primitives/database/github.ts
We're looking to extend the GithubBridge Class in the cloud repo.
We can't currently override the instance methods, as they are currently properties
https://stackoverflow.com/questions/53997107/allow-subclass-to-override-with-either-a-function-property-or-a-method
I also added a few extra types to the export.
=> GitHub extendable

.github/workflows/build-test-lint.yml
Reverts tinacms/tinacms#1961
This did not work as hoped so let's clean it up
=> Revert "trigger PR build on pushes to changeset-release branches"

.changeset/rotten-items-bake.md, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
This PR looks at the users `_app.{js,tsx}` file and adds all css imports that where in it to the generate file.
=> added regex to add css files to generated file

packages/@tinacms/graphql/src/primitives/database/bridge.ts, packages/@tinacms/graphql/src/primitives/spec/setup.ts
Continuation of https://github.com/tinacms/tinacms/pull/1950
I forgot to update the Bridge interface (and other backends) to use methods instead of props, so that they can be overridden.
=> Extendable GitHub w/ interface

.changeset/early-gorillas-poke.md, packages/@tinacms/graphql/src/primitives/database/index.ts, packages/@tinacms/graphql/src/primitives/resolver/index.ts, packages/@tinacms/graphql/src/primitives/schema/index.ts
Fix issue where the `isBody` field wasn't properly removing that value from frontmatter. Ensure that the field is not treating any differently for JSON format
Closes https://github.com/tinacms/tinacms/issues/1955
=> Fix issue with _body being written to frontmatter

.changeset/fuzzy-chicken-sniff.md
Add a changeset for #2003, as it appears to beta release wasn't triggered.
First time working with this changeset, so let me know if this isn't the correct procedure!
=> chore: add changeset

.changeset/seven-items-move.md, packages/@tinacms/graphql/src/primitives/resolver/index.ts, packages/@tinacms/graphql/src/primitives/schema/index.ts
Fixed issue where you could not save a file on windows
=> fixed windows saving issue

.changeset/silent-bees-brush.md, examples/tina-cloud-starter/components/placeholder.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/NoFormsPlaceHolder.tsx
James accurately pointed out that the link for the `NoFormsPlaceholder` was now not as relevant.
Updated to point to our page on Content Modelling.
Closes #2007
=> 2007 - Updates Placeholder Links

.changeset/fluffy-plums-smell.md, examples/tina-cloud-starter/.tina/schema.ts, packages/@tinacms/cli/src/index.ts, packages/@tinacms/graphql/src/index.ts, packages/@tinacms/graphql/src/primitives/types.ts
Closes https://github.com/tinacms/tinacms/issues/1947
=> Improve exported types

README.md
Figured myself and @jbevis should be added to the maintainer list?
@jbevis is linking to GitHub Ok? We cal also link to your twitter
=> updated maintainer list

.changeset/kind-years-learn.md, packages/@tinacms/cli/src/cmds/start-server/index.ts
=> feat(tinacms/cli): add simpler err message

packages/next-tinacms-github/README.md
=> Add missing comma in docs

.changeset/modern-nails-sort.md, examples/tina-cloud-starter/pages/_app.js, packages/tinacms/src/auth/TinaCloudProvider.tsx, packages/tinacms/src/tina-cms.tsx
Fixes https://github.com/tinacms/tinacms/issues/2035
=> fixed media bundle

packages/@tinacms/graphql/src/primitives/index.ts
I fixed the types that where causing  a build error @jbevis
=> fixed types

packages/@tinacms/graphql/src/primitives/resolve.ts
Not entirely sure when or why it was omitted, but, while `getPostsDocument`, etc, return `mutationInfo`, in a pair programming discussion, we noticed `getDocument` does not.
Solution is pretty simple - slightly modify `buildMutationPath` to not require `collection` and carry that through the function.
Closes #2118
=> 2118 - Adds `mutationInfo` for `getDocument`

.changeset/twenty-kangaroos-repeat.md, packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
Updated marked and updated CND to pin at 4.0.0
=> updated cli generated files

.changeset/short-ways-tan.md, examples/tina-cloud-starter/.tina/__generated__/_graphql.json, examples/tina-cloud-starter/.tina/__generated__/_schema.json, examples/tina-cloud-starter/pages/_app.tsx, packages/tinacms/src/auth/TinaCloudProvider.tsx, packages/tinacms/src/tina-cms.tsx
update media store to load only when in edit mode
=> update media store to load only when in edit mode

.changeset/little-points-change.md
`tina-cloud-starter` is not published and should not be part of the `changeset` for #2181.
=> 2181 - Removes unpublished package from changeset

dangerfile.ts
Needs to be merged to #2218 will pass CI checks
=> updated regex to include a reject experimental-examples folder

.changeset/blue-steaks-sparkle.md, packages/tinacms/src/admin/README.md
I anticipate this becoming a whole section in the documentation, but for now, this README seeks to describe how to set up `TinaAdmin` in a brand new or existing `TinaCMS`-enabled site.
I also added "Bonus" sections related to the `tina-admin` flag and `RouteMappingPlugin` for those interested in setting those features up.
Closes #2211
=> 2211 - Adds README for `TinaAdmin`

.changeset/three-lizards-wash.md, packages/@tinacms/cli/src/cmds/compile/index.ts
the lingering `schema.json` was causing issues
=> Reset entire __generated__ folder on re-compile

.changeset/shiny-teachers-attack.md, experimental-examples/tina-cloud-starter/pages/_app.tsx, packages/tinacms/src/hooks/use-graphql-forms.tsx
=> Add ability to control plugin layout for global plugins from formify

packages/@tinacms/toolkit/src/packages/fields/plugins/GroupFieldPlugin.tsx
Removes more tailwind classes.
=> fix: replace tailwind classes in panel body

.changeset/bright-donuts-shake.md, packages/tinacms/src/admin/components/AuthTemplate.tsx, packages/tinacms/src/admin/components/Sidebar.tsx, packages/tinacms/src/admin/index.tsx, packages/tinacms/src/admin/pages/LogoutPage.tsx, yarn.lock
From a conversation during office hours, we decided to rework `TinaAdmin` to provide the same login/logout functionality that the old `pages/admin/[...slug].tsx` has and enable us to replace that file with the new `pages/admin/[...tina].tsx` that contains the import of `TinaAdmin`.
With this in place, a user can turn on and off `TinaAdmin`'s dashboard, content creator, etc. through the `tina-admin` flag without also having to do any file manipulation.
It also simplifies what the CLI needs to do dramatically.
https://www.loom.com/share/69f679fb41bc47108574e241fc81710f
Closes #2258
=> 2258 - Swaps starter's old `admin` for the new one

dangerfile.ts
=> Revert "remove regexp from danger file"

dangerfile.ts
=> update regexp to include packages/create-tina-app/examples

.changeset/honest-buses-boil.md, packages/tinacms/src/client/index.ts
Improves UX for user's who have expired tokens https://github.com/tinacms/tinacms/issues/2179
=> Throw when Tina Cloud responds with non 200 code

examples/basic/pages/posts/[slug].js, packages/create-tina-app/examples/basic/pages/posts/[slug].js
Intended to change getStaticPropsForTina to staticRequest, also fixed the build for the basic starter
fixes #2296 
Sorry @logan-anderson, just noticed you self-assigned https://github.com/tinacms/tinacms/issues/2296 so I hope I didn't step on your toes too much
=> Fix basic starter

.changeset/stale-seals-rhyme.md, packages/@tinacms/graphql/src/mdx/stringify.ts
fixes #2323 
As stated I am unsure how to fix underline and strikethrough support as both don't seem to be supported in standard markdown but would need a plugin or something.
=> Fix 2323 enable bold and italic in plate editor

yarn.lock
should fix the yarn lock file so e2e tests go through and unblock publishing a new package on npm
will fix broken github action runs:
https://github.com/tinacms/tinacms/runs/4510560803?check_suite_focus=true
https://github.com/tinacms/tinacms/runs/4511212209?check_suite_focus=true
see https://stackoverflow.com/questions/67062308/getting-yn0028-the-lockfile-would-have-been-modified-by-this-install-which-is-e
=> chore(tinacms): fix yarn lock file

.changeset/gold-pets-return.md, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/config.ts
Closes https://github.com/tinacms/tinacms/issues/2332
=> Remove ability to tab in rich-text editing

.changeset/loud-bananas-rhyme.md, experimental-examples/tina-cloud-starter/.tina/__generated__/_schema.json, experimental-examples/tina-cloud-starter/content/posts/anotherPost.mdx, packages/@tinacms/graphql/src/resolver/index.ts
Fixes https://github.com/tinacms/tinacms/issues/2165
=> Added delete button to image field

.changeset/silver-pandas-hunt.md, packages/tinacms/src/tina-cms.tsx
=> add "switch to default branch" recover option to error boundary

.changeset/mighty-sheep-search.md, examples/basic/.tina/__generated__/_schema.json, experimental-examples/tina-cloud-starter/.tina/__generated__/_schema.json, packages/next-tinacms-cloudinary/src/handlers.ts
=> fixed issue where folder could not have spaces in its name

.changeset/clever-beds-reflect.md, packages/tinacms/src/tina-cms.tsx
Noticed that the types where not building on `main` so I fixed it.
=> fixed ts types

.changeset/fair-pots-cry.md, experimental-examples/tina-cloud-starter/.tina/__generated__/_schema.json, packages/@tinacms/cli/src/cmds/start-server/index.ts
@jeffsee55  this "Fixes" https://github.com/tinacms/tinacms/issues/2363 but I am not sure if this is the correct way to fix it.
=> rebuild database every schema change

cypress/integration/kitchen-sink/sidebar.spec.js, experimental-examples/kitchen-sink/.tina/__generated__/_graphql.json, experimental-examples/kitchen-sink/.tina/__generated__/schema.gql, experimental-examples/kitchen-sink/.tina/__generated__/types.ts, experimental-examples/kitchen-sink/content/page/home.mdx
=> Reset state with graphQL request instead of UI

.all-contributorsrc
=> Update .all-contributorsrc adding xaviemirmon

packages/create-tina-app/src/index.ts
=> fix: Fix typos in cli

package.json
Pull before runing git push on publish action
https://github.com/tinacms/tinacms/runs/4926325693?check_suite_focus=true
=> Fix broken publish action

.changeset/calm-trainers-speak.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/FormList.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/SidebarBody.tsx
Fixes #2505 "Tina UI issues when multiple forms"
Replaces existing styled components with new tailwind components. They're essentially styled like groups. 
List:
Header:
=> style: multiform header and list

.changeset/modern-balloons-fail.md, packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
Implement useTina in CLI
(quickly tested this using a pr deploy)
=> Implement useTina in CLI

packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx
Fixes issue in barebones starter.
=> style: floating nav position top fix

.changeset/honest-badgers-prove.md, packages/@tinacms/toolkit/src/packages/fields/plugins/BlocksFieldPlugin.tsx
- Displays filter input in DDL when there's more than 6 blocks.
- Block lists scrolls after ~10 blocks.
=> Block Selector Improvements

.changeset/brave-planes-boil.md, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/wrapFieldWithMeta.tsx, packages/react-tinacms-editor/src/tinacms-plugins/MarkdownFieldPlugin.tsx
=> restore activefieldindicator behavior

.changeset/poor-actors-move.md, packages/tinacms/src/admin/components/Page.tsx
Fixes scrolling in admin list page when content is overflowing the view wrapper.
Closes #2543
=> Admin Scrolling Fix

.changeset/wet-steaks-remain.md, packages/next-tinacms-cloudinary/src/handlers.ts
Fixed a small type error in cloudinary package.
=> fix: type error

.changeset/silver-buckets-wait.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/sidebar.ts
Fixing sidebar position so it pulls from the CMS object if available.
=> Fix sidebar overlay behaviour

.changeset/wicked-experts-vanish.md, packages/@tinacms/cli/src/cmds/init/index.ts
Helping @Enigmatical complete the work of supporting static export by updating the admin path in the CLI
I am going to deploy this PR and test it with npx before merging.
Part of the fix for #2542
=> update admin path in CLI

.changeset/silent-keys-refuse.md, examples/basic/.tina/schema.ts, packages/tinacms/src/index.ts, packages/tinacms/src/tina-cms.tsx
Adds defineConfig function so we can support type hints.
=> add define config function

.changeset/modern-years-yawn.md, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx
=> 2635 - Document creating/updating success messaging

.changeset/olive-experts-turn.md, packages/next-tinacms-cloudinary/src/errors.ts
Fix link URL in "Learn More" link
=> Fix-broken-cloudinary-link

packages/@tinacms/toolkit/src/packages/form-builder/fields-builder.tsx
Fixes #2660
I've attached a screen recording below to show how it works now. It's a little clunky but I don't think there's a good way to indicate when a plugin is loading async (there's no way for the system to know about it.)
https://user-images.githubusercontent.com/15221702/157288555-24b2c06a-df43-45ac-b2db-87e18a2845e7.mov
=> rebuild field UI when field plugins are registered

.github/ISSUE_TEMPLATE/feature-request.md
Use issue template used in the product roadmap for feature requests
=> Update feature-request issue template

.changeset/eleven-walls-occur.md, packages/@tinacms/cli/src/cmds/compile/defaultSchema.ts
Fix return type on cmsCallback codegen
=> Fix-cmscallback-return

.changeset/nine-flowers-yell.md, examples/basic/.tina/__generated__/_graphql.json, examples/basic/.tina/__generated__/_schema.json, examples/basic/.tina/__generated__/schema.gql, examples/basic/.tina/__generated__/types.ts, examples/basic/.tina/schema.js, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx
=> use schema in admin

.changeset/fuzzy-eels-share.md, packages/@tinacms/toolkit/src/packages/fields/components/TextField.tsx, packages/@tinacms/toolkit/src/packages/react-modals/Modal/ModalOverlay.tsx, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchSwitcher.tsx
This improves clarity between filtering and branch creation by breaking out the two functions into their own  UI.
=> Improve Branch Switcher UI

.changeset/happy-vans-obey.md, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/cli/src/cmds/init/setup-files/index.ts
Closes https://github.com/tinacms/tinacms/issues/2642
Let me know if you have any tweaks @jamespohalloran
=> Cli init updates

.changeset/thirty-dots-repeat.md, experimental-examples/unit-test-example/package.json, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/updated/plate/plugins/create-mdx-plugins/component.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/updated/plate/plugins/ui/toolbar/overflow-menu.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/updated/plate/plugins/ui/toolbar/toolbar-item.tsx
Fixes https://github.com/tinacms/tinacms/issues/2849
=> Fix issue where popover item onMouseDown wasn't triggering

.changeset/flat-suns-argue.md, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/ListFieldPlugin.tsx
This improves the string list field UI by sharing UI with the group list field.
Old UI:
New UI:
=> List Field UI

.changeset/sharp-brooms-mate.md, packages/@tinacms/graphql/src/database/index.ts
This adds an optional indexStatusCallback prop to the Database configuration. If it is configured, the callback will receive index status events that can be used for keeping track of when an indexing process is in progress
=> feat: #153: index status callback

.changeset/short-socks-complain.md, packages/@tinacms/graphql/src/database/index.ts
Fixes issue where documents could not be deleted locally on windows
=> fix: delete documents on windows

.changeset/gentle-games-heal.md, experimental-examples/tina-cloud-starter/.tina/__generated__/types.ts, experimental-examples/tina-cloud-starter/.tina/client.ts, experimental-examples/tina-cloud-starter/pages/[filename].tsx, experimental-examples/tina-cloud-starter/pages/posts.tsx, experimental-examples/tina-cloud-starter/pages/posts/[filename].tsx, packages/@tinacms/cli/src/cmds/compile/index.ts, packages/@tinacms/cli/src/codegen/plugin.ts, packages/tinacms/src/tina-cms.tsx, packages/tinacms/src/unifiedClient/index.ts
=> update sdk so it works with unified client

.changeset/quick-teachers-grow.md, packages/@tinacms/graphql/src/resolve.ts, packages/@tinacms/graphql/src/resolver/index.ts
=> Always use query when data layer is enabled.

.github/workflows/e2e-dev.yml, package.json
Try running `yarn dev` in CI as well as `yarn start`
=> run in dev

CHANGELOG.md, README.md, packages/tinacms/CHANGELOG.md
update readme to make discord help more prominent; update changelogs to refer to each other so they are easily found from each other
=> Readme and Changelog minor updates for more clarity

.changeset/new-fishes-glow.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx
=> Fix Collection List Page Delete Modal

packages/@tinacms/datalayer/src/database/bridge/isomorphic.ts
Fixes an issue when pathToTina is specified as rootPath
=> fix: relativePath calculation

.changeset/late-jeans-eat.md, packages/@tinacms/cli/src/cmds/init/index.ts
Fixes issue where had a src and pages dir for tina init.
=> fix src issue

.changeset/quiet-moose-return.md, experimental-examples/tina-cloud-starter/.tina/__generated__/types.ts, experimental-examples/tina-cloud-starter/.tina/client.ts, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/cli/src/codegen/plugin.ts, packages/tinacms/src/unifiedClient/index.ts
New error message in the client that links to the FAQ and also throws an error message when a non 200 status code is returned.
=> better errors in the client

.changeset/slow-swans-brake.md, packages/@tinacms/schema-tools/src/validate/fields.ts
=> Throw an error message when name contains spaces

.changeset/famous-hornets-trade.md, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/toolkit/src/packages/fields/components/Select.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/SelectFieldPlugin.tsx, packages/tinacms/src/admin/api.ts, packages/tinacms/src/admin/components/GetCollection.tsx, packages/tinacms/src/admin/components/Page.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx
This adds the ability to sort in the CMS
closes #2774
=> Sort by any field in cms

.changeset/weak-horses-yell.md, packages/tinacms/src/hooks/formify/formify.ts
Closes https://github.com/tinacms/tinacms/issues/2929
=> Specify inlineFragment nodes to show in sidebar

.changeset/sour-olives-refuse.md, packages/@tinacms/graphql/src/builder/index.ts
Closes https://github.com/tinacms/tinacms/issues/3089
=> Fix issue where fields with an empty templates array generated an invalid GraphQL filter

.changeset/mean-candles-walk.md, packages/@tinacms/toolkit/src/packages/fields/components/ImageUpload/ImageUpload.tsx
=> set max-height to imageUpload button

.changeset/chatty-cycles-watch.md, packages/create-tina-app/src/util/fileUtil.ts
=> create-tina-app Windows fix

packages/next-tinacms-dos/package.json, packages/next-tinacms-s3/package.json, pnpm-lock.yaml
Upgrade next dep, as it has a security vulnerability: https://github.com/tinacms/tinacms/security/dependabot/239
=> chore: upgrade next deps

.changeset/little-bats-rule.md, packages/@tinacms/graphql/src/index.ts
export functions needed for backend indexing
=> Fix export indxing fns

.changeset/calm-bees-buy.md, packages/@tinacms/toolkit/src/packages/fields/plugins/wrapFieldWithMeta.tsx, packages/@tinacms/toolkit/src/packages/form-builder/fields-builder.tsx
=> Fix rich text dropdown overlap issue

CONTRIBUTING.md
The `pnpm install` step was missing in the instructions
- Add note about NVM
- Add a step about installing yarn globally
The code doesn't change, so I doubt there's a need for a changeset.
Correct me if I'm wrong :)
=> update the development setup instructions

.changeset/stupid-colts-relate.md, packages/@tinacms/mdx/package.json, packages/@tinacms/toolkit/package.json, packages/next-tinacms-dos/package.json, packages/next-tinacms-s3/package.json, packages/tinacms/package.json, pnpm-lock.yaml
Updates all deps that where causing vulnerabilities
=> Remove all known vulnerabilities

.changeset/witty-cobras-turn.md, packages/@tinacms/graphql/src/ast-builder/index.ts
=> adds cursor definition to generated client

.changeset/nervous-walls-run.md, packages/@tinacms/toolkit/src/packages/fields/components/Reference/ReferenceSelect.tsx
=> Fix refernce list query

.changeset/rotten-islands-end.md, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Nav.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/SyncStatus.tsx
Fixes https://linear.app/tina/issue/ENG-560/clicking-load-more-events-closes-modal
=> Relocate Event Log Dialog

.changeset/wet-beds-whisper.md, packages/@tinacms/toolkit/src/packages/react-cloud-config/cloud-config-plugin.tsx, packages/@tinacms/toolkit/src/packages/react-cloud-config/index.ts, packages/@tinacms/toolkit/src/packages/react-cloud-config/use-cloud-config-plugin.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Nav.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/Sidebar.tsx, packages/@tinacms/toolkit/src/tina-cms.ts, packages/tinacms/src/admin/components/Sidebar.tsx, packages/tinacms/src/auth/TinaCloudProvider.tsx
=> Add link to Tina Cloud Project settings

.changeset/empty-cheetahs-refuse.md, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupFieldPlugin.tsx
=> disable tabbing PanelHeader

packages/@tinacms/toolkit/src/components/media/breadcrumb.tsx
=> Fix media breadcrumb back arrow click error

.changeset/moody-turkeys-sleep.md, packages/@tinacms/cli/src/cmds/init/static.ts
Remove styled-components from static install and fix message about next steps.
=> Remove styled-components from static install 

.changeset/soft-cups-develop.md, packages/@tinacms/toolkit/src/packages/fields/plugins/wrapFieldWithMeta.tsx, packages/@tinacms/toolkit/src/packages/form-builder/fields-builder.tsx
=> Fix rich-text dropdown overlap issue

.changeset/nervous-geese-wash.md, packages/@tinacms/cli/src/cmds/init/static.ts
Remove extra space in tina init console.log
=> Script-formatting-fix

.changeset/curly-coins-turn.md, packages/@tinacms/toolkit/src/packages/react-modals/Modal/ModalHeader.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx
=> Fix Text Truncation

.github/workflows/e2e-dev.yml, .github/workflows/e2e.yml
Update container to support vite 3.0
=> use new container

.changeset/pink-timers-knock.md, packages/@tinacms/cli/src/buildTina/attachPath.ts
=> check config.ts/tsx addition to schema.ts/tsx

.changeset/lovely-icons-listen.md, packages/next-tinacms-cloudinary/src/cloudinary-media-store.ts, packages/next-tinacms-dos/src/dos-media-store.ts, packages/next-tinacms-dos/src/handlers.ts, packages/next-tinacms-s3/src/handlers.ts, packages/next-tinacms-s3/src/s3-media-store.ts
Closes #2692
Fix ENG-63
fixes #2851
=> Fix drag'n'drop impage upload not working issue

.changeset/afraid-phones-mate.md, packages/@tinacms/cli/src/cmds/statusChecks/waitForIndexing.ts, packages/@tinacms/toolkit/src/components/media/media-manager.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx
Update couple of error messages.
=> update error message

packages/@tinacms/toolkit/src/packages/form-builder/FormBuilder.tsx
=> fix onPristineChange not calling issue

examples/basic-iframe/.tina/config.js, packages/@tinacms/mdx/src/stringify/index.ts
=> update regex to match on spaces

.changeset/polite-bugs-search.md, packages/@tinacms/cli/src/cmds/compile/index.ts
=> show a deprecation message for old schema file usage

.changeset/large-dryers-fly.md, packages/tinacms/src/edit-state.tsx, packages/tinacms/src/tina-cms.tsx
Add some console.warn's and jsdoc deprecated comments on some deprecated API's from the switch to the iframe api
=> add deprecation notices to pre-iframe apis

packages/@tinacms/cli/src/buildTina/index.ts, packages/@tinacms/cli/src/cmds/compile/index.ts, packages/@tinacms/cli/src/cmds/start-server/index.ts
Fix issue with using dev instead of local
=> fix issue with local build

.changeset/curly-fans-nail.md, packages/tinacms/src/rich-text/index.tsx
Fixes https://github.com/tinacms/tinacms/issues/3172
=> Improve types on TinaMarkdown

.changeset/many-dolphins-own.md, examples/basic-iframe/.tina/config.js, examples/kitchen-sink/.tina/config.tsx, experimental-examples/tina-cloud-starter-iframe/.tina/config.ts, packages/@tinacms/app/appFiles/src/preview.tsx, packages/@tinacms/app/src/index.ts, packages/@tinacms/cli/src/cmds/init/setup-files/config.ts, packages/@tinacms/schema-tools/src/types/SchemaTypes.ts, packages/tinacms/src/hooks/formify/spec/schema.ts, packages/tinacms/src/index.ts
Fixes https://github.com/tinacms/tinacms/pull/3318#pullrequestreview-1159913356
I also merged main back in. The only real change is to this file: https://github.com/tinacms/tinacms/pull/3336/files#diff-5798c8e5184486e9163b064c0c2316af7843399a7dc491d7ec2714266ea0018fL38
cc @jeffsee55
=> Dont restart vite logan

packages/@tinacms/toolkit/src/packages/react-sidebar/components/Nav.tsx
=> fix logging out not working issue

packages/@tinacms/cli/bin/tinacms
=> Display an error when node version < 14.18

.changeset/ten-cows-laugh.md, experimental-examples/tina-cloud-starter-iframe/package.json, packages/@tinacms/app/appFiles/src/lib/machines/query-machine.ts
=> Fix console error message about multiple field nodes

.changeset/gold-bulldogs-scream.md, packages/@tinacms/graphql/src/builder/index.ts
=> Fix empty selections issue

.changeset/thick-cups-mix.md, packages/next-tinacms-cloudinary/src/cloudinary-media-store.ts, packages/next-tinacms-dos/src/dos-media-store.ts, packages/next-tinacms-s3/src/s3-media-store.ts
=> Fix accept img

.changeset/beige-penguins-cover.md, packages/@tinacms/toolkit/src/packages/fields/components/Reference/ReferenceSelect.tsx
=> Show title for reference fields

packages/@tinacms/mdx/package.json, packages/@tinacms/mdx/src/parse/index.ts, packages/@tinacms/mdx/src/parse/remarkToPlate.ts, packages/@tinacms/mdx/src/tests/autotest/image.test.ts, packages/@tinacms/mdx/src/tests/autotest/kitchen sink.test.ts, pnpm-lock.yaml
=> Revert "Unwrap image block"

packages/tinacms/src/admin/pages/CollectionListPage.tsx
=> display subfolders in correct field

.changeset/tender-kings-march.md, packages/tinacms/src/rich-text/index.tsx
=> Enable custom component for lic in TinaMarkdown

.changeset/many-flies-arrive.md, packages/@tinacms/toolkit/src/packages/form-builder/FormBuilder.tsx, packages/@tinacms/toolkit/src/packages/form-builder/PublishForm.tsx, packages/tinacms/src/internalClient/index.ts
demo video:
[![Alt text](https://img.youtube.com/vi/CGfHarCnNtk/0.jpg)](https://www.youtube.com/watch?v=CGfHarCnNtk)
=> Implement initial create pull request / preview functionality

packages/@tinacms/toolkit/src/packages/form-builder/FormBuilder.tsx, packages/@tinacms/toolkit/src/packages/form-builder/PublishForm.tsx, packages/tinacms/src/internalClient/index.ts
CORS issue is resolved - enable indexStatus check before switching to the branch and committing
=> fix: enable index status check when creating new pull request

packages/@tinacms/toolkit/src/packages/form-builder/PublishForm.tsx
Don't wait for the full vercel deployment to finish
Also, stick the pull_number in storage so we can grab it globally later
=> dont wait for deployment

packages/@tinacms/toolkit/src/packages/form-builder/PublishForm.tsx, packages/@tinacms/toolkit/src/packages/react-sidebar/components/BranchBanner.tsx, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchSwitcher.tsx
Simple create branch modal. Trying to make it refresh the branch selector list & select the created branch using a callback, but the `createBranch` is just a placeholder.
=> Create Branch Modal

packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx
Fixes https://github.com/tinacms/tinacms/pull/3499#issuecomment-1376316884
=> default min should be 0

.changeset/kind-phones-try.md, packages/@tinacms/toolkit/src/packages/core/media.ts, packages/next-tinacms-cloudinary/src/errors.ts
=> fix broken media links

examples/basic-iframe/.tina/config.js, packages/@tinacms/schema-tools/src/types.ts, packages/tinacms/src/auth/authenticate.ts, packages/tinacms/src/internalClient/index.ts
Adds the `getToken` function to the config
=> added getToken function to the schema

.changeset/mean-dodos-appear.md, packages/@tinacms/app/appFiles/src/fields/rich-text/monaco/index.tsx
Add Line number to raw editor. 
Also make the error UI on the right-hand-side more visible
=> Line numbers

.changeset/nasty-boats-fry.md, packages/@tinacms/cli/src/cmds/init/index.ts
=> cleanup styling in tinacms init CLI

.changeset/real-toys-clean.md, packages/next-tinacms-dos/README.md, packages/next-tinacms-dos/src/handlers.ts
Adds a new optional configuration property to the DO media handler to specify a `mediaRoot` to store media.
Demo
[![Alt text](https://img.youtube.com/vi/0kpnurlbk2w/0.jpg)](https://www.youtube.com/watch?v=0kpnurlbk2w)
=> feat: ENG-806: configurable dos media store base directory

.changeset/angry-hats-design.md, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchBanner.tsx, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchSwitcher.tsx, packages/@tinacms/toolkit/src/plugins/branch-switcher/types.ts, packages/tinacms/package.json, packages/tinacms/src/internalClient/index.ts, pnpm-lock.yaml
https://user-images.githubusercontent.com/5075484/219146400-9e5f9b2f-f194-4c59-ad20-e83be5536464.mp4
=> Fix Create Branch

.changeset/itchy-windows-sing.md, packages/@tinacms/schema-tools/src/types.ts
Closes https://github.com/tinacms/tinacms/issues/3621
=> Fix issue where return type for  was incorrect

.changeset/quick-phones-chew.md, packages/@tinacms/schema-tools/src/schema/resolveField.ts
fix recent regression: https://github.com/tinacms/tinacms/commit/a0f655a1ab0eafacc0dd56fc1bfdfac5d8056e13#diff-421505360e5ff613592d15eba5619a6c3e195357e53df9c0bc8a4f380bce2f2bR98
=> fix: templates regression

.changeset/little-mice-applaud.md, packages/create-tina-app/src/examples.ts
add docusaurus to CLI 
closes ENG-835
=> feat: Add docusaurus starter to cli

packages/@tinacms/cli/src/cmds/statusChecks/checkClientInformation.ts
=> Fix CLI Typo

packages/@tinacms/cli/src/next/commands/build-command/index.ts
Wait for DB before checking schema.
=> wait for DB before checking schema

packages/@tinacms/toolkit/src/components/media/media-manager.tsx
Replaces the window confirm function with a styled modal. Fixes an issue where the media preview pane was left open after deleting.
=> Media Delete Modal

.changeset/curvy-ducks-sleep.md, packages/@tinacms/toolkit/src/components/media/media-item.tsx, packages/@tinacms/toolkit/src/components/media/media-manager.tsx
Fix regression with thumbails. We were trying to grab thumbnails off of directory and blowing up
=> Nested thumbnails fix

.changeset/poor-wombats-love.md, examples/kitchen-sink/.tina/config.tsx, packages/@tinacms/schema-tools/src/schema/resolveField.ts, packages/@tinacms/toolkit/src/packages/fields/components/ImageUpload/ImageUpload.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/ListFieldPlugin.tsx
This adds list support for the image field type and improves the UI for the base image field. 
closes ENG-845
=> Image List Component

.changeset/green-birds-own.md, packages/@tinacms/mdx/src/next/tests/image-in-link/field.ts, packages/@tinacms/mdx/src/next/tests/image-in-link/in.md, packages/@tinacms/mdx/src/next/tests/image-in-link/index.test.ts, packages/@tinacms/mdx/src/next/tests/image-in-link/node.json, packages/@tinacms/mdx/src/next/tests/image-in-link/out.md, packages/@tinacms/toolkit/src/components/media/utils.ts, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/index.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/create-img-plugin/component.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/create-img-plugin/index.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/ui/components.tsx, pnpm-lock.yaml
- Stop treating images as block-level
- Fix issue where images inside links were being stripped out
- Fix display of .avif images in the media manager
=> Fix issues with images being treated as blocks

packages/@tinacms/cli/src/next/commands/build-command/index.ts
The description of `--tina-graphql-version` was incorrect
=> update the description of --tina-graphql-version flag

.changeset/strong-humans-hide.md, packages/@tinacms/graphql/src/build.ts
Closes https://github.com/tinacms/tinacms/issues/3727
=> Fix regression from Tina client not having referenceDepth provided

package.json, pnpm-lock.yaml
Prettier test output! https://github.com/tinacms/tinacms/actions/runs/4492377423/jobs/7902171166?pr=3729
=> Update turbo, add color to some commands

.changeset/khaki-peaches-reply.md, packages/@tinacms/cli/src/next/commands/audit-command/index.ts, packages/@tinacms/cli/src/next/commands/build-command/index.ts, packages/@tinacms/cli/src/next/commands/dev-command/index.ts, packages/@tinacms/cli/src/next/database.ts, packages/@tinacms/graphql/src/level/tinaLevel.ts
Closes https://github.com/tinacms/tinacms/issues/3742
=> Fix issue where datalayer-port option wasn't being used

.changeset/lazy-cooks-try.md, packages/@tinacms/cli/src/cmds/forestry-migrate/index.ts, packages/@tinacms/graphql/src/database/index.ts
Updates the warning message to improve forestry migration.
=> better error messages

.changeset/thin-cobras-perform.md, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchBanner.tsx
=> Truncate branch

.changeset/slimy-seas-rest.md, packages/@tinacms/toolkit/src/packages/fields/components/ImageUpload/ImageUpload.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx
I was also in the process of fixing the collection list page on mobile, but I didn't get that working in time to include it in this PR. I'll return to that work next week.
=> Template Menu Fix, Image Field Button Placement

.changeset/sweet-grapes-fix.md, packages/tinacms/src/admin/index.tsx, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionDuplicatePage.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx
Add the ability to duplicate documents from collection list
https://www.loom.com/share/a052bbb2463945139c85c8978aef8afe
=> feat: Add ability to duplicate documents

packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx
cc @kldavis4 
Fixes https://github.com/tinacms/tinacms/pull/3855#issuecomment-1521866712
=> fix issue with backwards navigation in a collection update page

.changeset/rotten-turtles-tan.md, packages/tinacms/src/admin/components/GetCollection.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx
Fixes issue where auto-edit of single document collections was not updated to use the new `/collections/edit` route
=> fix: bug in auto-edit of single document collections

.changeset/cuddly-roses-explode.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx
Fix issue where sortFields are undefined.
=> Fix collection templates

.changeset/old-crews-hammer.md, packages/tinacms/src/admin/components/GetCollection.tsx
See thread on this ticket for background https://github.com/tinacms/tinacms/issues/3870#issuecomment-1529717941
=> fix: issue where collection is read only with a single document not working with folders

.changeset/new-grapes-buy.md, examples/kitchen-sink/package.json, pnpm-lock.yaml
I noticed that the workspace dependency had the version in it _I think_ this might be what is causing our publish to fail.
=> fix kitchen sink workspace dep issue

.changeset/sixty-maps-exist.md, packages/@tinacms/graphql/src/database/datalayer.ts, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/database/level.ts, packages/@tinacms/graphql/src/resolver/filter-utils.test.ts, packages/@tinacms/graphql/src/resolver/filter-utils.ts
=> feat: add support for filtering on list fields

.changeset/angry-horses-occur.md, packages/@tinacms/graphql/src/resolve.ts, packages/@tinacms/graphql/src/resolver/index.ts
=> Fix empty reference

.changeset/kind-years-film.md, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/index.tsx
Fixes this issue: https://www.loom.com/share/3bb0163cccaf4db1949fb0a60fdffc93
=> Add array check to value.children

.changeset/dirty-fireants-stare.md, .changeset/four-tomatoes-learn.md, packages/@tinacms/cli/src/next/commands/dev-command/server/media.ts, packages/@tinacms/cli/src/server/models/media.ts, packages/@tinacms/toolkit/src/components/media/media-item.tsx, packages/@tinacms/toolkit/src/components/media/media-manager.tsx, packages/@tinacms/toolkit/src/components/media/modal.tsx, packages/@tinacms/toolkit/src/packages/core/media-store.default.ts, packages/next-tinacms-cloudinary/package.json, packages/next-tinacms-cloudinary/src/handlers.ts, packages/next-tinacms-dos/package.json, packages/next-tinacms-dos/src/handlers.ts, packages/next-tinacms-s3/package.json, packages/next-tinacms-s3/src/handlers.ts
Fixes ENG-955
Fixes ENG-25
Fixes #2343
Demo: https://www.loom.com/share/725629c889c14eeaa34a427b44dca7af
Testing
=> New image uploads

.changeset/witty-spoons-build.md, packages/@tinacms/app/src/lib/graphql-reducer.ts
Fix issue where activeField search param would be called twice, resulting in the incorrect form being focused.
=> Fix issue where activeField search param would be called twice

packages/tinacms/src/admin/index.tsx, packages/tinacms/src/tina-cms.tsx
Update UI for branch not existing
Changes:
- Show branch modal regardless of your page
- Tweak messaging to make it seem less "error'ey"
- Don't allow user to dismiss modal
=> Missing branch ux

.changeset/gorgeous-bobcats-drop.md, .changeset/unlucky-doors-guess.md, packages/@tinacms/cli/src/next/commands/baseCommands.ts, packages/@tinacms/cli/src/next/commands/dev-command/server/media.ts
Also fixes an issue where uncaught errors in the CLI would exit silently
=> Fix issue where images with spaces in their names wouldn't upload properly

.changeset/odd-adults-call.md, packages/tinacms/package.json
See: https://www.loom.com/share/72eb540987f445f5822c3284f62d7119?sid=59dc9ce5-221b-4aa9-a8d9-ea09a5c2ecf4 for more context.
Fixes: ENG-1034
=> remove type module from the tinacms package

.changeset/brown-hairs-clean.md, packages/@tinacms/toolkit/src/packages/fields/components/ImageUpload/ImageUpload.tsx, packages/@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/create-img-plugin/component.tsx
- Updates the image upload component to fix issues with file name truncation, focus styles & maximum image height.
- Updates the MDX image plugin to match the UI for the image field.
=> Image Field

.changeset/quick-pants-visit.md, packages/@tinacms/toolkit/src/packages/form-builder/FormBuilder.tsx, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchSwitcher.test.tsx, packages/@tinacms/toolkit/src/plugins/branch-switcher/BranchSwitcher.tsx, packages/tinacms/src/admin/pages/IndexingPage.tsx
- Update pull request title to include the branch name
- Slugify brach name when typing in the title
=> Slugify branch name

.changeset/clever-ladybugs-fry.md, packages/@tinacms/toolkit/src/packages/fields/plugins/GroupListFieldPlugin.tsx
=> fix: draggable style & class overrides

.changeset/smart-kids-complain.md, packages/@tinacms/toolkit/src/packages/form-builder/FormBuilder.tsx
=> Update branch modal

.changeset/tall-eyes-explode.md, packages/next-tinacms-cloudinary/src/cloudinary-media-store.ts
=> save https value on cloudinary upload

.changeset/lemon-pots-float.md, packages/@tinacms/toolkit/src/components/media/media-manager.tsx, packages/@tinacms/toolkit/src/packages/core/media-store.default.ts
Fixes the issue in this thread: https://discord.com/channels/835168149439643678/1130685435832700949
=> fix: issue when uploading media in a folder with repo based media

.changeset/gold-grapes-give.md, examples/basic-iframe/tina/config.js, packages/@tinacms/schema-tools/src/types/index.ts, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx
Adds a second parameter to the slugify function that passes the current collection and template.
=> add meta parameter to slugify

.changeset/gentle-doors-cry.md, packages/@tinacms/schema-tools/src/types/index.ts, packages/tinacms/src/auth/TinaCloudProvider.tsx, packages/tinacms/src/hooks/use-content-creator.tsx, packages/tinacms/src/index.ts, packages/tinacms/src/internalClient/index.ts, packages/tinacms/src/toolkit/components/media/media-manager.tsx, packages/tinacms/src/toolkit/form-builder/form-builder.tsx, packages/tinacms/src/toolkit/plugin-branch-switcher/branch-switcher-legacy.tsx, packages/tinacms/src/toolkit/plugin-branch-switcher/branch-switcher.tsx, packages/tinacms/src/toolkit/plugin-branch-switcher/types.ts, packages/tinacms/src/toolkit/tina-cms.ts
Update the before submit types to not pass the finalForm form since it is contained in the TinaForm
=> Fix before submit types

packages/@tinacms/cli/src/cmds/init/templates/database.ts
In redis kv generated database.ts, validate the KV environment variables are set and throw an explanatory error if not
=> feat: ENG-1119: validate kv env vars

.changeset/itchy-boats-share.md, packages/@tinacms/app/src/lib/graphql-reducer.ts, packages/@tinacms/graphql/src/database/index.ts, packages/tinacms/src/admin/components/ErrorDialog.tsx, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx, packages/tinacms/src/index.ts
- Catch onPut / onDelete hook exceptions and bubble them up
- Update UI to display exception details in the error alert dialog
=> feat: ENG-1117: improve error messaging for onPut / onDelete

.changeset/gentle-bobcats-peel.md, packages/@tinacms/schema-tools/src/types/index.ts
=> make router optionally async

packages/tinacms-next-auth/src/cli.ts
Make NEXTAUTH_CREDENTIALS_KEY optional in users cli
closes ENG-1104
=> Make NEXTAUTH_CREDENTIALS_KEY optional

packages/@tinacms/cli/src/cmds/init/apply.ts, packages/@tinacms/cli/src/cmds/init/configure.ts, packages/@tinacms/cli/src/cmds/init/detectEnvironment.ts, packages/@tinacms/cli/src/cmds/init/index.ts
Always call addReactiveFile. Make the demo reactive page a GeneratedFile and rewrite depending on the configuration.
Currently this won't rewrite (preserving the current behavior) but it fixes the issue with the setup:user script not getting output.
=> fix: add reactive file

packages/@tinacms/cli/src/cmds/init/detectEnvironment.ts
Fixes an issue when using init and using a src directory.
Instead of putting content and demo content in src/pages we where adding it to src/
When using src/ use src/pages instead of src. 
cc @kldavis4
=> Fix src folder in init

packages/tinacms-next-auth/package.json, pnpm-lock.yaml
@kldavis4  This should fix the build
=> add bcryptjs to package.json

.changeset/polite-swans-leave.md, packages/@tinacms/app/src/Playground.tsx
=> fix issue with graphql playground button

packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/resolve.ts
Trying to fix https://github.com/tinacms/tinacms/pull/4205#issuecomment-1733695987
=> update lodash imports

examples/tina-self-hosted-demo/pages/api/auth/[...nextauth].ts, examples/tina-self-hosted-demo/pages/api/gql.ts, examples/tina-self-hosted-demo/tina/auth.ts, packages/tinacms-authjs/src/index.ts
Add all of the code needed for https://www.loom.com/share/4f41cf49b26249339da938043e25e538?sid=59b2f592-d839-47f1-80e1-e22da053d28a
=> make boilerplate easier to generate

.changeset/old-dodos-grab.md, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/hooks/embed-hooks.ts, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/plugins/soft-break/on-key-down-soft-break.ts
Fixes https://github.com/tinacms/tinacms/issues/4220
=> Use named import for is-hotkey package

.changeset/tough-mangos-tease.md, packages/@tinacms/schema-tools/src/schema/TinaSchema.ts
Fix handling of windows path separators in match property (fix #4210)
=> fix: #4210 file sep issue with collection match

packages/@tinacms/graphql/src/builder/index.ts
make required true in a collectionDocument
=> make required true in a collectionDocument

packages/@tinacms/cli/src/cmds/init/prompts/authenticationProvider.ts, packages/@tinacms/cli/src/cmds/init/prompts/types.ts, packages/@tinacms/cli/src/cmds/init/templates/config.ts
Adds the user collection to the config file in the init process if it does not exist.
=> Add user collection to init

packages/@tinacms/datalayer/src/backend/index.ts
Make sure the gql endpoint as auth turned on.
=> add secure: true to gql endpoint

packages/@tinacms/cli/package.json, packages/@tinacms/cli/src/cmds/init/apply.ts, packages/@tinacms/cli/src/cmds/init/codegen/index.ts, packages/@tinacms/cli/src/cmds/init/codegen/util.ts, packages/@tinacms/cli/src/cmds/init/detectEnvironment.ts, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/cli/src/cmds/init/prompts/databaseAdapter.ts, packages/@tinacms/cli/src/cmds/init/prompts/generatedFiles.ts, packages/@tinacms/cli/src/cmds/init/prompts/gitProvider.ts, packages/@tinacms/cli/src/cmds/init/prompts/index.ts, packages/@tinacms/cli/src/cmds/init/prompts/types.ts, pnpm-lock.yaml
- update the backend init to update the tina config using the typescript compiler api
- fix a bug in the overwrite logic for the api routes
=> feat: cli init update tina config

packages/@tinacms/cli/src/cmds/init/apply.ts, packages/@tinacms/cli/src/cmds/init/configure.ts, packages/@tinacms/cli/src/cmds/init/detectEnvironment.ts, packages/@tinacms/cli/src/cmds/init/index.ts
When doing init and using self hosted, add a content/users/index.json file
=> add users/index.json file when doing init

packages/tinacms-clerk/package.json, packages/tinacms-clerk/src/index.ts, packages/tinacms-clerk/src/tinacms.ts, pnpm-lock.yaml
Updates the `tinacms-clerk` package to use the new auth patterns
=> Fix clerk auth

packages/tinacms-clerk/src/index.ts, packages/tinacms-clerk/src/tinacms.ts
- Fixes a couple errors I found while dogfooding clerk auth
=> fix clerk auth and add orgId

examples/tina-self-hosted-demo/pages/api/tina/[...routes].ts, packages/@tinacms/auth/src/index.ts, packages/@tinacms/cli/src/cmds/init/apply.ts, packages/@tinacms/cli/src/cmds/init/codegen/index.ts, packages/@tinacms/cli/src/cmds/init/configure.ts, packages/@tinacms/cli/src/cmds/init/prompts/authProvider.ts, packages/@tinacms/cli/src/cmds/init/prompts/index.ts, packages/@tinacms/cli/src/cmds/init/prompts/types.ts, packages/@tinacms/cli/src/cmds/init/templates/config.ts, packages/@tinacms/cli/src/cmds/init/templates/tinaNextRoute.tsx, packages/@tinacms/datalayer/src/backend/index.ts, packages/tinacms-authjs/src/index.ts
=> refactor: authentication -> authProvider

packages/@tinacms/datalayer/src/backend/index.ts, packages/tinacms-authjs/src/index.ts
A couple of small(ish) Backend improvements
- Previously when using with a backend other then next.js one would have to fake. req.query.routes. Now that is handled. 
-  Add ability to pass a base path other then /api/tina/ (Currently will not work with NextAuth Default Session provider )
=> Backend improvements

packages/@tinacms/cli/src/cmds/init/apply.ts
Fix the generated users/index.json file
=> Fix users json file

packages/@tinacms/schema-tools/src/types/index.ts, packages/tinacms-authjs/src/tinacms.ts
Fix self hosted types so we don't get any errors in strict mode.
=> fix self hosted types

examples/kitchen-sink/package.json, examples/tina-self-hosted-demo/package.json, experimental-examples/tina-cloud-starter/package.json, packages/tinacms-authjs/src/tinacms.ts, packages/tinacms/src/auth/TinaCloudProvider.tsx, packages/tinacms/src/toolkit/components/account/update-password.tsx, packages/tinacms/src/toolkit/react-sidebar/components/nav.tsx, pnpm-lock.yaml
- update default authjs provider to not redirect on logout and handle at application level
- add option to the default authjs provider to enable redirect
- update mongodb-level to latest version with fix for clear() on sublevels
=> fix: no redirect on logout & update mongodb-level

packages/@tinacms/cli/src/cmds/init/apply.ts, packages/@tinacms/cli/src/cmds/init/configure.ts, packages/@tinacms/cli/src/cmds/init/detectEnvironment.ts, packages/@tinacms/cli/src/cmds/init/index.ts, packages/@tinacms/cli/src/cmds/init/prompts/databaseAdapter.ts, packages/@tinacms/cli/src/cmds/init/prompts/gitProvider.ts
A couple of small QOL updates that I noticed when going threw the demo with Scott.
- Updates verbiage on some of the questions (makes it a bit more clear with examples)
- removes looking at app router
-  I realized that  if the user is using the app router, adding the pages router example will still work because both the app router and pages router can be used at the same time. We ran into an issue where the entire init backend would break if the pages router is being used.
=> Minor Improvements

packages/tinacms/src/admin/components/Sidebar.tsx, packages/tinacms/src/toolkit/react-sidebar/components/nav.tsx, packages/tinacms/src/toolkit/react-sidebar/components/sidebar.tsx
=> feat: move user collection to site section of sidebar

packages/@tinacms/cli/src/cmds/init/prompts/databaseAdapter.ts, packages/@tinacms/cli/src/cmds/init/templates/config.ts
Fixes two issues with the generates files 
- If 'js' was chosen and mongoDB was chosen an error would occure as the generated file contains typescript. 
- if extra collections was not used it would generated `undefined,`
=> Fix generated files

.changeset/tender-singers-switch.md, packages/next-tinacms-s3/package.json
=> chore: correct typo in next-tinacms-s3 package.json

.changeset/nice-news-refuse.md, packages/tinacms/src/toolkit/form-builder/form-builder.tsx, packages/tinacms/src/toolkit/forms/form.ts
=> fix: update beforeSubmit logic to fix issue with saved changes indicator not working

packages/@tinacms/cli/src/cmds/init/prompts/databaseAdapter.ts
Updates init to work with the new version of upstash-redis-level
=> Update upstash redis level

.changeset/smart-kiwis-brake.md, packages/@tinacms/app/package.json, packages/tinacms/package.json, pnpm-lock.yaml
Fixes https://github.com/tinacms/tinacms/issues/4239
=> update final form

.changeset/happy-paws-arrive.md, packages/tinacms-authjs/package.json
Adds next 14 as a peer dep to authjs
=> Update peer deps in tinacms-authjs

.changeset/hip-turkeys-reply.md, packages/@tinacms/graphql/src/resolver/index.ts
Fixes https://github.com/tinacms/tinacms/issues/4355
=> Fix nested array issue

.changeset/heavy-chicken-reply.md, packages/tinacms/src/toolkit/core/media-store.default.ts
Update media store to use authProvider. 
Issue found in discord: https://discord.com/channels/835168149439643678/1176628245152681994/1176628245152681994
=> fix media store auth funtions

.changeset/lazy-needles-love.md, packages/@tinacms/graphql/src/resolver/index.ts
Explanation: https://www.loom.com/share/77fb42684ceb45478ca14c985a1ef61f
Issue found on discord: https://discord.com/channels/835168149439643678/1176757172139470858
cc @jeffsee55
=> fix resolveLegacyValues logic

.changeset/brave-cooks-collect.md, packages/tinacms/src/toolkit/react-cloud-config/cloud-config-plugin.tsx, packages/tinacms/src/toolkit/tina-cms.ts
Add Support link in sidebar, and fix icon for Users
=> Add support link

.changeset/shiny-baboons-itch.md, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/index.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/nested-form.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/plugins/create-link-plugin/index.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/plugins/ui/toolbar/index.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/plugins/ui/toolbar/toolbar-item.tsx
=> Fix issue where link form does not render.

.changeset/gentle-doors-move.md, packages/@tinacms/graphql/src/resolver/index.ts
Fixes https://github.com/tinacms/tinacms/discussions/4375
=> Fix saving empty list

.changeset/sweet-geese-check.md, packages/@tinacms/graphql/src/database/index.ts
Update Database.getLookup to support returning the full lookup
=> feat: allow full lookup to be retrieved from database

.changeset/few-flies-refuse.md, packages/tinacms/src/toolkit/react-sidebar/components/sync-status.tsx
sync-status was calling wrong isAuthenticated leading to console errors
=> fix: incorrect call to isAuthenticated

.changeset/real-masks-suffer.md, packages/@tinacms/cli/src/next/commands/build-command/index.ts, packages/@tinacms/cli/src/next/commands/build-command/waitForDB.ts
- add build cli command for specifying the upstream branch when using separate content repos
- add preview name / base branch for generating a preview branch
=> feat: support for overriding upstream branch and preview branch

.changeset/grumpy-clouds-float.md, packages/create-tina-app/src/examples.ts
Added demo docs starter to create-tina-app
=> create-tina-app - added demo docs

examples/tina-self-hosted-demo/package.json, packages/@tinacms/scripts/package.json, packages/@tinacms/scripts/src/index.ts
Fix watch script for window environment to run "pnpm watch command"
=> fix watch script for window environment

.github/workflows/main.yml
**Hey Team,** 
We have the ability to publish a build to npm if we add the label 'tagged'. However, currently we have to push a new commit after we add the 'tagged' label to actually trigger this. 
With this change, as soon as we add the label it will now re-build
=> 🛠️ Adds ability to re-build on tagged label

.changeset/clean-tips-impress.md
=> add changeset for #4567

.github/workflows/main.yml, .husky/pre-commit
Try to fix issue where changeset release PRs are not triggerring builds
=> 2041-build-changeset-prs

.github/workflows/e2e-dev.yml, .github/workflows/e2e.yml, .github/workflows/main.yml, .github/workflows/publish-pr.yml, .github/workflows/publish.yml, CONTRIBUTING.md, package.json
Trying to fix build issues on `main` - on last run, the `main.yml` workflow was successful, but `publish/yml` was not.
Trying to standardise package manager version selection via `corepack`
Updated GitHub Actions to reduce warnings in the logs
=> Fix build issues

.changeset/yellow-trains-roll.md
fixes publish workflow - there were example packages in a changeset
=> removed example packages from changeset

.github/workflows/publish.yml
trying to follow https://github.com/changesets/action/issues/187\#issuecomment-2142759223
=> publish workflow - try and fix publishing

.github/workflows/publish.yml
Attempt to fix https://github.com/tinacms/tinacms/actions/runs/9675295973/job/26692532439
=> fix publish token

.github/workflows/publish.yml
Attempt to fix: https://github.com/tinacms/tinacms/actions/runs/9708034175/job/26794165637
=> 🔧 Add fallback token to publish workflow

.changeset/proud-tables-clap.md, packages/@tinacms/cli/src/next/codegen/index.ts
Hello team, I noticed this link was broken but couldn't find a great alternative... I think think the one I added is the best option but open to suggestions. We might need a new page for this.
=> cli - fix broken link

.changeset/smooth-hotels-listen.md, packages/create-tina-app/bin/create-tina-app
=> Create-tina-app - Revert back to using require 

.changeset/chatty-beers-kick.md
=> changeset - tinacms update was incorrectly marked as a minor change

.changeset/calm-scissors-bathe.md, packages/tinacms/src/admin/components/Page.tsx, packages/tinacms/src/admin/pages/CollectionCreatePage.tsx, packages/tinacms/src/admin/pages/CollectionUpdatePage.tsx, packages/tinacms/src/toolkit/form-builder/form-builder.tsx
Fixes #4615
- Ensure padding between collection list page and singular pages are consistent
- Ensure navigation bar doesn't overlap with burger icon on smaller screens for the collections singular pages
**Figure: CollectionListPage and CollectionUpdatePage have consistent padding around the body**
**Figure: CollectionUpdatePage navigation bar not overlapping with the burger icon**
=> 💄 Collections - Enhance navigation UI on mobile screens

.changeset/cold-meals-occur.md, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/plugins/create-invalid-markdown-plugin/index.tsx
=> add emoji to error message for rich text editor 

.changeset/breezy-zoos-suffer.md, packages/create-tina-app/src/examples.ts
As per my conversation with @adamcogan and @wicksipedia css framework doesn't matter - React framework is more relevant.
=> create-tina-app - Change from Tailwind starter to NextJS starter

.changeset/good-tools-buy.md, examples/tina-self-hosted-demo/package.json, package.json, playwright/tina-playwright/components/Layout.js, playwright/tina-playwright/package.json, pnpm-lock.yaml
Update packages in example project to solve package vulnerability issue 
Override **loader-utils** and **ws** peer dependency packages with no vulnerabilities issue at the root 
Related PBI : #4474
=> fix packages critical vulnerabilities issue

examples/empty/package.json, playwright/tina-playwright/package.json
=> add missing version numbers

package.json
Attempt 2 https://github.com/tinacms/tinacms/pull/4668
=> update package.json with missing version number

.changeset/tidy-grapes-rhyme.md, packages/tinacms/src/toolkit/components/media/utils.ts
Implements https://github.com/tinacms/tina-cloud/issues/2078. 
Adding support for cloudinary supported files in the default supported file types
=> ✨ TinaCMS - Media Manager - Add support for uploading non-image files

.changeset/tall-mangos-bathe.md, packages/@tinacms/schema-tools/src/types/index.ts, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/index.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/index.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/plugins/ui/toolbar/index.tsx
=> add `toolbarOverride` option to `rich-text` fields

.changeset/ninety-spoons-notice.md, packages/create-tina-app/package.json, packages/create-tina-app/src/index.ts, packages/create-tina-app/src/util/examples.ts, pnpm-lock.yaml
Fixes https://github.com/tinacms/tina-cloud-starter/issues/523
Version of tar causing issue. 
**Before:**
**After:**
**Figure: This is using the tagged npm version**
=> fix create-tina-app

_docs/Definition-of-Done.md
This PR documents a Definition of Done for the TinaCMS project.
It draws guidance from the following sources:
- SSW Rule [Do you go beyond 'Done' and follow a 'Definition of Done'?](https://www.ssw.com.au/rules/definition-of-done/)
- SSW Rule [Do you make awesome documentation?](https://www.ssw.com.au/rules/awesome-documentation/)
=> 📝 Docs - Adds Definition of Done

.changeset/small-ties-pay.md, packages/tinacms/src/toolkit/fields/components/reference/reference-select.tsx
**Figure: Added an icon for reference selector field**
=> add icon to reference selector field

.changeset/rude-grapes-sort.md, packages/tinacms/src/toolkit/fields/components/reference/components/command.tsx, packages/tinacms/src/toolkit/fields/components/reference/reference-select.tsx
=> Fix reference field

.changeset/healthy-colts-behave.md, packages/tinacms/src/admin/pages/CollectionListPage.tsx, playwright/tina-playwright/tests/create-blog.spec.ts
Fixes #4667 by adding a path below the title.
**Figure: Collections page showing a path**
=> 💄 TinaCMS - Collections - Add file path

.changeset/hot-donkeys-lay.md, packages/tinacms/src/toolkit/components/media/media-manager.tsx
Fixes #4714. 
Ensure active item is not present on navigation and page reload
=> ♻️ Media Manager - Fix media manager active item

.changeset/healthy-spiders-stare.md, packages/@tinacms/graphql/package.json, playwright/tina-playwright/package.json, pnpm-lock.yaml
update axios and nodemon packages to latest version (they are low risk packages upgrade)
=> Fix vulnerable packages

.changeset/five-terms-retire.md, experimental-examples/kitchen-sink/tina/custom-component-reference-select/model.ts, experimental-examples/kitchen-sink/tina/custom-component-reference-select/reference-field-schema.tsx, packages/@tinacms/schema-tools/src/types/index.ts, packages/tinacms/src/toolkit/fields/components/reference/index.tsx, packages/tinacms/src/toolkit/fields/components/reference/model/reference-field-props.ts, packages/tinacms/src/toolkit/fields/components/reference/reference-select.tsx
> [!CAUTION]
> ⚠️ This will be deprecated in the **_near future._** 
- Adds a way to interact and filter a reference field.
=> 🚧 Experimental reference field filter

.changeset/spotty-ducks-think.md, packages/tinacms/src/toolkit/fields/components/reference/reference-select.tsx
fix race condition when fetch list of reference field
related bug [#4763](https://github.com/tinacms/tinacms/issues/4763)
=> Fix search in reference field selector

.changeset/modern-cougars-clap.md, packages/tinacms/src/toolkit/fields/components/reference/reference-select.tsx
=> Enable / in reference search

README.md
With @piers-sinclair
This is required for the [Internal Projects](https://sswcom.sharepoint.com/SitePages/Internal-Projects.aspx#2.-%E2%9C%A8-tinacms-(includes-sample-templates)) page, I am happy to move it somewhere better e.g.  a wiki
=> README - Add vision

packages/tinacms/README.md
tinacms | readme - use repo readme this is shown on the npm listing and should look presentable
=> tinacms | readme - improve npm readme

.changeset/fast-turkeys-study.md, .vscode/settings.json, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/templates-toolbar-button.tsx, packages/tinacms/src/toolkit/react-sidebar/components/nav.tsx
rich text editor | embed dropdown - adds filter to control + enables scrolling for long lists
filter is only visible when there are more than 10 entries
vscode - adding watcher excludes to try and speed it up 
fixes #4809
=> Rich text editor | embed dropdown - add scrolling

CONTRIBUTING.md
I've moved some content form the tina.io repo readme to this repo's documentation.
Specifically on how to run a local CMS instance with a web app.
=> 📝  Update CONTRIBUTING.md

.changeset/config.json, .github/workflows/publish.yml, package.json, pnpm-lock.yaml
publish - set git user + use changesets publish (this should tag the version)
it looks like github releases aren't created since a magic "new tag: " string isn't being outputted during the publish event - https://github.com/changesets/action/blob/3de3850952bec538fde60aac71731376e57b9b57/src/run.ts#L139
should be published with https://github.com/changesets/changesets/blob/689e54127fe059425c6be51e2802879b49b0b5d8/packages/cli/src/commands/publish/index.ts#L119
this was based off a random comment on https://github.com/changesets/action/issues/259
=> try to fix github releases + changesets

.github/workflows/main-generate-release-notes.yml, .github/workflows/publish.yml
publish workflow:
- steamlines into a single run
- uses outputs of changesets/action to conditionally publish beta tag or call release notes workflow
=> Fix-beta-publishing

.changeset/orange-dragons-type.md, packages/tinacms/src/cache/node-cache.ts, packages/tinacms/src/unifiedClient/index.ts
This was reproducible with a NextJS site using TinaCMS 2.2.6
=> Attempt to fix `fs` not found issue

.changeset/witty-meals-repeat.md, packages/tinacms/src/toolkit/react-sidebar/components/form-list.tsx
Fixes an issue where it is possible to have multiple forms with the same key in React.
=> ♻️ Add index to key

.vscode/settings.json, examples/tina-self-hosted-demo/components/blocks/content.tsx, examples/tina-self-hosted-demo/components/blocks/hero.tsx, examples/tina-self-hosted-demo/components/blocks/testimonial.tsx, experimental-examples/tina-cloud-starter/components/blocks/content.tsx, experimental-examples/tina-cloud-starter/components/blocks/hero.tsx, experimental-examples/tina-cloud-starter/components/blocks/testimonial.tsx
Removes code usages of deprecated TinaTemplate
fixes #1997
=> Removes code usages of deprecated TinaTemplate

.github/workflows/build-starter-templates.yml
Specify where the GitHub issue is to be created
=> Specify where the GitHub issue is to be created

.github/workflows/build-starter-templates.yml
- Fixed duplicate issue creation bug
=> Add Node version to GitHub issue title

.github/workflows/build-starter-templates.yml
Add missing " to build-all-templates workflow
=> Add missing " to build-all-templates workflow

.changeset/flat-feet-allow.md, .github/workflows/build-starter-templates.yml, packages/create-tina-app/src/templates.ts
- Remove `demo-docs` from build all templates action.
=> Remove `demo-docs` from `create-tina-app`

.changeset/light-sheep-tell.md, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/turn-into-dropdown-menu.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/plugins/core/common.tsx
Ensure that the mermaid button doesn't show up in the fixed-toolbar when a user is inside a table.
**Figure: Mermaid button not shown when user is inside a table**
**Figure: Mermaid button shows up when user is outside a table**
=> ♻️ Rich Text - Table Plugin - Add mermaid button to unsupported table type

_docs/dev-badge.md
Adds suggestions for types of things to build to earn a dev badge
=> dev-badge - add suggestions for what to build

.changeset/gorgeous-ligers-dress.md, packages/tinacms/src/toolkit/form-builder/form-builder.tsx, packages/tinacms/src/toolkit/styles/button.tsx
Request from @adamcogan  - "Save button too low" email task 
> 2. Button is enormous - check with Betty and Tiago what the correct size should be
As per conversation with @bettybondoc, we reduced the size of the button to improve the UI 😊
**Figure: Original Button Size**
**Figure: Button After Fix**
=> fix button sizing css

.changeset/soft-olives-draw.md, packages/@tinacms/cli/package.json, packages/@tinacms/graphql/src/database/bridge/isomorphic.test.ts, packages/@tinacms/graphql/src/spec/forestry-sample/requests.test.ts, packages/@tinacms/graphql/src/spec/movies-with-datalayer/requests.test.ts, packages/@tinacms/schema-tools/src/validate/index.spec.ts, pnpm-lock.yaml
- Updated **@types/fs-extra** from `^9.0.13` to `^11.0.4`
- Updated **@types/yup** from `^0.29.14` to `^0.32.0`
- Updated **yup** from `^0.32.11` to `^0.32.0`
=> ⬆️ Fixes some Issues with peer dependencies

.changeset/good-buses-mix.md, _docs/dev-badge.md, packages/@tinacms/cli/src/next/vite/index.ts, packages/tinacms/src/cache/node-cache.test.ts, packages/tinacms/src/cache/node-cache.ts
- Attempts to fix - #5226
Tested Build, 
- ✅ Locally 
- ✅ GitHub Pages
- ✅ Self hosted
- ✅ Vercel
=> 💚 Fix r.join is not a function

.github/workflows/e2e.yml, playwright/tina-playwright/.gitignore, playwright/tina-playwright/playwright.config.ts
=> Add playwright report summary in github action

.changeset/tame-pets-give.md, examples/kitchen-sink/package.json, examples/next-2024/package.json, packages/@tinacms/graphql/package.json, packages/@tinacms/mdx/package.json, packages/tinacms/package.json, pnpm-lock.yaml
Update packages to latest patch version to solve **critical** packages vulnerabilities
Updated packages
1. happy-dom
2. jsonpath-plus
=> Bug fix packages vulnerability

.changeset/brave-kids-thank.md, packages/create-tina-app/package.json, pnpm-lock.yaml
- Removed `got` package as it isn't used
**Figure: got package version `14.x.x` does not work with node version < 20**
=> Remove `got` package from `create-tina-app`

.changeset/pretty-pigs-jog.md, packages/@tinacms/schema-tools/src/util/parseZodErrors.ts, packages/@tinacms/schema-tools/src/validate/fields.ts, packages/@tinacms/schema-tools/src/validate/index.ts, packages/@tinacms/schema-tools/src/validate/schema.ts, packages/@tinacms/schema-tools/src/validate/util.ts
This PR improves the error messages for schema validation by adding additional information / formatting
=> Improve schema validation messages

.changeset/strong-weeks-turn.md, packages/create-tina-app/src/index.ts, packages/create-tina-app/src/templates.ts
- Adds the Astro Tina Starter 'https://github.com/tinacms/tina-astro-starter'
=> Add Tina Astro Starter template to create-tina-app

.changeset/eight-sloths-sip.md, packages/create-tina-app/src/templates.ts
=> feat: update template title for Astro Starter

.changeset/happy-bats-sip.md, packages/next-tinacms-s3/src/handlers.ts
Hey lads, quick fix. Been running into issue with cloudflare workers and their node.js compatibility and poly-fills. 
Figured i would suggest fixing this as this has started becoming the standard. Thanks!
=> add node:* prefix :)

.changeset/unlucky-zoos-tease.md, packages/next-tinacms-s3/src/handlers.ts, packages/next-tinacms-s3/src/s3-media-store.ts, packages/next-tinacms-s3/src/s3-tina-cloud-media-store.ts
Attempts to fix: https://github.com/tinacms/tinacms/issues/5523
feat: implement basePath handling in S3 media store for improved URL Management
=> Implement basePath handling in S3 media store

.vscode/extensions.json, .vscode/settings.json
=> Improve biome settings

.github/workflows/main.yml, packages/@tinacms/cli/src/next/commands/dev-command/index.ts, packages/@tinacms/graphql/src/database/datalayer.ts, packages/@tinacms/graphql/src/database/index.ts, packages/@tinacms/graphql/src/resolver/index.test.ts, packages/@tinacms/graphql/src/resolver/index.ts, packages/@tinacms/schema-tools/src/schema/TinaSchema.test.ts, packages/@tinacms/schema-tools/src/schema/TinaSchema.ts, packages/@tinacms/scripts/src/index.ts, packages/next-tinacms-s3/src/handlers.ts, packages/next-tinacms-s3/src/s3-media-store.ts, packages/next-tinacms-s3/src/s3-tina-cloud-media-store.ts, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/fixed-toolbar-buttons.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/code-block-toolbar-button.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/image-toolbar-button.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/indent-list-toolbar-button.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/link-toolbar-button.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/mark-toolbar-button.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/quote-toolbar-button.tsx, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/components/plate-ui/raw-markdown-toolbar-button.tsx, packages/tinacms/src/toolkit/react-sidebar/components/sidebar.tsx
this pr implements a code format check on prs and will fail if format detects
code formatting required.
=> feat: fail pr if `pnpm format` attempts to change things

.changeset/thirty-berries-glow.md, packages/@tinacms/cli/src/cmds/init/apply.ts, packages/create-tina-app/src/index.ts
As per email, `Tested Tina Starters`
=> Add a message to install Hugo

.changeset/great-schools-attack.md, packages/@tinacms/graphql/src/database/index.ts, packages/tinacms/src/admin/components/GetCollection.tsx
Adds support for filtering on fields in templates
If a collection has templates, all fields on all templates are indexed (unless they have conflicting types).
Addresses #5480
=> feat: add support for filtering on fields in templates

.changeset/tough-chicken-poke.md, packages/@tinacms/graphql/README.md, packages/@tinacms/graphql/_docs/Technologies-and-Architecture.md
This change does the following:
1. Moves the existing README to a separate `_docs` folder as per [SSW Rule "Do you make awesome documentation?"](https://www.ssw.com.au/rules/awesome-documentation/)
2. Removes obviously out-of-date material from the old material.
3. Adds a new README with links back to the TinaCMS project and an example of how to use the package.
=> 📝 Docs - Improve @tinacms/graphql README

.changeset/config.json
=> 📝 Config - reset ignore list in changeset configuration

.changeset/beige-eagles-pump.md, packages/tinacms/package.json, packages/tinacms/src/admin/components/ui/tooltip.tsx, packages/tinacms/src/admin/pages/CollectionListPage.tsx, pnpm-lock.yaml
This pull request introduces several updates to the `tinacms` package, including enhancements to the user interface, dependency upgrades, and tooltip functionality. The most significant changes involve making the "Add Folder" button more user-friendly by providing tooltips when the feature is unavailable, upgrading the `@radix-ui/react-tooltip` library, and refactoring imports for better code organization.
* The "Add Folder" button in the `CollectionListPage` now remains visible but is disabled when templates are used. A tooltip explains the restriction and provides a link to relevant documentation. (`packages/tinacms/src/admin/pages/CollectionListPage.tsx`, `packages/tinacms/src/admin/components/ui/tooltip.tsx`) [[1]](diffhunk://#diff-2e6ff4dd3c7fbe329897977dc4049884a984ef06511a1fb268a030 …
=> Collections - make add folder button always visible

.changeset/cold-ligers-smoke.md, packages/@tinacms/cli/src/cmds/init/detectEnvironment.ts, packages/@tinacms/scripts/bin/tina-build, packages/@tinacms/scripts/package.json, packages/@tinacms/scripts/src/index.ts, packages/@tinacms/scripts/src/utils.ts, pnpm-lock.yaml
This PR attempts to refactor the build script
Relates to #5663
=> refactor: build script

.changeset/tender-wasps-whisper.md, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/transforms/is-url.test.ts, packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/transforms/is-url.ts
Issue reported from the Discord: https://discord.com/channels/835168149439643678/1361716113007706162
This update introduces support for validating 'tel:' links in the isUrl function. The regex patterns have been modified to include a new regex for telephone links, ensuring that they are correctly identified as valid URLs. Additionally, the logic for determining valid URLs has been streamlined for better readability and efficiency.
- Added regex for 'tel:' links.
- Updated isUrl function to handle tel links alongside existing URL types.
Tests have been added to verify the new functionality.
=> Allow tel links

.changeset/strange-apes-exist.md, packages/tinacms/src/admin/components/GetDocument.tsx, packages/tinacms/src/toolkit/fields/components/reference/model/reference-link-props.ts, packages/tinacms/src/toolkit/fields/components/reference/reference-link.tsx
This pull request introduces enhancements to the TinaCMS codebase, focusing on improving functionality for document fetching and reference linking. Key changes include adding cancellation logic to prevent state updates for unmounted components, extending the `Document` type to include new fields, and refining the `ReferenceLink` component for better URL generation and error handling.
* [`packages/tinacms/src/admin/components/GetDocument.tsx`](diffhunk://#diff-aa0f03d2dc1874068768e9e5537bf9bac7ebac510b880c155079af43e2c62ffbR23-R61): Added a cancellation flag (`isCancelled`) to prevent state updates if the component is unmounted during asynchronous operations. Cleanup logic ensures requests are properly canceled.
* [`packages/tinacms/src/toolkit/fields/components/reference/model/reference-li …
=> ♻️ Improve "Edit in CMS" Button in Admin

.changeset/polite-rockets-sleep.md, packages/tinacms/src/admin/components/Sidebar.tsx, packages/tinacms/src/toolkit/react-sidebar/components/alert.tsx, packages/tinacms/src/toolkit/react-sidebar/components/nav.tsx, packages/tinacms/src/toolkit/react-sidebar/components/sidebar.tsx
Found on Discord - https://discord.com/channels/835168149439643678/1392188110867267815
**Figure: Now can close**
=> Fix Admin sidebar mobile view 

packages/@tinacms/graphql/tests/document-update-mutation/index.test.ts, packages/@tinacms/graphql/tests/document-update-mutation/posts/in.md, packages/@tinacms/graphql/tests/document-update-mutation/tina/config.ts, packages/@tinacms/graphql/tests/document-update-mutation/update-document-content.md, packages/@tinacms/graphql/tests/document-update-mutation/update-document-node.json, packages/@tinacms/graphql/tests/document-update-mutation/update-post-content.md, packages/@tinacms/graphql/tests/document-update-mutation/update-post-node.json
This change adds a basic automated test to ensure that fields can be updated in an existing document.
=> 🧪 GraphQL Test - Document update mutation

.changeset/perfect-toes-repeat.md, packages/create-tina-app/src/templates.ts, packages/create-tina-app/src/themes.ts
cc: @JackDevAU adding a missing devUrl
=> added missing devUrl

.changeset/old-brooms-lie.md, packages/tinacms/src/toolkit/components/tina-ui.test.tsx, packages/tinacms/src/toolkit/react-sidebar/components/sidebar.tsx, packages/tinacms/src/toolkit/styles/button.tsx
Sidebar - updated tooltips for hide/show buttons
Sidebar - when hidden, the show button is now orange
closes #5941 
https://github.com/user-attachments/assets/64e7d9f8-b30d-45bc-b7df-1dea6f8764ed
=> Sidebar - update tooltips

packages/create-tina-app/src/templates.ts
As per request in tina.io sprint review last week
=> create-tina-app - consistency of Next.js 

packages/create-tina-app/src/index.ts
As per https://github.com/tinacms/tina-docs/issues/257
**Figure: Added Extra prompts for someone with error msg**
=> add install dependencies step

.changeset/sweet-comics-build.md, packages/tinacms/src/toolkit/core/media-store.default.ts
When loading assets in TinaCMS we do a redundant call to the user GET endpoint just to check authentication.
As we already have logic in place to handle Unauthorized errors so when we do the call to get the assets, this authentication is handled.
Therefore by removing this extra call, we can speed up the media loading.
=> ⚡ Performance - Improve media load performance

packages/@tinacms/cli/src/next/vite/tailwind.ts, packages/tinacms/src/admin/pages/CollectionListPage.tsx
As per email task 
Added a roll-over effect 
https://github.com/user-attachments/assets/64d3a1c6-c203-41a7-a21c-760b9ce6a2b0
=> 💄UI - Add animated roll-over effect
